#!/bin/bash

app_name="WeChat"
wechat_path="/Applications/WeChat.app"
shell_path="$(dirname "$0")"
framework_name="WeChatPlugin"
app_content_path="${wechat_path}/Contents"
app_executable_path="${app_content_path}/MacOS/${app_name}"
app_executable_backup_path="${app_executable_path}_backup"
ori_frameowrk_path="${shell_path}/Products/Debug/${framework_name}.framework"
des_framework_path="${app_content_path}/Frameworks/${framework_name}.framework"

_install() {
    cp -R -H "${ori_frameowrk_path}" ${des_framework_path}
    ${shell_path}/insert_dylib --all-yes "@rpath/${framework_name}.framework/Versions/A/${framework_name}" "$app_executable_backup_path" "$app_executable_path"
    ${shell_path}/UpdateRemoteControlCommandsPlist.py
}

install() {
    # 判断是否已经存在备份文件 或者 是否强制覆盖安装
    if [ ! -f "$app_executable_backup_path" ] || [ -n "$1" -a "$1" = "--force" ]; then
        # 备份 WeChat 原始可执行文件
        cp "$app_executable_path" "$app_executable_backup_path"
        result="y"
    else
        read -t 150 -p "已安装微信小助手，是否覆盖？[y/n]:" result
    fi

    if [[ "$result" == 'y' ]]; then
        _install
    fi
}

uninstall() {
    # 备份WeChat原始可执行文件
    if [ -f "$app_executable_backup_path" ]; then
        rm "$app_executable_path"
        rm -rf "$framework_path"
        mv "$app_executable_backup_path" "$app_executable_path"

        if [ -f "$app_executable_backup_path" ]; then
            echo "卸载失败，请到 /Applications/WeChat.app/Contents/MacOS 路径，删除 WeChatPlugin.framework、WeChat 两个文件文件，并将 WeChat_backup 重命名为 WeChat"
        else
            echo "卸载成功"
        fi

    else
        echo "未发现微信小助手"
    fi
}

update() {
    # 备份 WeChat 原始可执行文件
    if [ ! -f "$app_executable_backup_path" ]; then
        cp "$app_executable_path" "$app_executable_backup_path"
    fi

    _install
}

help() {
    echo "WeChatPlugin [install/uninstall/update/help]"
    echo "    install:      安装插件"
    echo "    uninstall:    卸载插件"
    echo "    update:       更新插件"
    echo "    help:         帮助"
}

# 版本匹配
APP_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${app_content_path}/Info.plist")
PLUGIN_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${ori_frameowrk_path}/Resources/Info.plist")
if [ "${APP_VERSION}" != "${PLUGIN_VERSION}" ]; then
    read -t 150 -p "检测微信小助手版本(${PLUGIN_VERSION})和微信版本(${APP_VERSION})不匹配，是否继续安装？[y/n]:" result
    if [[ "$result" == 'y' ]]; then
        echo "如果发现奔溃等问题，请使用 WeChatPlugin uninstall 卸载"
    else
        exit 0
    fi
fi


if [ ! -d "$wechat_path" ]; then
    wechat_path="/Applications/微信.app"
    if [ ! -d "$wechat_path" ]; then
        echo "应用程序文件夹中未发现微信，请检查微信是否有重命名或者移动路径位置"
        exit -1
    fi
fi

# 对 WeChat 赋予权限
if [ ! -w "$wechat_path" ]; then
    echo "为了将小助手写入微信, 请输入密码 ： "
    sudo chown -R $(whoami) "$wechat_path"
fi

while [ $# -gt 0 ];do
    case $1 in
        install)
            install
            exit 0
            ;;
        uninstall)
            uninstall
            exit 0
            ;;
        update)
            update
            exit 0
            ;;
        help)
            help
            exit 0
            ;;
        ?)
            help
            exit -1
            ;;
    esac
done

help