//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MessageSender.h"

#import "ICdnComMgrExt-Protocol.h"
#import "MMCGIDelegate-Protocol.h"

@class CdnTaskInfo, NSString;

@interface AppMessageSender : MessageSender <ICdnComMgrExt, MMCGIDelegate>
{
    unsigned int _scene;
    CdnTaskInfo *m_oCurTaskInfo;
    NSString *m_nsFileAeskey;
    NSString *m_nsFileMsgSignature;
    NSString *m_nsFakeFileAeskey;
    NSString *m_nsFakeFileMsgSignature;
    NSString *m_nsMsgMd5;
    unsigned int m_uMsgCrc32;
}

@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
- (void).cxx_destruct;
- (void)startUploadBigFileWithoutHitCheck;
- (void)OnCdnUpload:(id)arg1;
- (void)OnCdnUploadProgress:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)handleFileMsg;
- (void)sendCGIWithoutUploadMedia;
- (void)startSending;
- (void)uploadSuccess:(BOOL)arg1;
- (void)uploadFail:(int)arg1;
- (void)uploadSuccessByCDN:(id)arg1;
- (void)uploadFailByCDN:(int)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (BOOL)sendAppMsgWithFileExists:(BOOL)arg1;
- (void)handleStartUploadFailed;
- (void)startUploadAppMsgByCDNWithHitCheck:(BOOL)arg1;
- (BOOL)createSendAppMsg;
- (BOOL)createAppAttachUpload;
- (BOOL)createCheckMd5Upload;
- (BOOL)createUploadAndSendAppMsg;
- (BOOL)startUploadAppMsgWithoutCDN;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

