//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FavoritesItemDataField, MessageData, NSString;

@protocol AppMessageHandlerDelegate <NSObject>

@optional
- (void)notifyAppMsgDownloadProgress:(NSString *)arg1 msgData:(MessageData *)arg2 downloadedBytes:(int)arg3 totalBytes:(int)arg4;
- (void)onAppRecordMsgDownloadFinish:(NSString *)arg1 msgData:(MessageData *)arg2 recordMsgData:(FavoritesItemDataField *)arg3;
- (void)onAppMsgDownloadFinish:(NSString *)arg1 msgData:(MessageData *)arg2 isSuccess:(BOOL)arg3;
- (void)notifyAppMsgUploadProgress:(NSString *)arg1 msgData:(MessageData *)arg2 uploadedBytes:(int)arg3 totalBytes:(int)arg4;
- (void)onAppMsgSendFinish:(NSString *)arg1 msgData:(MessageData *)arg2;
@end

