//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSData, NSDictionary, NSString;

@interface CBaseContact : NSObject <NSCoding>
{
    BOOL _m_isPlugin;
    unsigned int _m_uiConType;
    unsigned int _m_uiSex;
    unsigned int _m_uiType;
    unsigned int _m_uiChatState;
    unsigned int _m_uiDraftTime;
    unsigned int _m_uiQQUin;
    unsigned int _m_uiFriendScene;
    unsigned int _m_uiImgKey;
    unsigned int _m_uiExtKey;
    unsigned int _m_uiImgKeyAtLastGet;
    unsigned int _m_uiExtKeyAtLastGet;
    NSString *m_nsUsrName;
    NSString *_m_nsEncodeUserName;
    NSString *_m_nsAliasName;
    NSString *_m_nsNickName;
    NSString *_m_nsFullPY;
    NSString *_m_nsShortPY;
    NSString *_m_nsRemark;
    NSString *_m_nsRemarkPYShort;
    NSString *_m_nsRemarkPYFull;
    NSData *_m_dtUsrImg;
    NSString *_m_nsImgStatus;
    NSString *_m_nsHDImgStatus;
    NSString *_m_nsHeadImgUrl;
    NSString *_m_nsHeadHDImgUrl;
    NSString *_m_nsHeadHDMd5;
    NSString *_m_nsDraft;
    NSString *_m_nsAtUserList;
    NSString *_m_nsMobileIdentify;
    NSDictionary *_externalInfoJSONCache;
    NSString *_m_nsAntispamTicket;
    NSString *_m_nsDisplayNamePY;
}

@property(retain, nonatomic) NSString *m_nsDisplayNamePY; // @synthesize m_nsDisplayNamePY=_m_nsDisplayNamePY;
@property(retain, nonatomic) NSString *m_nsAntispamTicket; // @synthesize m_nsAntispamTicket=_m_nsAntispamTicket;
@property(retain, nonatomic) NSDictionary *externalInfoJSONCache; // @synthesize externalInfoJSONCache=_externalInfoJSONCache;
@property(readonly, nonatomic) BOOL m_isPlugin; // @synthesize m_isPlugin=_m_isPlugin;
@property(nonatomic) unsigned int m_uiExtKeyAtLastGet; // @synthesize m_uiExtKeyAtLastGet=_m_uiExtKeyAtLastGet;
@property(nonatomic) unsigned int m_uiImgKeyAtLastGet; // @synthesize m_uiImgKeyAtLastGet=_m_uiImgKeyAtLastGet;
@property(nonatomic) unsigned int m_uiExtKey; // @synthesize m_uiExtKey=_m_uiExtKey;
@property(nonatomic) unsigned int m_uiImgKey; // @synthesize m_uiImgKey=_m_uiImgKey;
@property(nonatomic) unsigned int m_uiFriendScene; // @synthesize m_uiFriendScene=_m_uiFriendScene;
@property(retain, nonatomic) NSString *m_nsMobileIdentify; // @synthesize m_nsMobileIdentify=_m_nsMobileIdentify;
@property(nonatomic) unsigned int m_uiQQUin; // @synthesize m_uiQQUin=_m_uiQQUin;
@property(retain, nonatomic) NSString *m_nsAtUserList; // @synthesize m_nsAtUserList=_m_nsAtUserList;
@property(nonatomic) unsigned int m_uiDraftTime; // @synthesize m_uiDraftTime=_m_uiDraftTime;
@property(retain, nonatomic) NSString *m_nsDraft; // @synthesize m_nsDraft=_m_nsDraft;
@property(retain, nonatomic) NSString *m_nsHeadHDMd5; // @synthesize m_nsHeadHDMd5=_m_nsHeadHDMd5;
@property(retain, nonatomic) NSString *m_nsHeadHDImgUrl; // @synthesize m_nsHeadHDImgUrl=_m_nsHeadHDImgUrl;
@property(retain, nonatomic) NSString *m_nsHeadImgUrl; // @synthesize m_nsHeadImgUrl=_m_nsHeadImgUrl;
@property(retain, nonatomic) NSString *m_nsHDImgStatus; // @synthesize m_nsHDImgStatus=_m_nsHDImgStatus;
@property(retain, nonatomic) NSString *m_nsImgStatus; // @synthesize m_nsImgStatus=_m_nsImgStatus;
@property(retain, nonatomic) NSData *m_dtUsrImg; // @synthesize m_dtUsrImg=_m_dtUsrImg;
@property(nonatomic) unsigned int m_uiChatState; // @synthesize m_uiChatState=_m_uiChatState;
@property(nonatomic) unsigned int m_uiType; // @synthesize m_uiType=_m_uiType;
@property(nonatomic) unsigned int m_uiSex; // @synthesize m_uiSex=_m_uiSex;
@property(retain, nonatomic) NSString *m_nsRemarkPYFull; // @synthesize m_nsRemarkPYFull=_m_nsRemarkPYFull;
@property(retain, nonatomic) NSString *m_nsRemarkPYShort; // @synthesize m_nsRemarkPYShort=_m_nsRemarkPYShort;
@property(retain, nonatomic) NSString *m_nsRemark; // @synthesize m_nsRemark=_m_nsRemark;
@property(retain, nonatomic) NSString *m_nsShortPY; // @synthesize m_nsShortPY=_m_nsShortPY;
@property(retain, nonatomic) NSString *m_nsFullPY; // @synthesize m_nsFullPY=_m_nsFullPY;
@property(retain, nonatomic) NSString *m_nsNickName; // @synthesize m_nsNickName=_m_nsNickName;
@property(nonatomic) unsigned int m_uiConType; // @synthesize m_uiConType=_m_uiConType;
@property(retain, nonatomic) NSString *m_nsAliasName; // @synthesize m_nsAliasName=_m_nsAliasName;
@property(retain, nonatomic) NSString *m_nsEncodeUserName; // @synthesize m_nsEncodeUserName=_m_nsEncodeUserName;
@property(retain, nonatomic) NSString *m_nsUsrName; // @synthesize m_nsUsrName;
- (void).cxx_destruct;
- (BOOL)isEqualToName:(id)arg1;
- (BOOL)isEqualToContact:(id)arg1;
- (id)getEncodeUserName;
- (BOOL)isValid;
- (BOOL)copyFrom:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

