//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CCNNavigationController, NSViewController;

@protocol CCNNavigationControllerDelegate <NSObject>

@optional
- (void)navigationController:(CCNNavigationController *)arg1 didPopViewController:(NSViewController *)arg2 animated:(BOOL)arg3;
- (void)navigationController:(CCNNavigationController *)arg1 willPopViewController:(NSViewController *)arg2 animated:(BOOL)arg3;
- (void)navigationController:(CCNNavigationController *)arg1 didShowViewController:(NSViewController *)arg2 animated:(BOOL)arg3;
- (void)navigationController:(CCNNavigationController *)arg1 willShowViewController:(NSViewController *)arg2 animated:(BOOL)arg3;
@end

