//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMViewController.h"

@class CCNNavigationControllerConfiguration, NSArray, NSMutableArray, NSViewController;
@protocol CCNNavigationControllerDelegate;

@interface CCNNavigationController : MMViewController
{
    NSMutableArray *_viewControllers;
    id <CCNNavigationControllerDelegate> _delegate;
    CCNNavigationControllerConfiguration *_configuration;
}

@property(retain, nonatomic) CCNNavigationControllerConfiguration *configuration; // @synthesize configuration=_configuration;
@property __weak id <CCNNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)navigationController:(id)arg1 didPopViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 willPopViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
@property(copy, nonatomic) NSArray *viewControllers;
@property(readonly, nonatomic) NSViewController *visibleViewController;
@property(readonly, nonatomic) NSViewController *topViewController;
- (void)setBackgroundColor:(id)arg1;
- (void)_transitionFromViewController:(id)arg1 toViewController:(id)arg2 animated:(BOOL)arg3 push:(BOOL)arg4;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)setViewControllers:(id)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithRootViewController:(id)arg1;

@end

