//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CBaseContact.h"

#import "NSCoding-Protocol.h"

@class CAppBrandInfo, ChatRoomData, ChatRoomDetail, NSArray, NSDictionary, NSString, SubscriptBrandInfo;

@interface CContact : CBaseContact <NSCoding>
{
    CAppBrandInfo *appBrandInfo;
    BOOL _m_isExtInfoValid;
    BOOL _m_isShowRedDot;
    BOOL _m_bFromNewDB;
    unsigned int _m_uiChatRoomStatus;
    unsigned int _m_uiChatRoomMaxCount;
    unsigned int _m_uiChatRoomVersion;
    unsigned int _m_uiCertificationFlag;
    unsigned int _m_uiNeedUpdate;
    int _m_iWCFlag;
    unsigned int _m_uiBrandSubscriptionSettings;
    unsigned int _m_uiChatRoomAccessType;
    unsigned int _m_uiDeleteFlag;
    unsigned int _m_uiLastUpdate;
    unsigned int _m_uiMetaFlag;
    unsigned int _m_uiDebugModeType;
    unsigned int _m_uiWxAppOpt;
    unsigned int _uiLastUpdateAppVersionInfoTime;
    NSDictionary *externalInfoJSONCache;
    NSString *_m_nsChatRoomMemList;
    NSString *_m_nsChatRoomAdminList;
    ChatRoomDetail *_m_ChatRoomDetail;
    NSString *_m_nsCountry;
    NSString *_m_nsProvince;
    NSString *_m_nsCity;
    NSString *_m_nsSignature;
    NSString *_m_nsCertificationInfo;
    NSString *_m_nsOwner;
    NSString *_m_nsFBNickName;
    NSString *_m_nsFBID;
    NSString *_m_nsWCBGImgObjectID;
    NSString *_m_pcWCBGImgID;
    NSString *_m_nsExternalInfo;
    NSString *_m_nsBrandSubscriptConfigUrl;
    SubscriptBrandInfo *_m_subBrandInfo;
    NSString *_m_nsBrandIconUrl;
    NSString *_m_nsChatRoomData;
    ChatRoomData *_m_ChatRoomData;
    NSString *_m_nsMobileHash;
    NSString *_m_nsMobileFullHash;
    NSString *_m_nsLinkedInID;
    NSString *_m_nsLinkedInName;
    NSString *_m_nsLinkedInPublicUrl;
    NSString *_m_nsDescription;
    NSString *_m_nsCardUrl;
    NSString *_m_nsWorkID;
    NSString *_m_nsLabelIDList;
    NSArray *_m_arrPhoneItem;
    NSString *_m_nsWeiDianInfo;
    CAppBrandInfo *_appBrandInfo;
}

+ (BOOL)isWeAppUserName:(id)arg1;
@property(retain, nonatomic) CAppBrandInfo *appBrandInfo; // @synthesize appBrandInfo=_appBrandInfo;
@property(nonatomic) unsigned int uiLastUpdateAppVersionInfoTime; // @synthesize uiLastUpdateAppVersionInfoTime=_uiLastUpdateAppVersionInfoTime;
@property(nonatomic) unsigned int m_uiWxAppOpt; // @synthesize m_uiWxAppOpt=_m_uiWxAppOpt;
@property(nonatomic) unsigned int m_uiDebugModeType; // @synthesize m_uiDebugModeType=_m_uiDebugModeType;
@property(nonatomic) unsigned int m_uiMetaFlag; // @synthesize m_uiMetaFlag=_m_uiMetaFlag;
@property(nonatomic) unsigned int m_uiLastUpdate; // @synthesize m_uiLastUpdate=_m_uiLastUpdate;
@property(nonatomic) BOOL m_bFromNewDB; // @synthesize m_bFromNewDB=_m_bFromNewDB;
@property(retain, nonatomic) NSString *m_nsWeiDianInfo; // @synthesize m_nsWeiDianInfo=_m_nsWeiDianInfo;
@property(retain, nonatomic) NSArray *m_arrPhoneItem; // @synthesize m_arrPhoneItem=_m_arrPhoneItem;
@property(retain, nonatomic) NSString *m_nsLabelIDList; // @synthesize m_nsLabelIDList=_m_nsLabelIDList;
@property(retain, nonatomic) NSString *m_nsWorkID; // @synthesize m_nsWorkID=_m_nsWorkID;
@property(retain, nonatomic) NSString *m_nsCardUrl; // @synthesize m_nsCardUrl=_m_nsCardUrl;
@property(retain, nonatomic) NSString *m_nsDescription; // @synthesize m_nsDescription=_m_nsDescription;
@property(nonatomic) unsigned int m_uiDeleteFlag; // @synthesize m_uiDeleteFlag=_m_uiDeleteFlag;
@property(retain, nonatomic) NSString *m_nsLinkedInPublicUrl; // @synthesize m_nsLinkedInPublicUrl=_m_nsLinkedInPublicUrl;
@property(retain, nonatomic) NSString *m_nsLinkedInName; // @synthesize m_nsLinkedInName=_m_nsLinkedInName;
@property(retain, nonatomic) NSString *m_nsLinkedInID; // @synthesize m_nsLinkedInID=_m_nsLinkedInID;
@property(retain, nonatomic) NSString *m_nsMobileFullHash; // @synthesize m_nsMobileFullHash=_m_nsMobileFullHash;
@property(retain, nonatomic) NSString *m_nsMobileHash; // @synthesize m_nsMobileHash=_m_nsMobileHash;
@property(nonatomic) BOOL m_isShowRedDot; // @synthesize m_isShowRedDot=_m_isShowRedDot;
@property(retain, nonatomic) ChatRoomData *m_ChatRoomData; // @synthesize m_ChatRoomData=_m_ChatRoomData;
@property(retain, nonatomic) NSString *m_nsChatRoomData; // @synthesize m_nsChatRoomData=_m_nsChatRoomData;
@property(nonatomic) unsigned int m_uiChatRoomAccessType; // @synthesize m_uiChatRoomAccessType=_m_uiChatRoomAccessType;
@property(nonatomic) BOOL m_isExtInfoValid; // @synthesize m_isExtInfoValid=_m_isExtInfoValid;
@property(retain, nonatomic) NSString *m_nsBrandIconUrl; // @synthesize m_nsBrandIconUrl=_m_nsBrandIconUrl;
@property(retain, nonatomic) SubscriptBrandInfo *m_subBrandInfo; // @synthesize m_subBrandInfo=_m_subBrandInfo;
@property(nonatomic) unsigned int m_uiBrandSubscriptionSettings; // @synthesize m_uiBrandSubscriptionSettings=_m_uiBrandSubscriptionSettings;
@property(retain, nonatomic) NSString *m_nsBrandSubscriptConfigUrl; // @synthesize m_nsBrandSubscriptConfigUrl=_m_nsBrandSubscriptConfigUrl;
@property(retain, nonatomic) NSString *m_nsExternalInfo; // @synthesize m_nsExternalInfo=_m_nsExternalInfo;
@property(retain, nonatomic) NSString *m_pcWCBGImgID; // @synthesize m_pcWCBGImgID=_m_pcWCBGImgID;
@property(nonatomic) int m_iWCFlag; // @synthesize m_iWCFlag=_m_iWCFlag;
@property(retain, nonatomic) NSString *m_nsWCBGImgObjectID; // @synthesize m_nsWCBGImgObjectID=_m_nsWCBGImgObjectID;
@property(nonatomic) unsigned int m_uiNeedUpdate; // @synthesize m_uiNeedUpdate=_m_uiNeedUpdate;
@property(retain, nonatomic) NSString *m_nsFBID; // @synthesize m_nsFBID=_m_nsFBID;
@property(retain, nonatomic) NSString *m_nsFBNickName; // @synthesize m_nsFBNickName=_m_nsFBNickName;
@property(retain, nonatomic) NSString *m_nsOwner; // @synthesize m_nsOwner=_m_nsOwner;
@property(retain, nonatomic) NSString *m_nsCertificationInfo; // @synthesize m_nsCertificationInfo=_m_nsCertificationInfo;
@property(nonatomic) unsigned int m_uiCertificationFlag; // @synthesize m_uiCertificationFlag=_m_uiCertificationFlag;
@property(retain, nonatomic) NSString *m_nsSignature; // @synthesize m_nsSignature=_m_nsSignature;
@property(retain, nonatomic) NSString *m_nsCity; // @synthesize m_nsCity=_m_nsCity;
@property(retain, nonatomic) NSString *m_nsProvince; // @synthesize m_nsProvince=_m_nsProvince;
@property(retain, nonatomic) NSString *m_nsCountry; // @synthesize m_nsCountry=_m_nsCountry;
@property(retain, nonatomic) ChatRoomDetail *m_ChatRoomDetail; // @synthesize m_ChatRoomDetail=_m_ChatRoomDetail;
@property(nonatomic) unsigned int m_uiChatRoomVersion; // @synthesize m_uiChatRoomVersion=_m_uiChatRoomVersion;
@property(nonatomic) unsigned int m_uiChatRoomMaxCount; // @synthesize m_uiChatRoomMaxCount=_m_uiChatRoomMaxCount;
@property(nonatomic) unsigned int m_uiChatRoomStatus; // @synthesize m_uiChatRoomStatus=_m_uiChatRoomStatus;
@property(retain, nonatomic) NSString *m_nsChatRoomAdminList; // @synthesize m_nsChatRoomAdminList=_m_nsChatRoomAdminList;
@property(retain, nonatomic) NSString *m_nsChatRoomMemList; // @synthesize m_nsChatRoomMemList=_m_nsChatRoomMemList;
- (void)setExternalInfoJSONCache:(id)arg1;
- (id)externalInfoJSONCache;
- (void).cxx_destruct;
- (id)getContactDisplayUsrName;
- (BOOL)isWeixinTeamContact;
- (id)getRemark;
- (id)getContactDisplayName;
- (BOOL)copyFieldFromContact:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)getFixBrandUrlValueForKey:(id)arg1;
- (id)getTitleKey:(id)arg1;
- (id)getBrandInfoItemAndRemoveIt:(id)arg1 fromArray:(id)arg2;
- (id)getBrandUrlValueForKey:(id)arg1;
- (BOOL)isContactValid;
- (BOOL)isBlockWeAppTemplateMessage;
- (BOOL)isBlockWeAppSessionMessage;
- (BOOL)isWeAppContact;
- (BOOL)isSimulatedNativeWeApp;
- (id)getAppID;
- (id)getAppBrandInfo;
- (BOOL)isAppBrandInfoValid;
- (id)getExternalInfoDictionary;
- (void)updateWithBizAttrChanged:(id)arg1;

@end

