//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MessageHandler.h"

@class FIFOQueue, NSMutableDictionary, NSRecursiveLock;
@protocol ImgMessageHandlerDelegate;

@interface ImgMessageHandler : MessageHandler
{
    FIFOQueue *m_downloadQueue;
    unsigned long long m_downloadTaskId;
    NSMutableDictionary *m_dictDownloadTask;
    NSRecursiveLock *m_oLockForDictDownloadTask;
    id <ImgMessageHandlerDelegate> m_delegate;
}

@property(nonatomic) __weak id <ImgMessageHandlerDelegate> delegate; // @synthesize delegate=m_delegate;
- (void).cxx_destruct;
- (void)notifyCheckQQ;
- (void)modifyMsgField:(id)arg1 msgData:(id)arg2 bitSet:(unsigned int)arg3;
- (void)notifyUploadProgress:(id)arg1 msgData:(id)arg2 uploadedBytes:(int)arg3 totalBytes:(int)arg4;
- (void)onSendFinished:(id)arg1 taskId:(unsigned long long)arg2 msgData:(id)arg3;
- (void)addMsgToSendQueue:(id)arg1 msgData:(id)arg2;
- (id)init;

@end

