//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MMCTTextView, NSImageView, NSString;

@interface JSApiScopeConfirmTableViewCell : NSTableCellView
{
    NSImageView *_selectImage;
    MMCTTextView *_scopeLabel;
    BOOL _isMustSelect;
    BOOL _isSelect;
    NSString *_scopeDescription;
}

+ (unsigned long long)verticalMarginWithWidth:(unsigned long long)arg1;
+ (unsigned long long)viewHeightWithScopeText:(id)arg1 width:(unsigned long long)arg2;
@property(nonatomic) BOOL isSelect; // @synthesize isSelect=_isSelect;
@property(nonatomic) BOOL isMustSelect; // @synthesize isMustSelect=_isMustSelect;
@property(retain, nonatomic) NSString *scopeDescription; // @synthesize scopeDescription=_scopeDescription;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateScopeLabel;
- (void)upadteSelectImage;
- (void)updateView;

@end

