//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class JSApiScopeConfirmWindow, MMTableView, NSButton, NSImageView, NSMutableArray, NSScrollView, NSString, NSTextField;

@interface JSAPIScopeConfirmContainterView : NSView <NSTableViewDataSource, NSTableViewDelegate>
{
    NSView *_contentView;
    NSTextField *_titleLabel;
    NSView *_titleSplitLine;
    NSImageView *_appIconImageView;
    NSTextField *_scopeDescriptionLabel;
    NSView *_tableSplitLine;
    MMTableView *_scopeTableView;
    NSScrollView *_scopeScrollView;
    NSView *_buttonSplitLine;
    NSView *_buttonVerticalSpliteLine;
    NSButton *_cancelButton;
    NSButton *_confirmButton;
    NSMutableArray *_arrSelect;
    JSApiScopeConfirmWindow *_weakConfirmWindow;
}

@property(nonatomic) __weak JSApiScopeConfirmWindow *weakConfirmWindow; // @synthesize weakConfirmWindow=_weakConfirmWindow;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)onClickButtonClose:(id)arg1;
- (void)onClickButtonCancel:(id)arg1;
- (void)onClickButtonConfirm:(id)arg1;
- (id)titleText;
- (double)designTableHeightToContentWidthRatio;
- (double)designNoTableContentHeightToContentWidthRatio;
- (unsigned long long)designContentWidth;
- (struct CGRect)contentViewFrame;
- (void)layoutSubviews;
- (void)initTableView;
- (void)initView;
- (void)initData;
- (id)confirmWindow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

