//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt-Protocol.h"
#import "MMService-Protocol.h"
#import "SDWebImageManagerDelegate-Protocol.h"
#import "TaskInstanceDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString, TaskSetting;

@interface LocalTaskCenter : MMService <SDWebImageManagerDelegate, TaskInstanceDelegate, AccountServiceExt, MMService>
{
    BOOL _isShowingAlert;
    BOOL _isLaunching;
    NSRecursiveLock *_taskLock;
    TaskSetting *_myConfig;
    NSMutableDictionary *_taskInstances;
    NSMutableDictionary *_jumpPairTask;
    NSMutableDictionary *_pendingLaunchMap;
    NSMutableArray *_waitingInstanceArray;
    NSMutableDictionary *_IDKeyReportDic;
    NSMutableDictionary *_IDKeyReportDic2;
    NSMutableDictionary *_seqNOOfTnstance;
}

@property(retain, nonatomic) NSMutableDictionary *seqNOOfTnstance; // @synthesize seqNOOfTnstance=_seqNOOfTnstance;
@property(retain, nonatomic) NSMutableDictionary *IDKeyReportDic2; // @synthesize IDKeyReportDic2=_IDKeyReportDic2;
@property(retain, nonatomic) NSMutableDictionary *IDKeyReportDic; // @synthesize IDKeyReportDic=_IDKeyReportDic;
@property(nonatomic) BOOL isLaunching; // @synthesize isLaunching=_isLaunching;
@property(retain, nonatomic) NSMutableArray *waitingInstanceArray; // @synthesize waitingInstanceArray=_waitingInstanceArray;
@property(retain, nonatomic) NSMutableDictionary *pendingLaunchMap; // @synthesize pendingLaunchMap=_pendingLaunchMap;
@property(retain, nonatomic) NSMutableDictionary *jumpPairTask; // @synthesize jumpPairTask=_jumpPairTask;
@property(retain, nonatomic) NSMutableDictionary *taskInstances; // @synthesize taskInstances=_taskInstances;
@property(retain, nonatomic) TaskSetting *myConfig; // @synthesize myConfig=_myConfig;
@property(retain, nonatomic) NSRecursiveLock *taskLock; // @synthesize taskLock=_taskLock;
@property(nonatomic) BOOL isShowingAlert; // @synthesize isShowingAlert=_isShowingAlert;
- (void).cxx_destruct;
- (void)doSendEventToClient:(id)arg1 withIndex:(int)arg2 withDict:(id)arg3;
- (void)receiveTaskDataEvent:(struct __CFData *)arg1;
- (BOOL)isGlobalEvent:(int)arg1;
- (id)getDebugContact:(id)arg1;
- (void)doLaunchDebugMiniProgramInternal:(id)arg1;
- (void)doLaunchDebugMiniProgram:(id)arg1;
- (void)doLaunchMiniProgramFromBrand:(id)arg1;
- (void)doLaunchMiniProgram:(id)arg1;
- (void)doLaunchMiniProgramNavigateBack:(id)arg1;
- (void)doLaunchMiniProgramNavigateTo:(id)arg1;
- (id)getTaskIdentifier:(id)arg1;
- (void)taskDidEnd:(id)arg1;
- (void)taskDidConnected:(id)arg1;
- (void)taskDidFinishLaunch:(id)arg1;
- (void)taskDidStart:(id)arg1;
- (void)getReturnMsg:(id)arg1;
- (void)setCurSeqNO:(int)arg1 withKey:(id)arg2;
- (int)getNextSeqNO:(id)arg1;
- (void)doConfirm:(id)arg1;
- (void)reportTotalCost:(long long)arg1;
- (id)instanceForKey:(id)arg1;
- (void)removeInstance:(id)arg1;
- (void)doNextTaskInstance;
- (void)checkAndStartInstance:(id)arg1;
- (void)scrollStatusChangeNotifiy:(id)arg1;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (id)loadTaskExtendConfigure;
- (void)updateTaskConfigureIfNeeded:(id)arg1;
- (void)loadBaseTaskConfigure;
- (void)onServiceTerminate;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

