//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "SDWebImageManagerDelegate-Protocol.h"

@class CAShapeLayer, CContact, MMView, NSImageView, NSString, NSTextField;

@interface MMAppProfileMessageCellView : MMMessageCellView <SDWebImageManagerDelegate>
{
    CContact *_contactCardData;
    MMView *_containerView;
    NSImageView *_contactCardAvatar;
    NSTextField *_contactCardNickName;
    NSString *_stripeHeading;
    CAShapeLayer *_strokeLayer;
    MMView *_divider;
    NSTextField *_stripeHeadingTextField;
}

+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
@property(retain, nonatomic) NSTextField *stripeHeadingTextField; // @synthesize stripeHeadingTextField=_stripeHeadingTextField;
@property(retain, nonatomic) MMView *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain, nonatomic) NSString *stripeHeading; // @synthesize stripeHeading=_stripeHeading;
@property(retain, nonatomic) NSTextField *contactCardNickName; // @synthesize contactCardNickName=_contactCardNickName;
@property(retain, nonatomic) NSImageView *contactCardAvatar; // @synthesize contactCardAvatar=_contactCardAvatar;
@property(retain, nonatomic) MMView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) CContact *contactCardData; // @synthesize contactCardData=_contactCardData;
- (void).cxx_destruct;
- (id)getReferMenuItem;
- (void)webImageManager:(id)arg1 didFinishWithImage:(id)arg2;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (void)showProfile:(id)arg1;
- (BOOL)draggingEnabled;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (struct CGRect)clickableArea;
- (id)getOperationMenuItem;
- (void)updateHighlightMaskView;
- (struct CGRect)bubbleFrame;
- (void)updateMessageLayer;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

