//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMView.h"

@class NSColor;

@interface MMAppReferContainerView : MMView
{
    BOOL _ignoreEvent;
    double _cornerRadius;
    NSColor *_normalColor;
    NSColor *_highlightColor;
}

@property(retain, nonatomic) NSColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(retain, nonatomic) NSColor *normalColor; // @synthesize normalColor=_normalColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) BOOL ignoreEvent; // @synthesize ignoreEvent=_ignoreEvent;
- (void).cxx_destruct;
- (void)setHighlighted:(BOOL)arg1;
- (id)initWithCornerRadius:(double)arg1 normalColor:(id)arg2 highlightColor:(id)arg3 frameRect:(struct CGRect)arg4;

@end

