//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSMutableDictionary, NSString;

@interface MMAppWindowSizeManger : MMService <MMService>
{
    NSMutableDictionary *_shouldUseWidescreenDic;
}

@property(retain, nonatomic) NSMutableDictionary *shouldUseWidescreenDic; // @synthesize shouldUseWidescreenDic=_shouldUseWidescreenDic;
- (void).cxx_destruct;
- (long long)getWAAppContentDefaultHeight;
- (long long)getWAAppContentDefaultWidth;
- (void)sendWAAppWidescreenNotificationWithAppID:(id)arg1;
- (void)setWidescreenFalgWithAppIP:(id)arg1 shouldUseWidescreen:(unsigned char)arg2;
- (long long)getAppContentHeightWith:(id)arg1;
- (long long)getAppContentWidthWith:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

