//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImageView.h>

@interface MMAppReferImageView : NSImageView
{
    CDUnknownBlockType _rightMouseUpEventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType rightMouseUpEventBlock; // @synthesize rightMouseUpEventBlock=_rightMouseUpEventBlock;
- (void).cxx_destruct;
- (void)rightMouseUp:(id)arg1;

@end

