//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class MMTextAttachmentCell;

@interface MMAttachmentReusableView : NSView
{
    MMTextAttachmentCell *_attachmentCell;
    NSView *_containerView;
}

@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MMTextAttachmentCell *attachmentCell; // @synthesize attachmentCell=_attachmentCell;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;

@end

