//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMBasePreviewPanelWindowController, NSString;

@interface MMBasePreviewUIMgr : MMService <MMService>
{
    BOOL _isMessageMode;
    MMBasePreviewPanelWindowController *_previewPanelWindowController;
}

@property(nonatomic) BOOL isMessageMode; // @synthesize isMessageMode=_isMessageMode;
@property(retain, nonatomic) MMBasePreviewPanelWindowController *previewPanelWindowController; // @synthesize previewPanelWindowController=_previewPanelWindowController;
- (void).cxx_destruct;
- (void)ensurePreviewPanelClose;
- (void)openWithPreviewItem:(id)arg1;
- (void)previewPanelHandleCurrentFileParaInfo:(id)arg1 paraInfoList:(id)arg2;
- (void)previewPanelHandleCurrentFileDataField:(id)arg1 parentMessage:(id)arg2 parentFavItem:(id)arg3;
- (void)previewPanelHandleCurrentFileDataField:(id)arg1 parentDataField:(id)arg2;
- (void)previewPanelHandleFileHandoffItem:(id)arg1;
- (void)previewPanelHandleFileMessage:(id)arg1;
- (void)previewPanelHandleFileFavItem:(id)arg1;
- (void)openWithCurrentParaInfo:(id)arg1 paraInfoList:(id)arg2;
- (void)openWithCurrentDataField:(id)arg1 parentMessage:(id)arg2 orParentFavItem:(id)arg3;
- (void)openWithCurrentDataField:(id)arg1 parentDataField:(id)arg2;
- (void)openWithFavItemList:(id)arg1 AndInitialSelectedFavItem:(id)arg2;
- (void)openWithInitialSelectedMessage:(id)arg1;
- (void)closePreviewWindow;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

