//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FavoritesItemDataField, MessageData, NSString;

@interface MMCDNTask : NSObject
{
    unsigned int _localID;
    unsigned int _fileType;
    MessageData *_message;
    FavoritesItemDataField *_favItemData;
    NSString *_chatName;
    FavoritesItemDataField *_recordMsgData;
    NSString *_clientMediaID;
    NSString *_destinationPath;
    NSString *_authKey;
}

@property(retain, nonatomic) NSString *authKey; // @synthesize authKey=_authKey;
@property(nonatomic) unsigned int fileType; // @synthesize fileType=_fileType;
@property(retain, nonatomic) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
@property(retain, nonatomic) NSString *clientMediaID; // @synthesize clientMediaID=_clientMediaID;
@property(retain, nonatomic) FavoritesItemDataField *recordMsgData; // @synthesize recordMsgData=_recordMsgData;
@property(nonatomic) unsigned int localID; // @synthesize localID=_localID;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName=_chatName;
@property(retain, nonatomic) FavoritesItemDataField *favItemData; // @synthesize favItemData=_favItemData;
@property(retain, nonatomic) MessageData *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)description;

@end

