//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMIgnoreEventView.h"

@class MMImageView, MMTextField;

@interface MMChatsBannerCellView : MMIgnoreEventView
{
    MMImageView *_iconImageView;
    MMTextField *_descriptionLabel;
}

@property(retain, nonatomic) MMTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) MMImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (void)adjustLayout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

