//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatLogBaseCellView.h"

@class MMImageView, NSString;

@interface MMChatLogImageCellView : MMChatLogBaseCellView
{
    BOOL _isExpired;
    MMImageView *_thumbnailImageView;
    NSString *_imageFilePath;
}

+ (struct CGSize)imageSizeWithImage:(id)arg1 constrainedToWidth:(double)arg2;
+ (struct CGSize)imageSizeWithImagePath:(id)arg1 constrainedToWidth:(double)arg2;
+ (id)imageWithImagePath:(id)arg1;
@property(nonatomic) BOOL isExpired; // @synthesize isExpired=_isExpired;
@property(retain, nonatomic) NSString *imageFilePath; // @synthesize imageFilePath=_imageFilePath;
@property(retain, nonatomic) MMImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
- (void).cxx_destruct;
- (id)draggingImage;
- (id)originalFilePath;
- (BOOL)allowExport;
- (BOOL)allowAddToFavorites;
- (BOOL)allowForward;
- (BOOL)allowCopy;
- (struct CGRect)clickableArea;
- (void)openImagePreview;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

