//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMBasicSearchResult.h"

@class MMSessionInfo, NSArray;

@interface MMChatLogSearchResult : MMBasicSearchResult
{
    MMSessionInfo *_sessionInfo;
    NSArray *_results;
}

@property(retain, nonatomic) NSArray *results; // @synthesize results=_results;
@property(retain, nonatomic) MMSessionInfo *sessionInfo; // @synthesize sessionInfo=_sessionInfo;
- (void).cxx_destruct;
- (id)initWithSelectSession:(id)arg1 results:(id)arg2;

@end

