//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatLogBaseCellView.h"

@class NSImageView, NSTextField;

@interface MMChatLogWeAppCellView : MMChatLogBaseCellView
{
    NSImageView *_iconImageView;
    NSTextField *_titleTextField;
    NSTextField *_descTextField;
}

+ (double)cellHeightWithFavItemDataField:(id)arg1 parentMessage:(id)arg2 parentFavItem:(id)arg3 parentDataField:(id)arg4 constrainedToWidth:(double)arg5;
@property(retain, nonatomic) NSTextField *descTextField; // @synthesize descTextField=_descTextField;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(retain, nonatomic) NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)populateWithFavItemDataField:(id)arg1 parentDataField:(id)arg2;
- (void)populateWithFavItemDataField:(id)arg1 parentFavItem:(id)arg2;
- (void)populateWithFavItemDataField:(id)arg1 parentMessage:(id)arg2;
- (BOOL)allowExport;
- (BOOL)allowAddToFavorites;
- (BOOL)allowForward;
- (BOOL)allowCopy;
- (struct CGRect)clickableArea;
- (void)layoutSubViews:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

