//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class MMPlaceholderContainerView, MMSearchImageView, NSAttributedString, NSColor, NSFont, NSString;

@interface MMCustomSearchField : NSView
{
    BOOL _isHighlight;
    NSString *_placeholderString;
    NSAttributedString *_placeholderAttributedString;
    double _cornerRadius;
    NSColor *_backgroundColor;
    NSColor *_hightlightBackgroudColor;
    NSColor *_borderColor;
    NSColor *_highlightBorderColor;
    double _borderWidth;
    NSFont *_font;
    MMPlaceholderContainerView *_placeholderContainerView;
    MMSearchImageView *_imageView;
    CDUnknownBlockType _resetSearchBlock;
    CDUnknownBlockType _textDidChangeBlock;
    CDUnknownBlockType _didBecomeFirstResponderBlock;
    CDUnknownBlockType _didIsHightlightBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didIsHightlightBlock; // @synthesize didIsHightlightBlock=_didIsHightlightBlock;
@property(copy, nonatomic) CDUnknownBlockType didBecomeFirstResponderBlock; // @synthesize didBecomeFirstResponderBlock=_didBecomeFirstResponderBlock;
@property(copy, nonatomic) CDUnknownBlockType textDidChangeBlock; // @synthesize textDidChangeBlock=_textDidChangeBlock;
@property(copy, nonatomic) CDUnknownBlockType resetSearchBlock; // @synthesize resetSearchBlock=_resetSearchBlock;
@property(retain, nonatomic) MMSearchImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) MMPlaceholderContainerView *placeholderContainerView; // @synthesize placeholderContainerView=_placeholderContainerView;
@property(nonatomic) BOOL isHighlight; // @synthesize isHighlight=_isHighlight;
@property(retain, nonatomic) NSFont *font; // @synthesize font=_font;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) NSColor *highlightBorderColor; // @synthesize highlightBorderColor=_highlightBorderColor;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) NSColor *hightlightBackgroudColor; // @synthesize hightlightBackgroudColor=_hightlightBackgroudColor;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(retain, nonatomic) NSAttributedString *placeholderAttributedString; // @synthesize placeholderAttributedString=_placeholderAttributedString;
@property(retain, nonatomic) NSString *placeholderString; // @synthesize placeholderString=_placeholderString;
- (void).cxx_destruct;
- (BOOL)isTextEditing;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
@property(retain, nonatomic) NSString *inputValue;
- (id)initWithFrame:(struct CGRect)arg1;

@end

