//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class MMTextField, NSDateFormatter;

@interface MMDatePickerDemo : NSWindowController
{
    MMTextField *_datePickerInput;
    MMTextField *_datePickerInputEnd;
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property __weak MMTextField *datePickerInputEnd; // @synthesize datePickerInputEnd=_datePickerInputEnd;
@property __weak MMTextField *datePickerInput; // @synthesize datePickerInput=_datePickerInput;
- (void).cxx_destruct;
- (void)setupView;
- (void)windowDidLoad;

@end

