//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class MMSidebarColorIconView, MMSidebarLabelTextField, NSImage;

@interface MMFavSidebarHeaderRowView : NSTableRowView
{
    NSImage *_icon;
    NSImage *_arrowIcon;
    MMSidebarLabelTextField *_titleLabel;
    MMSidebarColorIconView *_iconView;
    MMSidebarColorIconView *_arrowIconView;
}

@property(retain, nonatomic) MMSidebarColorIconView *arrowIconView; // @synthesize arrowIconView=_arrowIconView;
@property(retain, nonatomic) MMSidebarColorIconView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) MMSidebarLabelTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSImage *arrowIcon; // @synthesize arrowIcon=_arrowIcon;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

