//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMFileMgrSearchTask : NSObject
{
    BOOL _isCancelled;
    double _createDate;
}

@property BOOL isCancelled; // @synthesize isCancelled=_isCancelled;
@property(nonatomic) double createDate; // @synthesize createDate=_createDate;
- (void)doSearchWithKeyword:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)cancel;
- (id)init;

@end

