//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSTextField, SVGImageView;

@interface MMFileSplitLeftSectionView : NSTableCellView
{
    BOOL _isFolder;
    NSTextField *_sectionName;
    SVGImageView *_iconView;
    long long _sectionIndex;
    CDUnknownBlockType _onSectionHeaderClick;
}

@property(copy, nonatomic) CDUnknownBlockType onSectionHeaderClick; // @synthesize onSectionHeaderClick=_onSectionHeaderClick;
@property(nonatomic) BOOL isFolder; // @synthesize isFolder=_isFolder;
@property(nonatomic) long long sectionIndex; // @synthesize sectionIndex=_sectionIndex;
@property(retain, nonatomic) SVGImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) NSTextField *sectionName; // @synthesize sectionName=_sectionName;
- (void).cxx_destruct;
- (void)updateStatus;
- (void)updateUI:(id)arg1 isInitial:(BOOL)arg2;
- (void)initViews;
- (void)mouseDown:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

