//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IMMSessionMgrExt-Protocol.h"
#import "IMessageExt-Protocol.h"
#import "MMCDNDownloadMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class AFHTTPSessionManager, MMCache, NSLock, NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface MMMessageCacheMgr : MMService <MMCDNDownloadMgrExt, IMMSessionMgrExt, IMessageExt, MMService>
{
    MMCache *_textMessageCache;
    MMCache *_translationCache;
    MMCache *_referCache;
    MMCache *_thumbImgCache;
    MMCache *_originImgCache;
    AFHTTPSessionManager *_downloadMgr;
    NSMutableDictionary *_cdnDownloadTasks;
    NSObject<OS_dispatch_queue> *_diskQueue;
    NSMutableDictionary *_downloadingOriginImageSet;
    NSLock *_m_lock;
}

+ (void)clearOldMessageFilesAtFolder:(id)arg1;
+ (void)clearOldMessageFiles;
@property(retain, nonatomic) NSLock *m_lock; // @synthesize m_lock=_m_lock;
@property(retain, nonatomic) NSMutableDictionary *downloadingOriginImageSet; // @synthesize downloadingOriginImageSet=_downloadingOriginImageSet;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *diskQueue; // @synthesize diskQueue=_diskQueue;
@property(retain, nonatomic) NSMutableDictionary *cdnDownloadTasks; // @synthesize cdnDownloadTasks=_cdnDownloadTasks;
@property(retain, nonatomic) AFHTTPSessionManager *downloadMgr; // @synthesize downloadMgr=_downloadMgr;
@property(retain, nonatomic) MMCache *originImgCache; // @synthesize originImgCache=_originImgCache;
@property(retain, nonatomic) MMCache *thumbImgCache; // @synthesize thumbImgCache=_thumbImgCache;
@property(retain, nonatomic) MMCache *referCache; // @synthesize referCache=_referCache;
@property(retain, nonatomic) MMCache *translationCache; // @synthesize translationCache=_translationCache;
@property(retain, nonatomic) MMCache *textMessageCache; // @synthesize textMessageCache=_textMessageCache;
- (void).cxx_destruct;
- (void)setupDownloadMgr;
- (void)proxySettingsDidChange:(id)arg1;
- (void)loadImageWithMessage:(id)arg1;
- (void)cdnDownloadMgrDidFinishedDownloadWithChatName:(id)arg1 localID:(unsigned int)arg2 recordMsgData:(id)arg3 type:(int)arg4 isSuccess:(BOOL)arg5;
- (void)cdnDownloadMgrDidFailedDownloadWithChatName:(id)arg1 localID:(unsigned int)arg2 recordMsgData:(id)arg3 type:(int)arg4;
- (void)cdnDownloadMgrDidFinishedDownloadWithChatName:(id)arg1 localID:(unsigned int)arg2 recordMsgData:(id)arg3 type:(int)arg4;
- (void)downloadImageFinishedWithMessage:(id)arg1 type:(int)arg2 isSuccess:(BOOL)arg3;
- (void)startDownloadImageWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cdnDownloadMgrDidFailedDownloadWithCdnTask:(id)arg1;
- (void)cdnDownloadMgrDidFinishedDownloadWithCdnTask:(id)arg1;
- (void)downloadSightFileWithChatName:(id)arg1 mesLocalID:(unsigned int)arg2 recordMsgData:(id)arg3 isFavorite:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (id)cachedFileDataWithFilePath:(id)arg1;
- (BOOL)saveImageSizeForMessage:(id)arg1 size:(struct CGSize)arg2;
- (BOOL)isOriginalImageDownloading:(id)arg1;
- (void)downloadImageWithURLString:(id)arg1 thumbPath:(id)arg2 message:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)thumbImageWithReaderMessage:(id)arg1 thumbUrl:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)thumbImageWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cachedOriginImageWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cachedThumbImageWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)originalImageWithMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)originalImageWithMessage:(id)arg1;
- (void)originalImageWithPreviewMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeCachedImageWithFilePath:(id)arg1 isThumbnail:(BOOL)arg2;
- (id)cachedImageWithFilePath:(id)arg1 isThumbnail:(BOOL)arg2;
- (unsigned char)cacheOriginImageWithImageData:(id)arg1 FilePath:(id)arg2;
- (void)clearTextMessageCache;
- (void)clearReferCacheForMessage:(id)arg1;
- (void)clearReferStringForKey:(id)arg1;
- (void)setReferString:(id)arg1 forKey:(id)arg2;
- (void)setTranslationString:(id)arg1 forKey:(id)arg2;
- (id)cachedReferStringForKey:(id)arg1;
- (id)cachedTranslationStringForKey:(id)arg1;
- (void)setTextMessageString:(id)arg1 forKey:(id)arg2;
- (id)cachedTextMessageStringForKey:(id)arg1;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2 isRevoke:(BOOL)arg3;
- (void)onDelAllMsg:(id)arg1;
- (void)onSessionDeletedWithUserName:(id)arg1 atIndex:(long long)arg2;
- (void)clearAllCache;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

