//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, WXCMultiTalkGroup;

@protocol MMMultiTalkWindowDelegate <NSObject>
- (void)onMultiTalkWindowMicAudioOn:(BOOL)arg1;
- (void)onMultiTalkWindowRecoverVideoOn:(BOOL)arg1;
- (void)onMultiTalkWindowUpdateMessageWith:(WXCMultiTalkGroup *)arg1 duration:(unsigned int)arg2 messageId:(unsigned int)arg3;
- (void)onMultiTalkWindowAddMember:(NSArray *)arg1 withGroup:(WXCMultiTalkGroup *)arg2;
- (void)onMultiTalkWindowReceiveCancelCallWithGroup:(WXCMultiTalkGroup *)arg1;
- (void)onMultiTalkWindowHangup:(WXCMultiTalkGroup *)arg1;
@end

