//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMView.h"

@class MMPreviewTitleButton;

@interface MMNavigationBar : MMView
{
    MMPreviewTitleButton *leftView;
    MMPreviewTitleButton *rightView;
    CDUnknownBlockType _didLeftButtonClick;
    CDUnknownBlockType _didRightButtonClick;
}

@property(copy, nonatomic) CDUnknownBlockType didRightButtonClick; // @synthesize didRightButtonClick=_didRightButtonClick;
@property(copy, nonatomic) CDUnknownBlockType didLeftButtonClick; // @synthesize didLeftButtonClick=_didLeftButtonClick;
- (void).cxx_destruct;
- (void)clickNextBtn:(id)arg1;
- (void)clickBackBtn:(id)arg1;
- (void)setRightViewEnable:(BOOL)arg1;
- (void)setLeftViewEnable:(BOOL)arg1;
- (void)addRightView;
- (void)addLeftView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

