//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "NSTextFieldDelegate-Protocol.h"

@class MMPlaceholderTextField, NSImageView, NSString;

@interface MMPlaceholderContainerView : NSView <NSTextFieldDelegate>
{
    MMPlaceholderTextField *_placeholderTextField;
    NSImageView *_imageView;
    CDUnknownBlockType _didBecomeFirstResponderBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didBecomeFirstResponderBlock; // @synthesize didBecomeFirstResponderBlock=_didBecomeFirstResponderBlock;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) MMPlaceholderTextField *placeholderTextField; // @synthesize placeholderTextField=_placeholderTextField;
- (void).cxx_destruct;
- (struct CGRect)rectForPlaceholderString;
- (void)resignSearch;
- (void)startSearch;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

