//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMAttachmentReusableView.h"

@class MMAppReferCoverView, MMButton, MMCTTextView, MMReferCTTextView, NSImageView, NSView;
@protocol MMReferTextAttachmentViewDelegate;

@interface MMReferTextAttachmentView : MMAttachmentReusableView
{
    id <MMReferTextAttachmentViewDelegate> _referAttachDelegate;
    NSView *_bgView;
    MMAppReferCoverView *_coverView;
    MMReferCTTextView *_contentTextView;
    MMCTTextView *_senderTextView;
    NSImageView *_iconImageView;
    MMCTTextView *_summaryTextView;
    NSImageView *_moreHintView;
    NSImageView *_thumbImageView;
    NSImageView *_thumbIconImageView;
    MMButton *_clearButton;
}

@property(retain, nonatomic) MMButton *clearButton; // @synthesize clearButton=_clearButton;
@property(retain, nonatomic) NSImageView *thumbIconImageView; // @synthesize thumbIconImageView=_thumbIconImageView;
@property(retain, nonatomic) NSImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(retain, nonatomic) NSImageView *moreHintView; // @synthesize moreHintView=_moreHintView;
@property(retain, nonatomic) MMCTTextView *summaryTextView; // @synthesize summaryTextView=_summaryTextView;
@property(retain, nonatomic) NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) MMCTTextView *senderTextView; // @synthesize senderTextView=_senderTextView;
@property(retain, nonatomic) MMReferCTTextView *contentTextView; // @synthesize contentTextView=_contentTextView;
@property(retain, nonatomic) MMAppReferCoverView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) NSView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak id <MMReferTextAttachmentViewDelegate> referAttachDelegate; // @synthesize referAttachDelegate=_referAttachDelegate;
- (void).cxx_destruct;
- (BOOL)eventIsInsideReferArea:(id)arg1;
- (BOOL)eventIsInsideClearArea:(id)arg1;
- (void)layoutWithAttachmentObject:(id)arg1;
- (void)initView;
- (id)initWithIdentifier:(id)arg1;

@end

