//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMIgnoreEventView.h"

@class NSColor;

@interface MMRoundedRectangleView : MMIgnoreEventView
{
    double m_cornerRadius;
    NSColor *m_backGroundColor;
}

- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;
- (id)initWithCornerRadius:(double)arg1 backgroundColor:(id)arg2 frameRect:(struct CGRect)arg3;

@end

