//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPointerArray, NSRecursiveLock;

@interface MMRunLoopQueue : NSObject
{
    struct __CFRunLoop *_runLoop;
    struct __CFRunLoopSource *_runLoopSource;
    struct __CFRunLoopObserver *_runLoopObserver;
    NSPointerArray *_internalQueue;
    NSRecursiveLock *_internalQueueLock;
    BOOL _ensureExclusiveMembership;
    unsigned long long _batchSize;
    CDUnknownBlockType _queueConsumer;
}

@property(copy, nonatomic) CDUnknownBlockType queueConsumer; // @synthesize queueConsumer=_queueConsumer;
@property(nonatomic) BOOL ensureExclusiveMembership; // @synthesize ensureExclusiveMembership=_ensureExclusiveMembership;
@property(nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
- (void).cxx_destruct;
- (void)enqueue:(id)arg1;
- (void)processQueue;
- (void)dealloc;
- (id)initWithRunLoop:(struct __CFRunLoop *)arg1 runLoopMode:(struct __CFString *)arg2 retainObjects:(BOOL)arg3 handler:(CDUnknownBlockType)arg4;

@end

