//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class MMAvatarImageView, NSButton, NSImageView, NSTextField, WCContactData;

@interface MMSessionPickerChoosenRowView : NSTableRowView
{
    BOOL _disabled;
    WCContactData *_contact;
    MMAvatarImageView *_avatarView;
    NSTextField *_sessionNameField;
    NSButton *_removeButton;
    NSImageView *_openIMIcon;
    CDUnknownBlockType _didClickRemoveButtonBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didClickRemoveButtonBlock; // @synthesize didClickRemoveButtonBlock=_didClickRemoveButtonBlock;
@property(retain, nonatomic) NSImageView *openIMIcon; // @synthesize openIMIcon=_openIMIcon;
@property(retain, nonatomic) NSButton *removeButton; // @synthesize removeButton=_removeButton;
@property(retain, nonatomic) NSTextField *sessionNameField; // @synthesize sessionNameField=_sessionNameField;
@property(retain, nonatomic) MMAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) BOOL disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (void)setupWithContact:(id)arg1;
- (void)prepareForReuse;
- (void)_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

