//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class NSImageView, NSTextField;

@interface MMSessionCreateSessionButtonRowView : NSTableRowView
{
    NSImageView *_imageView;
    NSTextField *_titleField;
}

@property(retain, nonatomic) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

