//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WCTDatabase, WCTTable;

@interface MMSessionStorage : NSObject
{
    WCTDatabase *m_db;
    WCTTable *m_table;
    WCTTable *m_brandTable;
    NSString *m_nsDBFilePath;
}

+ (void)deleteSessionDB;
- (void).cxx_destruct;
- (void)deleteBrandSessionInfo:(id)arg1;
- (void)saveBrandSessionInfos:(id)arg1;
- (id)loadAllBrandSessionInfo;
- (void)deleteSessionInfo:(id)arg1;
- (void)saveSessionInfos:(id)arg1;
- (void)reportSessionIDKey:(unsigned long long)arg1;
- (id)loadAllSessionInfo;
- (void)close;
- (void)closeDBBeforeInit;
- (void)configDB;
- (void)dealloc;
- (id)init;

@end

