//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMThemeUtil : NSObject
{
}

+ (id)thinSystemFontSize:(double)arg1;
+ (id)mediumSystemFontSize:(double)arg1;
+ (id)systemFontSize:(double)arg1;
+ (id)imageWithName:(id)arg1 withSize:(struct CGSize)arg2 withColor:(id)arg3 flipped:(BOOL)arg4;
+ (id)imageWithName:(id)arg1 withSize:(struct CGSize)arg2 withColor:(id)arg3;
+ (id)imageWithName:(id)arg1 withSize:(struct CGSize)arg2;
+ (id)imageWithName:(id)arg1 withColor:(id)arg2;
+ (id)imageWithName:(id)arg1;
+ (BOOL)isDarkMode;

@end

