//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "CCNViewController-Protocol.h"

@class NSString, WAAppLoadingWindow;

@interface MMUIViewController : NSViewController <CCNViewController>
{
    BOOL m_bDisableAdjustInsetAndOffset;
    BOOL _m_bAnimated;
    BOOL _m_bAnimating;
    BOOL _m_bIsBeingPoped;
    BOOL _m_bInteractivePopEnabled;
    BOOL _isDuringInteractivePop;
    unsigned int _m_uiVcType;
    WAAppLoadingWindow *_loadingView;
}

@property(retain, nonatomic) WAAppLoadingWindow *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) unsigned int m_uiVcType; // @synthesize m_uiVcType=_m_uiVcType;
@property(nonatomic) BOOL isDuringInteractivePop; // @synthesize isDuringInteractivePop=_isDuringInteractivePop;
@property(nonatomic) BOOL m_bInteractivePopEnabled; // @synthesize m_bInteractivePopEnabled=_m_bInteractivePopEnabled;
@property(nonatomic) BOOL m_bIsBeingPoped; // @synthesize m_bIsBeingPoped=_m_bIsBeingPoped;
@property(nonatomic) BOOL m_bAnimating; // @synthesize m_bAnimating=_m_bAnimating;
@property(nonatomic) BOOL m_bAnimated; // @synthesize m_bAnimated=_m_bAnimated;
- (void).cxx_destruct;
- (void)stopLoading;
- (void)startLoadingWithText:(id)arg1;
- (void)startLoading;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

