//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MMNavigationController, MMTabbarController, MMTabbarItem, MMView;

@interface MMViewController : NSViewController
{
    MMTabbarItem *_tabbarItem;
    MMTabbarController *_tabbarController;
    MMViewController *_detailViewController;
    MMNavigationController *_navigationController;
}

@property(nonatomic) __weak MMNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;
- (void)popToThis:(id)arg1 beforePushViewController:(id)arg2 animated:(BOOL)arg3;
- (void)popToMeBeforePushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)popToRootBeforePushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)popViewController;
- (void)viewWillBePopedAnimated:(BOOL)arg1;
- (void)viewWillBePushedAnimated:(BOOL)arg1;
- (void)clearAllSubviews;
- (void)dealloc;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(retain, nonatomic) MMViewController *detailViewController;
@property(retain, nonatomic) MMTabbarItem *tabbarItem;

// Remaining properties
@property(retain) MMView *view; // @dynamic view;

@end

