//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface MMWebProgressBar : NSView
{
    BOOL _isProcessing;
    struct CGRect _oriFrame;
}

@property struct CGRect oriFrame; // @synthesize oriFrame=_oriFrame;
@property BOOL isProcessing; // @synthesize isProcessing=_isProcessing;
- (void)reset;
- (void)end;
- (void)progressing;
- (void)start;
- (id)initWithFrame:(struct CGRect)arg1;

@end

