//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

@interface MMWebViewPlugin_MenuWebSearch : MMWebViewPluginBase
{
    BOOL _menuNotificationRegistered;
    unsigned int _currentSelectionId;
    unsigned int _currentEvent;
}

@property(nonatomic) unsigned int currentEvent; // @synthesize currentEvent=_currentEvent;
@property(nonatomic) unsigned int currentSelectionId; // @synthesize currentSelectionId=_currentSelectionId;
@property(nonatomic) BOOL menuNotificationRegistered; // @synthesize menuNotificationRegistered=_menuNotificationRegistered;
- (void)tryAdjustSelectionWhenMenuShow:(id)arg1;
- (void)onMenuControllerDidShow:(id)arg1;
- (void)onMenuControllerDidHide:(id)arg1;
- (void)unregisterMenuNotifications;
- (void)registerMenuNotifications;
- (void)dealloc;

@end

