//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSColor, NSString;

@interface MMWebViewPresetUI : MMObject
{
    BOOL _navigationBarSperatorLineHidden;
    BOOL _hideCloseButton;
    BOOL _shouldShowDomain;
    unsigned long long _statusBarColor;
    NSColor *_navigationBarColor;
    NSColor *_navigationBarTitleColor;
    NSColor *_navigationLeftItemFontColor;
    NSColor *_navigationRightItemColor;
    NSString *_navigationLeftIconName;
    NSString *_navigationBarTitle;
    unsigned long long _webScrollStyle;
    NSColor *_backcontainerColor;
    unsigned long long _backcontainerEffect;
    NSColor *_addressLabelColor;
    NSColor *_backgroundColor;
}

@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) BOOL shouldShowDomain; // @synthesize shouldShowDomain=_shouldShowDomain;
@property(retain, nonatomic) NSColor *addressLabelColor; // @synthesize addressLabelColor=_addressLabelColor;
@property(nonatomic) unsigned long long backcontainerEffect; // @synthesize backcontainerEffect=_backcontainerEffect;
@property(retain, nonatomic) NSColor *backcontainerColor; // @synthesize backcontainerColor=_backcontainerColor;
@property(nonatomic) unsigned long long webScrollStyle; // @synthesize webScrollStyle=_webScrollStyle;
@property(copy, nonatomic) NSString *navigationBarTitle; // @synthesize navigationBarTitle=_navigationBarTitle;
@property(retain, nonatomic) NSString *navigationLeftIconName; // @synthesize navigationLeftIconName=_navigationLeftIconName;
@property(retain, nonatomic) NSColor *navigationRightItemColor; // @synthesize navigationRightItemColor=_navigationRightItemColor;
@property(retain, nonatomic) NSColor *navigationLeftItemFontColor; // @synthesize navigationLeftItemFontColor=_navigationLeftItemFontColor;
@property(nonatomic) BOOL hideCloseButton; // @synthesize hideCloseButton=_hideCloseButton;
@property(nonatomic) BOOL navigationBarSperatorLineHidden; // @synthesize navigationBarSperatorLineHidden=_navigationBarSperatorLineHidden;
@property(retain, nonatomic) NSColor *navigationBarTitleColor; // @synthesize navigationBarTitleColor=_navigationBarTitleColor;
@property(retain, nonatomic) NSColor *navigationBarColor; // @synthesize navigationBarColor=_navigationBarColor;
@property(nonatomic) unsigned long long statusBarColor; // @synthesize statusBarColor=_statusBarColor;
- (void).cxx_destruct;
- (id)init;

@end

