//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

@class NSString;

@interface MMWebViewPlugin_ReadMode : MMWebViewPluginBase
{
    unsigned int uiCurrentEventID;
    NSString *nsUrlOfReadingMode;
    NSString *nsUrlOfReadModeOriginal;
}

@property(retain, nonatomic) NSString *nsUrlOfReadModeOriginal; // @synthesize nsUrlOfReadModeOriginal;
@property(retain, nonatomic) NSString *nsUrlOfReadingMode; // @synthesize nsUrlOfReadingMode;
@property(nonatomic) unsigned int uiCurrentEventID; // @synthesize uiCurrentEventID;
- (void).cxx_destruct;
- (BOOL)canShowReadingMode;
- (void)GetReadingModeUrlFromServer:(id)arg1 andUserAgent:(id)arg2;
- (void)StopReadingMode;
- (BOOL)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)dealloc;
- (id)init;

@end

