//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMWebViewHelper : NSObject
{
}

+ (id)getUrlWithoutFontSize:(id)arg1;
+ (id)getFontSizeUrl:(id)arg1 fontSize:(int)arg2;
+ (int)getFontSizeFromUrl:(id)arg1;
+ (int)getFontSizeFromRealFontSize:(double)arg1;
+ (double)getRealFontSizeFromFontSize:(int)arg1;
+ (int)checkFontSize:(int)arg1;
+ (id)defaultBroswer;
+ (BOOL)hasWxWorkScheme:(id)arg1;
+ (BOOL)hasWeChatScheme:(id)arg1;
+ (BOOL)isAppScheme:(id)arg1;
+ (BOOL)isDownloadMIMEType:(id)arg1;
+ (id)getHostTextWithUrl:(id)arg1;
+ (void)handleWebViewDataItem:(id)arg1 windowId:(id)arg2;

@end

