//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "AccountServiceExt-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSButton, NSColor, NSString, NSTextField, NSTitlebarAccessoryViewController;

@interface MMWindowController : NSWindowController <NSWindowDelegate, AccountServiceExt>
{
    NSTitlebarAccessoryViewController *_titlebarController;
    NSButton *_closeButton;
    NSButton *_minButton;
    NSButton *_zoomButton;
    NSString *_windowTitle;
    NSTextField *_titleField;
    NSColor *_layerBackgroundColor;
    double _titleBarAccessoryViewHeight;
    double _buttonMarginBottom;
}

@property(nonatomic) double buttonMarginBottom; // @synthesize buttonMarginBottom=_buttonMarginBottom;
@property(nonatomic) double titleBarAccessoryViewHeight; // @synthesize titleBarAccessoryViewHeight=_titleBarAccessoryViewHeight;
@property(retain, nonatomic) NSColor *layerBackgroundColor; // @synthesize layerBackgroundColor=_layerBackgroundColor;
@property(retain, nonatomic) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(copy, nonatomic) NSString *windowTitle; // @synthesize windowTitle=_windowTitle;
@property(retain, nonatomic) NSButton *zoomButton; // @synthesize zoomButton=_zoomButton;
@property(retain, nonatomic) NSButton *minButton; // @synthesize minButton=_minButton;
@property(retain, nonatomic) NSButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) NSTitlebarAccessoryViewController *titlebarController; // @synthesize titlebarController=_titlebarController;
- (void).cxx_destruct;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)onUserLogout;
- (void)doSomethingWhenLocked;
- (void)doSomethingWhenUnLocked;
- (void)doSomethingWhenUserLogout;
- (void)windowWillEnterFullScreenAction:(id)arg1;
- (void)windowWillExitFullScreenAction:(id)arg1;
- (void)layoutTrafficLightButton;
- (void)adjustTitleBarSubViews;
- (void)addNotifications;
- (id)addEffectWithView:(id)arg1 aEffectMaterial:(long long)arg2 fillColor:(id)arg3 alpha:(double)arg4 blendingMode:(long long)arg5;
- (id)addEffectWithView:(id)arg1 fillColor:(id)arg2 alpha:(double)arg3;
- (id)addEffectWithView:(id)arg1;
- (void)initTitleTextField;
- (void)initTitleBar;
- (void)initWindow;
- (void)dealloc;
- (void)windowDidLoad;
- (id)initWithWindowNibName:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

