//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, NSString, WKWebView;
@protocol YYWebViewDelegate, YYWebViewInterface><MMWKWebViewInterface;

@protocol MMWKWebViewInterface <NSObject>
+ (WKWebView<YYWebViewInterface><MMWKWebViewInterface> *)webViewWithType:(long long)arg1 frame:(struct CGRect)arg2 recordInitUrl:(NSString *)arg3 delegate:(id <YYWebViewDelegate>)arg4;
@property(retain, nonatomic) NSSet *noNeedCheckOfflineUrlSet;
@property(nonatomic) BOOL isOfflinePage;
@property(retain, nonatomic) NSString *recordInitUrl;
@property(nonatomic) BOOL bWkProxyEnabled;
- (void)tryDestroyWebView;
- (void)tryUpdateWePkgByLoadingUrl:(NSString *)arg1 isMainFrame:(BOOL)arg2;
@end

