//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAlert.h>

@interface NSAlert (Ext)
+ (void)showAlertWindowWithTitle:(id)arg1 message:(id)arg2 confirmButton:(id)arg3 cancelButton:(id)arg4;
+ (void)showAlertWindowWithTitle:(id)arg1 message:(id)arg2 target:(id)arg3 confirmButton:(id)arg4 confirmAction:(SEL)arg5 cancelButton:(id)arg6 cancelAction:(SEL)arg7;
+ (void)showAlertSheetWithTitle:(id)arg1 message:(id)arg2 confirmButton:(id)arg3 cancelButton:(id)arg4 accessoryView:(id)arg5 onWindow:(id)arg6 completion:(CDUnknownBlockType)arg7;
+ (void)showAlertSheetWithTitle:(id)arg1 message:(id)arg2 confirmButton:(id)arg3 cancelButton:(id)arg4 onWindow:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (void)showAlertSheetWithTitle:(id)arg1 message:(id)arg2 confirmButton:(id)arg3 cancelButton:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)showAlertSheetWithTitle:(id)arg1 message:(id)arg2 onWindow:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)showConfirmSheetWithTitle:(id)arg1 message:(id)arg2 onWindow:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)showConfirmSheetWithTitle:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)showAlertSheetWithTitle:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;
@end

