//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (Stretchable)
- (id)stretchableImageWithTopCapHeight:(float)arg1 middleHeight:(float)arg2 bottomCapHeight:(float)arg3;
- (id)stretchableImageWithLeftCapWidth:(float)arg1 middleWidth:(float)arg2 rightCapWidth:(float)arg3;
- (id)stretchableImageWithSize:(struct CGSize)arg1 edgeInsets:(struct NSEdgeInsets)arg2;
- (id)genPNGRepresentationOfImage:(id)arg1;
@end

