//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (Jietu)
- (id)getTailorImageWithRect:(struct CGRect)arg1;
- (id)generateImageWithSize:(struct CGSize)arg1 cornerRadius:(double)arg2;
- (id)convert2Xto1XImage;
- (BOOL)saveToFile:(id)arg1 fileType:(unsigned long long)arg2;
- (BOOL)writePNGDataToPasteboard;
- (BOOL)isHighReolution;
- (struct CGSize)pixelSize;
@end

