//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (UserName)
+ (id)subscriptionHolderUserName;
- (BOOL)isWeAppSessionHolderUserName;
- (BOOL)isNotificationMessageUserName;
- (BOOL)isSearchableUserName;
- (BOOL)isHiddenRawUserName;
- (BOOL)isLocalHardCodeUsrName;
- (BOOL)isOfficialPluginUsrName;
- (BOOL)isLocalizedPluginUsrName;
- (BOOL)isPluginUsrName;
- (BOOL)isFileHelperUserName;
- (BOOL)isQQMailUserName;
- (BOOL)isTencentNewsUserName;
- (BOOL)isSubscriptionsHolderUserName;
- (BOOL)isMassSendContactUserName;
- (BOOL)isNewFriendUserName;
- (BOOL)isFBFriendUserName;
- (BOOL)isBottleContactUserName;
- (BOOL)isSXContactUserName;
- (BOOL)isGroupCardUserName;
- (BOOL)isCustomerUserName;
- (BOOL)isWxWorkChatRoom;
- (BOOL)isWxWorkUserName;
- (BOOL)isEncodeUserName;
- (unsigned int)GetChatNameType;
- (BOOL)isQQContactUserName;
- (BOOL)isLBSRoomUserName;
- (BOOL)isGroupChatUserName;
@end

