//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSView (Ext)
+ (id)rootDesc;
+ (id)recursiveDescriptionOfView:(id)arg1 level:(long long)arg2;
- (BOOL)isMouseReallyInside;
- (id)firstSubviewOfClass:(id)arg1;
- (id)rootDescWithLevel6;
- (id)rootDescWithLevel5;
- (id)rootDescWithLevel4;
- (id)rootDescWithLevel3;
- (id)rootDescWithLevel2;
- (id)rootDescWithLevel1;
- (id)rootDescWithLevel:(long long)arg1;
- (id)debugDescription;
- (id)rootDescWithLevel;
- (id)selfDesc;
- (id)screenCacheImageForViewWithRect:(struct CGRect)arg1;
- (id)screenCacheImageForView;
- (id)imageWithSubviews;
@property double cornerRadius;
@property double centerY;
@property double centerX;
@property double bottom;
@property double top;
@property double right;
@property double left;
@property double height;
@property double width;
@property double y;
@property double x;
@end

