//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "GetPhoneNumberLogicChoosePhoneSheetDelegate-Protocol.h"
#import "MMCGIDelegate-Protocol.h"
#import "WAPageSheetDelegate-Protocol.h"
#import "WAPhoneVerifyViewControllerDelegate-Protocol.h"

@class MMUIViewController, NSData, NSString, PhoneAuthGetPhoneNumberLogicAuthInfo, PhoneAuthGetPhoneNumberLogicChoosePhoneSheet, PhoneAuthGetPhoneNumberLogicPhoneInfo, WAPhoneVerifyViewController, WAReportPhoneAuthActionItem;

@interface PhoneAuthGetPhoneNumberLogic : MMObject <MMCGIDelegate, GetPhoneNumberLogicChoosePhoneSheetDelegate, WAPageSheetDelegate, WAPhoneVerifyViewControllerDelegate>
{
    BOOL _bindPhoneReturn;
    unsigned int _versionType;
    NSData *_requestData;
    NSString *_fromUrlString;
    NSString *_appid;
    MMUIViewController *_vc;
    CDUnknownBlockType _completion;
    PhoneAuthGetPhoneNumberLogicAuthInfo *_authInfo;
    WAReportPhoneAuthActionItem *_reportAction;
    PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *_choosePhoneSheet;
    WAPhoneVerifyViewController *_verifyWindow;
    PhoneAuthGetPhoneNumberLogicPhoneInfo *_chosenPhoneInfo;
    NSString *_recordPhone;
    unsigned long long _originInterativePopFlag;
}

@property(nonatomic) unsigned long long originInterativePopFlag; // @synthesize originInterativePopFlag=_originInterativePopFlag;
@property(copy, nonatomic) NSString *recordPhone; // @synthesize recordPhone=_recordPhone;
@property(retain, nonatomic) PhoneAuthGetPhoneNumberLogicPhoneInfo *chosenPhoneInfo; // @synthesize chosenPhoneInfo=_chosenPhoneInfo;
@property(retain, nonatomic) WAPhoneVerifyViewController *verifyWindow; // @synthesize verifyWindow=_verifyWindow;
@property(retain, nonatomic) PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *choosePhoneSheet; // @synthesize choosePhoneSheet=_choosePhoneSheet;
@property(retain, nonatomic) WAReportPhoneAuthActionItem *reportAction; // @synthesize reportAction=_reportAction;
@property(retain, nonatomic) PhoneAuthGetPhoneNumberLogicAuthInfo *authInfo; // @synthesize authInfo=_authInfo;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) __weak MMUIViewController *vc; // @synthesize vc=_vc;
@property(copy, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(nonatomic) BOOL bindPhoneReturn; // @synthesize bindPhoneReturn=_bindPhoneReturn;
@property(copy, nonatomic) NSString *fromUrlString; // @synthesize fromUrlString=_fromUrlString;
@property(retain, nonatomic) NSData *requestData; // @synthesize requestData=_requestData;
@property(nonatomic) unsigned int versionType; // @synthesize versionType=_versionType;
- (void).cxx_destruct;
- (id)getLastAuthPhone;
- (id)getRecordInfoFromLocal;
- (void)saveRecordPhoneToLocal:(id)arg1;
- (void)saveLastAuthPhone:(id)arg1;
- (void)onModalResponse:(long long)arg1 tipTag:(long long)arg2;
- (void)showAlertWithTitle:(id)arg1 message:(id)arg2 confirmButton:(id)arg3 cancelButton:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)beginBindPhone;
- (void)regenerateDisplayPhoneInfos;
- (id)getDisplayPhoneInfoArray;
- (id)getChoosePhoneSheetInfo;
- (void)showConfirmWindowOnContainer;
- (id)getPhoneInfoFromDic:(id)arg1;
- (void)onPhoneStatusResponse:(id)arg1;
- (void)onSuccessWithResultDic:(id)arg1;
- (void)onErrorWithErrCode:(int)arg1 msg:(id)arg2;
- (void)onClose;
- (void)onRetry;
- (void)onComplete:(id)arg1;
- (void)choosePhoneSheetDidTapOnAddNewPhoneButton:(id)arg1;
- (void)choosePhoneSheetDidTapOnManagePhoneButton:(id)arg1;
- (void)choosePhoneSheet:(id)arg1 didAllowOnPhoneInfo:(id)arg2;
- (void)choosePhoneSheetDidReject:(id)arg1;
- (void)pageSheetDidCancelByTapAside:(id)arg1;
- (void)closeVerifyWindow;
- (void)showPhoneVerifyWindow;
- (void)handleCheckVerifyCodeResponse:(id)arg1;
- (void)handleSendVerifyCodeResponse:(id)arg1;
- (void)handleGetAllUserPhone:(id)arg1;
- (void)OnResponseCGIFailedWithSessionId:(unsigned int)arg1 cgiWrap:(id)arg2 errType:(unsigned int)arg3 errCode:(unsigned int)arg4;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)startCheckPhoneVerifySmsRequest:(id)arg1;
- (void)startSendPhoneVerifySmsRequest;
- (void)startGetPhoneRequest;
- (void)getPhoneNumberWithCompletion:(CDUnknownBlockType)arg1;
- (void)onWeAppEnterForeground:(id)arg1;
- (void)dealloc;
- (id)initWithAppId:(id)arg1 vc:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

