//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface PhoneAuthGetPhoneNumberLogicPhoneInfo : MMObject
{
    BOOL _isBindWechat;
    BOOL _needAuth;
    BOOL _allowSendSms;
    NSString *_mobile;
    NSString *_showMobile;
    NSString *_encryptData;
    NSString *_iv;
}

@property(copy, nonatomic) NSString *iv; // @synthesize iv=_iv;
@property(copy, nonatomic) NSString *encryptData; // @synthesize encryptData=_encryptData;
@property(nonatomic) BOOL allowSendSms; // @synthesize allowSendSms=_allowSendSms;
@property(nonatomic) BOOL needAuth; // @synthesize needAuth=_needAuth;
@property(nonatomic) BOOL isBindWechat; // @synthesize isBindWechat=_isBindWechat;
@property(copy, nonatomic) NSString *showMobile; // @synthesize showMobile=_showMobile;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
- (void).cxx_destruct;
- (id)getResultDic;

@end

