//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class MMUILabel, NSImageView, NSView, PhoneAuthGetPhoneNumberLogicDisplayPhoneInfo;

@interface PhoneAuthGetPhoneNumberLogicDisplayPhoneTableViewCell : NSTableRowView
{
    MMUILabel *_phoneNumberLabel;
    MMUILabel *_describeLabel;
    NSImageView *_toggleImageView;
    NSView *_topLineView;
    NSView *_bottomLineView;
    PhoneAuthGetPhoneNumberLogicDisplayPhoneInfo *_info;
}

@property(retain, nonatomic) PhoneAuthGetPhoneNumberLogicDisplayPhoneInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) NSView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) NSView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) NSImageView *toggleImageView; // @synthesize toggleImageView=_toggleImageView;
@property(retain, nonatomic) MMUILabel *describeLabel; // @synthesize describeLabel=_describeLabel;
@property(retain, nonatomic) MMUILabel *phoneNumberLabel; // @synthesize phoneNumberLabel=_phoneNumberLabel;
- (void).cxx_destruct;
- (void)fillPhoneInfo:(id)arg1;
- (void)unToggle;
- (void)toggle;
- (void)markUnBottom;
- (void)markBottom;
- (void)setupConstraints;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

