//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_io, OS_dispatch_queue;

@interface PTUSBChannel : NSObject
{
    NSObject<OS_dispatch_io> *channel_;
    NSObject<OS_dispatch_queue> *queue_;
    unsigned int nextPacketTag_;
    NSMutableDictionary *responseQueue_;
    BOOL autoReadPackets_;
    BOOL isReadingPackets_;
}

+ (id)packetDictionaryWithPacketType:(id)arg1 payload:(id)arg2;
- (void).cxx_destruct;
- (void)stop;
- (void)cancel;
- (void)readFromOffset:(long long)arg1 length:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;
- (void)sendData:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)sendDispatchData:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)sendPacket:(id)arg1 tag:(unsigned int)arg2 callback:(CDUnknownBlockType)arg3;
- (void)sendPacketOfType:(unsigned int)arg1 overProtocol:(unsigned int)arg2 tag:(unsigned int)arg3 payload:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (void)scheduleReadPacketWithCallback:(CDUnknownBlockType)arg1;
- (void)scheduleReadPacketWithBroadcastHandler:(CDUnknownBlockType)arg1;
- (void)setNeedsReadingPacket;
- (void)sendRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (unsigned int)nextPacketTag;
- (BOOL)errorFromPlistResponse:(id)arg1 error:(id *)arg2;
- (void)listenWithBroadcastHandler:(CDUnknownBlockType)arg1 callback:(CDUnknownBlockType)arg2;
- (BOOL)openOnQueue:(id)arg1 error:(id *)arg2 onEnd:(CDUnknownBlockType)arg3;
@property(readonly) int fileDescriptor;
@property(readonly) NSObject<OS_dispatch_io> *dispatchChannel;
- (BOOL)valid;
- (void)dealloc;
- (id)init;

@end

