//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class DBEncryptInfo, NSMutableArray, NSMutableDictionary, NSString, TaskSetting;

@interface RemoteTaskCenter : MMService <MMService>
{
    struct __CFMessagePort *remotePortListenner;
    BOOL _hasOpenApp;
    BOOL _isForwarding;
    int _parentPid;
    DBEncryptInfo *_m_dbEncryptInfo;
    NSMutableArray *_waitForwardArr;
    NSString *_publicKey;
    NSString *_privateKey;
    TaskSetting *_myConfig;
    long long _lastTaskTime;
    NSString *_identifier;
    NSString *_displayName;
    NSString *_coverUrl;
    NSMutableDictionary *_seqNOOfTnstance;
    NSString *_portName;
}

@property(retain, nonatomic) NSString *portName; // @synthesize portName=_portName;
@property(retain, nonatomic) NSMutableDictionary *seqNOOfTnstance; // @synthesize seqNOOfTnstance=_seqNOOfTnstance;
@property(retain, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) long long lastTaskTime; // @synthesize lastTaskTime=_lastTaskTime;
@property(nonatomic) int parentPid; // @synthesize parentPid=_parentPid;
@property(retain, nonatomic) TaskSetting *myConfig; // @synthesize myConfig=_myConfig;
@property(retain, nonatomic) NSString *privateKey; // @synthesize privateKey=_privateKey;
@property(retain, nonatomic) NSString *publicKey; // @synthesize publicKey=_publicKey;
@property(retain, nonatomic) NSMutableArray *waitForwardArr; // @synthesize waitForwardArr=_waitForwardArr;
@property(nonatomic) BOOL isForwarding; // @synthesize isForwarding=_isForwarding;
@property(retain, nonatomic) DBEncryptInfo *m_dbEncryptInfo; // @synthesize m_dbEncryptInfo=_m_dbEncryptInfo;
@property(nonatomic) BOOL hasOpenApp; // @synthesize hasOpenApp=_hasOpenApp;
- (void).cxx_destruct;
- (void)startLocalListener;
- (void)sendMessageToServer:(id)arg1;
- (void)checkConnectionStatus;
- (void)startConnectionWatchDog;
- (void)doShowGlobalAlert:(id)arg1 message:(id)arg2 terminateAppTask:(BOOL)arg3;
- (void)reportCostTime:(long long)arg1;
- (void)doIDKeyReport:(int)arg1 key:(int)arg2;
- (void)doKVStatReport:(int)arg1 context:(id)arg2;
- (void)onFinishForward:(id)arg1;
- (void)doForwardMsgData:(id)arg1;
- (void)doCloseTask;
- (void)doCheckHeartBeat;
- (void)doTerminate;
- (void)receiveTaskDataEvent:(struct __CFData *)arg1;
- (void)doSendEventToServer:(int)arg1 withDict:(id)arg2;
- (int)getCurSeqNO:(id)arg1;
- (int)getNextSeqNO:(id)arg1;
- (void)setCurSeqNO:(int)arg1 withKey:(id)arg2;
- (BOOL)isExistParentProcess;
- (void)doEstablished:(id)arg1;
- (void)doConnect:(id)arg1;
- (void)doStart;
- (void)saveMarsCDNConfigure;
- (void)saveCGIServiceInfo;
- (void)saveSessionInfo:(id)arg1;
- (void)saveEncryptInfo:(id)arg1;
- (id)getDBEncryptInfo;
- (int)getParentPid;
- (id)getAppCoverUrl;
- (id)getAppDisplayName;
- (id)getAppId;
- (id)createBaseTaskInfo;
- (void)loadProcessInfo:(id)arg1;
- (void)loadTaskInfo;
- (void)onServiceTerminate;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

