//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSData;

@interface ReportClientCheckRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasClientCheckData:1;
    unsigned int hasContext:1;
    unsigned int context;
    BaseRequest *baseRequest;
    NSData *clientCheckData;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetContext:) unsigned int context; // @synthesize context;
@property(readonly, nonatomic) BOOL hasContext; // @synthesize hasContext;
@property(retain, nonatomic, setter=SetClientCheckData:) NSData *clientCheckData; // @synthesize clientCheckData;
@property(readonly, nonatomic) BOOL hasClientCheckData; // @synthesize hasClientCheckData;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

