//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSScroller.h>

@interface RFOverlayScroller : NSScroller
{
    BOOL _isOptiDisplay;
    double _preFloatValue;
}

+ (double)zeroWidth;
+ (BOOL)isCompatibleWithOverlayScrollers;
@property(nonatomic) double preFloatValue; // @synthesize preFloatValue=_preFloatValue;
@property(nonatomic) BOOL isOptiDisplay; // @synthesize isOptiDisplay=_isOptiDisplay;
- (void)fadeOut;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)setFloatValue:(float)arg1;
- (void)drawKnobSlotInRect:(struct CGRect)arg1 highlight:(BOOL)arg2;
- (void)commonInitializer;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

