//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IExptServiceExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSString;

@interface TaskSafeCenter : MMService <IExptServiceExt, MMService>
{
    BOOL _isElanyangTask;
    BOOL _forceUseSingleProcess;
}

@property(nonatomic) BOOL forceUseSingleProcess; // @synthesize forceUseSingleProcess=_forceUseSingleProcess;
@property(nonatomic) BOOL isElanyangTask; // @synthesize isElanyangTask=_isElanyangTask;
- (void)onExptItemListChange;
- (void)updateWeAppLocalConfig;
- (BOOL)canUseMultiProcess;
- (void)doForceUseSingleProcess:(BOOL)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

