//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSData, NSMutableDictionary, NSString;

@interface TopInfo : NSObject <PBCoding>
{
    unsigned int lastLoginType;
    NSString *curUserName;
    NSString *lastLoginUserName;
    NSMutableDictionary *m_hostMapList;
    NSString *lastLoginNickName;
    NSString *lastLoginAvatarUrl;
    NSData *lastLoginAutoAuthKey;
    NSString *showMsgAfterRelaunching;
}

+ (void)initialize;
+ (void)_initPBTableOfTopInfo;
@property(retain, nonatomic) NSString *showMsgAfterRelaunching; // @synthesize showMsgAfterRelaunching;
@property(retain, nonatomic) NSData *lastLoginAutoAuthKey; // @synthesize lastLoginAutoAuthKey;
@property(retain, nonatomic) NSString *lastLoginAvatarUrl; // @synthesize lastLoginAvatarUrl;
@property(retain, nonatomic) NSString *lastLoginNickName; // @synthesize lastLoginNickName;
@property(retain, nonatomic) NSMutableDictionary *m_hostMapList; // @synthesize m_hostMapList;
@property(nonatomic) unsigned int lastLoginType; // @synthesize lastLoginType;
@property(retain, nonatomic) NSString *lastLoginUserName; // @synthesize lastLoginUserName;
@property(retain, nonatomic) NSString *curUserName; // @synthesize curUserName;
- (void).cxx_destruct;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

