//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSString;

@interface TRTCDashBoardLayoutView : NSView
{
    NSString *_status;
    NSString *_log;
    struct TXTextScrollView *_statusView;
    struct TXTextScrollView *_logView;
    BOOL _logEnabled;
    struct NSEdgeInsets _margin;
}

@property(nonatomic) struct NSEdgeInsets margin; // @synthesize margin=_margin;
@property(nonatomic) BOOL logEnabled; // @synthesize logEnabled=_logEnabled;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *status;
@property(copy, nonatomic) NSString *log;
- (void)_layout;
- (struct TXTextScrollView *)createTextView;
- (void)layout;
- (id)initWithFrame:(struct CGRect)arg1 logEnabled:(BOOL)arg2;

@end

