//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TXIAudioPlayDataDelegate-Protocol.h"

@class NSString, NSView, TXCRenderAndDec;
@protocol TRTCAudioFrameDelegate;

@interface TRTCUserInfo : NSObject <TXIAudioPlayDataDelegate>
{
    BOOL _mainVideoMuted;
    BOOL _smallVideoMuted;
    BOOL _subVideoMuted;
    BOOL _audioMuted;
    int _videoState;
    unsigned int _exitReason;
    int _streamType;
    unsigned long long _tinyId;
    NSString *_strTinyId;
    NSString *_userId;
    NSView *_mainView;
    NSView *_subStreamView;
    TXCRenderAndDec *_render;
    TXCRenderAndDec *_subRender;
    id <TRTCAudioFrameDelegate> _delegate;
}

@property(nonatomic) BOOL audioMuted; // @synthesize audioMuted=_audioMuted;
@property(nonatomic) BOOL subVideoMuted; // @synthesize subVideoMuted=_subVideoMuted;
@property(nonatomic) BOOL smallVideoMuted; // @synthesize smallVideoMuted=_smallVideoMuted;
@property(nonatomic) BOOL mainVideoMuted; // @synthesize mainVideoMuted=_mainVideoMuted;
@property(nonatomic) int streamType; // @synthesize streamType=_streamType;
@property(nonatomic) __weak id <TRTCAudioFrameDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TXCRenderAndDec *subRender; // @synthesize subRender=_subRender;
@property(retain, nonatomic) TXCRenderAndDec *render; // @synthesize render=_render;
@property(nonatomic) unsigned int exitReason; // @synthesize exitReason=_exitReason;
@property(nonatomic) int videoState; // @synthesize videoState=_videoState;
@property(nonatomic) __weak NSView *subStreamView; // @synthesize subStreamView=_subStreamView;
@property(nonatomic) __weak NSView *mainView; // @synthesize mainView=_mainView;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *strTinyId; // @synthesize strTinyId=_strTinyId;
@property(nonatomic) unsigned long long tinyId; // @synthesize tinyId=_tinyId;
- (void).cxx_destruct;
- (void)onAudioPlayData:(id)arg1 timeStamp:(unsigned long long)arg2 sampleRate:(int)arg3 channels:(int)arg4;
- (BOOL)muteSubVideo;
- (BOOL)hasSubVideoStream;
- (BOOL)muteMainVideo;
- (BOOL)hasSmallVideoStream;
- (BOOL)hasBigVideoStream;
- (BOOL)muteAudio;
- (BOOL)hasAudioStream;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

