//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TXCAudioDeviceInfo : NSObject
{
    BOOL _isInput;
    unsigned int _connId;
    unsigned int _dataSource;
    unsigned int _portType;
    NSString *_name;
}

@property(nonatomic) unsigned int portType; // @synthesize portType=_portType;
@property(nonatomic) unsigned int dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) BOOL isInput; // @synthesize isInput=_isInput;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned int connId; // @synthesize connId=_connId;
- (void).cxx_destruct;
- (id)toString;
- (id)uint32ToString:(unsigned int)arg1;
- (void)copy:(id)arg1;
- (id)init;

@end

