//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TXCModule.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"
#import "TXCCapturer-Protocol.h"

@class AVCaptureConnection, AVCaptureScreenInput, AVCaptureSession, AVCaptureVideoDataOutput, NSObject, NSString;
@protocol OS_dispatch_queue, TXIMediaCapturerDelegate, TXINotifyDelegate;

@interface TXCScreenCapturer : TXCModule <AVCaptureVideoDataOutputSampleBufferDelegate, TXCCapturer>
{
    NSObject<OS_dispatch_queue> *_processQueue;
    NSObject<OS_dispatch_queue> *_captureSessionQueue;
    unsigned long long _captureFrameCount;
    unsigned long long _lastCalculateTS;
    unsigned long long _lastCaptureFrameCount;
    struct CGSize _imageSize;
    int _presetWidth;
    int _presetHeight;
    BOOL _capturesCursor;
    BOOL _capturesMouseClicks;
    BOOL _mirror;
    unsigned int _displayID;
    unsigned int _maxFPS;
    id <TXIMediaCapturerDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
    double _zoomScale;
    long long _rotation;
    AVCaptureSession *_captureSession;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureScreenInput *_videoInput;
    AVCaptureConnection *_videoConnection;
    struct CGSize _videoSize;
    struct CGRect _cropRect;
}

@property(retain) AVCaptureConnection *videoConnection; // @synthesize videoConnection=_videoConnection;
@property(retain) AVCaptureScreenInput *videoInput; // @synthesize videoInput=_videoInput;
@property(retain) AVCaptureVideoDataOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(nonatomic) BOOL mirror; // @synthesize mirror=_mirror;
@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(nonatomic) double zoomScale; // @synthesize zoomScale=_zoomScale;
@property(nonatomic) unsigned int maxFPS; // @synthesize maxFPS=_maxFPS;
@property(nonatomic) BOOL capturesMouseClicks; // @synthesize capturesMouseClicks=_capturesMouseClicks;
@property(nonatomic) BOOL capturesCursor; // @synthesize capturesCursor=_capturesCursor;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
@property(nonatomic) unsigned int displayID; // @synthesize displayID=_displayID;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
@property(nonatomic) __weak id <TXIMediaCapturerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)runTXCAsynchronouslyOnCameraProcessingQueue:(CDUnknownBlockType)arg1;
- (void)runTXCSynchronouslyOnCameraProcessingQueue:(CDUnknownBlockType)arg1;
- (id)genVFrame:(struct opaqueCMSampleBuffer *)arg1 gravityAngel:(long long)arg2;
- (void)sendNotifyEvent:(long long)arg1;
- (void)_processCapturedFrame:(struct opaqueCMSampleBuffer *)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property(readonly, nonatomic, getter=isRunning) BOOL running;
- (void)stop;
- (void)start;
- (void)_setupInput:(id)arg1;
- (void)_setScale:(id)arg1;
- (void)setupCaptureSession;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

