//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TXCCapturer-Protocol.h"

@class NSString, TXCModule;
@protocol OS_dispatch_queue, OS_dispatch_source, TXIMediaCapturerDelegate, TXINotifyDelegate;

@interface TXCWindowCapturer : NSObject <TXCCapturer>
{
    TXCModule *_module;
    unsigned int _windowID;
    BOOL _captureShadow;
    unsigned long long _startTime;
    NSObject<OS_dispatch_source> *_timer;
    NSObject<OS_dispatch_queue> *_workQueue;
    unsigned long long _frameIndex;
    struct CGSize _videoSize;
    BOOL _running;
    unsigned int _maxFPS;
    id <TXIMediaCapturerDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
    NSObject<OS_dispatch_queue> *_delegateQueue;
}

+ (struct CGImage *)newImageFromWindow:(unsigned int)arg1 withShadow:(BOOL)arg2;
+ (id)windowList;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(nonatomic, getter=isRunning) BOOL running; // @synthesize running=_running;
@property(nonatomic) unsigned int maxFPS; // @synthesize maxFPS=_maxFPS;
@property(nonatomic) unsigned int windowID; // @synthesize windowID=_windowID;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
@property(nonatomic) __weak id <TXIMediaCapturerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)genVFrame:(struct opaqueCMSampleBuffer *)arg1 gravityAngel:(long long)arg2;
- (void)onCaptureTimer;
- (struct opaqueCMSampleBuffer *)sampleBufferFromCGImage:(struct CGImage *)arg1;
- (struct __CVBuffer *)newPixelBufferFromCGImage1:(struct CGImage *)arg1;
- (struct __CVBuffer *)newPixelBufferFromCGImage:(struct CGImage *)arg1;
- (void)stop;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

