//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImageView;

@interface TXLiveContainerView : NSView
{
    NSView *_liveView;
    NSImageView *_snapshotImageView;
}

@property(retain, nonatomic) NSImageView *snapshotImageView; // @synthesize snapshotImageView=_snapshotImageView;
@property(retain, nonatomic) NSView *liveView; // @synthesize liveView=_liveView;
- (void).cxx_destruct;
- (void)keyDown:(id)arg1;
- (BOOL)isFlipped;
- (void)updateSnapshot;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

