//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSButton, NSImageView, NSTextField, NSView;
@protocol WAAlertDialogDelegate;

@interface WAAlertDialog : NSObject
{
    id <WAAlertDialogDelegate> _delegate;
    NSButton *_backgroundRoot;
    NSView *_contentView;
    NSImageView *_contentBg;
    NSTextField *_tipsTitleLabel;
    NSTextField *_tipsContentLabel;
    NSView *_view;
    NSView *_alignView;
}

@property(nonatomic) __weak NSView *alignView; // @synthesize alignView=_alignView;
@property(nonatomic) __weak NSView *view; // @synthesize view=_view;
@property(retain, nonatomic) NSTextField *tipsContentLabel; // @synthesize tipsContentLabel=_tipsContentLabel;
@property(retain, nonatomic) NSTextField *tipsTitleLabel; // @synthesize tipsTitleLabel=_tipsTitleLabel;
@property(retain, nonatomic) NSImageView *contentBg; // @synthesize contentBg=_contentBg;
@property(retain, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSButton *backgroundRoot; // @synthesize backgroundRoot=_backgroundRoot;
@property(nonatomic) __weak id <WAAlertDialogDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)fadeIn:(double)arg1;
- (void)hide;
- (void)onClickBtn:(id)arg1;
- (void)setButtonColor:(id)arg1 withTag:(long long)arg2;
- (void)setButtonTitle:(id)arg1 cancel:(id)arg2;
- (id)bulidNSAttributedStringText:(id)arg1;
- (void)setContent:(id)arg1 title:(id)arg2;
- (id)initWithWebView:(id)arg1;
- (void)dealloc;
- (id)initWithWebView:(id)arg1 alignView:(id)arg2;

@end

