//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSString;

@interface WAAppDeviceMediaService : MMService <MMService>
{
    BOOL _bPrivacyLocation;
    BOOL _bPrivacyCamera;
    BOOL _bPrivacyMicrophone;
    BOOL _bPrivacyPhotoAddi;
    BOOL _isAVCaptureSessionRunning;
    BOOL _isAudioSessionRunning;
}

@property(nonatomic) BOOL isAudioSessionRunning; // @synthesize isAudioSessionRunning=_isAudioSessionRunning;
@property(nonatomic) BOOL isAVCaptureSessionRunning; // @synthesize isAVCaptureSessionRunning=_isAVCaptureSessionRunning;
@property(nonatomic) BOOL bPrivacyPhotoAddi; // @synthesize bPrivacyPhotoAddi=_bPrivacyPhotoAddi;
@property(nonatomic) BOOL bPrivacyMicrophone; // @synthesize bPrivacyMicrophone=_bPrivacyMicrophone;
@property(nonatomic) BOOL bPrivacyCamera; // @synthesize bPrivacyCamera=_bPrivacyCamera;
@property(nonatomic) BOOL bPrivacyLocation; // @synthesize bPrivacyLocation=_bPrivacyLocation;
- (void)showScreenCapturePrivacyAlert;
- (void)showMicrophonePrivacyAlert;
- (void)showCameraPrivacyAlert;
- (BOOL)isVisiable:(id)arg1;
- (void)setEnableUsePhoto:(BOOL)arg1;
- (void)setEnableUseRecord:(BOOL)arg1;
- (void)setEnableUseCamera:(BOOL)arg1;
- (void)setEnableUseLocation:(BOOL)arg1;
- (BOOL)isMacLocationScopeKey:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

