//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSWindowDelegate-Protocol.h"

@class NSString, WAAppWindow, WANavigationController;

@interface WAAppWindowController : NSWindowController <NSWindowDelegate>
{
    WANavigationController *_navigationController;
}

@property(retain, nonatomic) WANavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;
- (void)updateWindowFrame:(BOOL)arg1;
- (void)beginWidesscreen:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)dealloc;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)initWithWindowNibName:(id)arg1 owner:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain) WAAppWindow *window; // @dynamic window;

@end

