//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "MMCGIDelegate-Protocol.h"

@class NSString;

@interface WAAppTrialInfoLoader : MMObject <MMCGIDelegate>
{
    CDUnknownBlockType m_completeBlock;
}

- (void).cxx_destruct;
- (void)updateNotifyInfoWithDownloadUrl:(id)arg1 md5Str:(id)arg2 extInfo:(id)arg3 oldNotify:(id)arg4;
- (void)sendRequest:(id)arg1 Retry:(unsigned int)arg2;
- (void)dealloc;
- (void)handleCheckTrialInfoResponse:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)loadTrialInfoWithPack:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

