//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class CContact, MMAppMouseEventView, MMUILabel, NSArray, NSButton, NSImage, NSImageView, NSMutableArray, NSString, NSView;
@protocol WAAppActionSheetDelegate;

@interface WAAppActionSheet : MMObject
{
    CContact *m_contact;
    unsigned long long m_appType;
    NSArray *m_btnTitles;
    NSArray *m_debugTitles;
    NSString *m_cancelTitle;
    NSString *m_destructiveTitle;
    NSImage *m_fakeViewImage;
    BOOL _isUseWeAppModule;
    id <WAAppActionSheetDelegate> m_delegate;
    long long _menuPrivacyState;
    unsigned long long _componentOptions;
    MMAppMouseEventView *_interateView;
    NSView *_containerView;
    NSMutableArray *_btnArray;
    NSButton *_destructiveBtn;
    NSButton *_cancelBtn;
    NSImageView *_maskView;
    MMUILabel *_headerTitleLabel;
    NSView *_parentView;
}

@property(nonatomic) __weak NSView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) MMUILabel *headerTitleLabel; // @synthesize headerTitleLabel=_headerTitleLabel;
@property(retain, nonatomic) NSImageView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) NSButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) NSButton *destructiveBtn; // @synthesize destructiveBtn=_destructiveBtn;
@property(retain, nonatomic) NSMutableArray *btnArray; // @synthesize btnArray=_btnArray;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MMAppMouseEventView *interateView; // @synthesize interateView=_interateView;
@property(nonatomic) unsigned long long componentOptions; // @synthesize componentOptions=_componentOptions;
@property(nonatomic) long long menuPrivacyState; // @synthesize menuPrivacyState=_menuPrivacyState;
@property(nonatomic) BOOL isUseWeAppModule; // @synthesize isUseWeAppModule=_isUseWeAppModule;
@property(nonatomic) __weak id <WAAppActionSheetDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)_releaseViews;
- (void)onCancelButtonClick:(id)arg1;
- (void)onDestructiveButtonClick:(id)arg1;
- (void)onHeaerButtonClicked:(id)arg1;
- (void)onButtonClicked:(id)arg1;
- (id)genWeAppInfoBtnWithContact:(id)arg1 appType:(unsigned long long)arg2;
- (id)genDestructiveBtn;
- (id)genNormalBtn:(id)arg1;
- (id)genPrivacyStateView;
- (void)initMaskView;
- (void)initInterateView;
- (void)initContainerView;
- (void)setDebugTitles:(id)arg1;
- (BOOL)isVisible;
- (void)dismissWithAnimation;
- (void)showInView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (double)getActionSheetWidth;
- (id)getHeaderButtonTitle:(id)arg1;
- (void)dealloc;
- (id)initWithUsrName:(id)arg1 appType:(unsigned long long)arg2 cancelButtonTitle:(id)arg3 destructiveButtonTitle:(id)arg4 buttonTitleArray:(id)arg5 delegate:(id)arg6;

@end

