//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface WAAppStateChangedContextInfoHangupInfo : MMObject
{
    BOOL _isHangingUp;
    BOOL _isHangUpInteruptedByOtherWeapp;
}

@property(nonatomic) BOOL isHangUpInteruptedByOtherWeapp; // @synthesize isHangUpInteruptedByOtherWeapp=_isHangUpInteruptedByOtherWeapp;
@property(nonatomic) BOOL isHangingUp; // @synthesize isHangingUp=_isHangingUp;
- (id)description;

@end

