//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class ITSwitch, MMUILabel;
@protocol WAAppAuthorizationCellViewDelegate;

@interface WAAppAuthorizationCellView : NSTableCellView
{
    id <WAAppAuthorizationCellViewDelegate> _delegate;
    MMUILabel *_titleLabel;
    ITSwitch *_authSwitch;
}

@property(retain, nonatomic) ITSwitch *authSwitch; // @synthesize authSwitch=_authSwitch;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <WAAppAuthorizationCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onSwitchChange:(id)arg1;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

