//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSArray, NSColor, WAAppTabBarItem;
@protocol WAAppTabBarDelegate;

@interface WAAppTabBar : NSView
{
    id <WAAppTabBarDelegate> _delegate;
    NSArray *_items;
    WAAppTabBarItem *_selectedItem;
    NSColor *_backgroundColor;
    NSView *_backgroundView;
    NSView *_lineView;
}

@property(retain, nonatomic) NSView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) NSView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) __weak WAAppTabBarItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <WAAppTabBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getBadgeViewForIndex:(unsigned long long)arg1;
- (void)onClickItem:(id)arg1;
- (void)cleanItems;
- (void)unpdateItemsFrame;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

