//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "WAAppAuthorizationCellViewDelegate-Protocol.h"
#import "WAAppDetailInfoManagerExtension-Protocol.h"

@class CContact, NSMutableArray, NSString, NSTableView, NSView;
@protocol WAAppAuthorizationDelegate;

@interface WAAppAuthorizationViewController : WAViewController <WAAppDetailInfoManagerExtension, NSTableViewDelegate, NSTableViewDataSource, WAAppAuthorizationCellViewDelegate>
{
    NSString *m_appid;
    NSMutableArray *m_authorationList;
    BOOL m_isAuthInfoChanged;
    int m_receiveMsgSwitchOriginalStatus;
    int m_receiveMsgSwitchLastStatus;
    CContact *_contact;
    id <WAAppAuthorizationDelegate> _delegate;
    NSTableView *_tableView;
    NSView *_emptyView;
}

@property(retain, nonatomic) NSView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WAAppAuthorizationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (id)getLocalScopeDesc:(id)arg1;
- (void)setReceiveMsgOriginalStatus;
- (void)setReceiveMsgLastStatusIfNeed:(id)arg1;
- (void)reloadData;
- (void)onGetAppAuthInfoList:(id)arg1 appid:(id)arg2 errorCode:(int)arg3;
- (void)authorizationCellViewSwitchStateChange:(id)arg1;
- (void)requestAuthorazitionInfo;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)initEmptyView;
- (void)initViews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

