//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSString;

@interface WAAppItemManager : MMService <MMService>
{
    unsigned int m_localUpdateTimeOfLastVisibleItem;
    unsigned int m_updateTimeOfFirstVisibleItem;
    unsigned int m_remoteUpdateTimeOfLastVisibleItem;
    unsigned int m_biggestUpdateTimeOfStarItem;
    unsigned int m_showOutErrTime;
}

+ (unsigned long long)getAppUserStateByUsername:(id)arg1;
+ (unsigned long long)getAppUserStateByUsername:(id)arg1 appType:(unsigned int)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

