//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString, NSURL;
@protocol IWAAudioPlayerDelegate;

@protocol WAAudioPlayerInterface <NSObject>
@property(readonly, nonatomic) long long state;
@property(readonly, nonatomic) double volume;
@property(readonly, nonatomic) double bufferTime;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) double curTime;
@property(readonly, nonatomic) double startTime;
@property(readonly, nonatomic) NSString *src;
@property(readonly, nonatomic) NSString *audioId;
- (BOOL)isIdle;
- (BOOL)isWaiting;
- (BOOL)isPaused;
- (BOOL)isPlaying;
- (BOOL)isSet;
- (void)seekTo:(double)arg1;
- (void)stop;
- (void)forcePause;
- (void)pause;
- (void)play;
- (void)setPlayerWithSrc:(NSString *)arg1 url:(NSURL *)arg2 startTime:(double)arg3 autoPlay:(BOOL)arg4 loop:(BOOL)arg5 obeyMuteSwitch:(BOOL)arg6 volume:(double)arg7 fileData:(NSData *)arg8;
- (id)initWithAudioId:(NSString *)arg1 appId:(NSString *)arg2 delegate:(id <IWAAudioPlayerDelegate>)arg3;
@end

