//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATouchBaseView.h"

@class MMUILabel, NSColor, NSDictionary, NSString, NSView;
@protocol WABaseViewDelegate;

@interface WABaseView : WATouchBaseView
{
    double _padding[4];
    double _alignOffset;
    double _rotate;
    double _scaleX;
    double _scaleY;
    BOOL _clickable;
    BOOL _bEventToWebView;
    BOOL _fixed;
    unsigned int _viewId;
    NSString *_userData;
    id <WABaseViewDelegate> _delegate;
    unsigned long long _type;
    MMUILabel *_label;
    NSView *_background;
    NSDictionary *_style;
    NSColor *_customBackgroundColor;
}

@property(retain, nonatomic) NSColor *customBackgroundColor; // @synthesize customBackgroundColor=_customBackgroundColor;
@property(retain, nonatomic) NSDictionary *style; // @synthesize style=_style;
@property(retain, nonatomic) NSView *background; // @synthesize background=_background;
@property(retain, nonatomic) MMUILabel *label; // @synthesize label=_label;
@property(nonatomic) BOOL fixed; // @synthesize fixed=_fixed;
@property(nonatomic) unsigned int viewId; // @synthesize viewId=_viewId;
@property(nonatomic) BOOL bEventToWebView; // @synthesize bEventToWebView=_bEventToWebView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) __weak id <WABaseViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *userData; // @synthesize userData=_userData;
- (void).cxx_destruct;
- (BOOL)clickable;
- (void)onButtonClick:(id)arg1;
- (void)setBorderStyle:(id)arg1;
- (void)setBackground:(id)arg1 style:(id)arg2 clickable:(BOOL)arg3;
- (id)getBackgroundImage:(id)arg1;
- (void)setClickable:(BOOL)arg1;
- (void)updateBackgoundImage:(id)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)setLabelWithParam:(id)arg1;
- (BOOL)isFlipped;
- (id)description;
- (id)init;

@end

