//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSImage, NSString;

@protocol WACameraLogicControllerDelegate <NSObject>

@optional
- (NSString *)getAppID;
- (void)onCameraVideoRecordingWithFrameImg:(NSImage *)arg1;
- (void)onCameraVideoTakenFail;
- (void)onCameraVideoTakenSuccess:(NSString *)arg1 thumbImg:(NSImage *)arg2 isMuted:(BOOL)arg3;
- (void)onCameraPictureTaken:(NSImage *)arg1 withFrontCamera:(BOOL)arg2;
- (void)onCameraScanCode:(NSDictionary *)arg1;
- (void)onCameraStopRecord;
- (void)onCameraStartRecord;
- (void)onCameraStop;
- (void)onCameraNeedAuthCancel;
@end

