//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"
#import "WACameraQRCodeScannerDelegate-Protocol.h"

@class NSImage, NSMutableArray, NSMutableDictionary, NSString, WACameraCapture, WACameraPreviewView, WACameraScanScanner;
@protocol OS_dispatch_queue, WACameraLogicControllerDelegate;

@interface WACameraLogicController : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, WACameraQRCodeScannerDelegate>
{
    struct opaqueCMSampleBuffer *_buffer;
    NSMutableArray *m_compressorAry;
    unsigned int m_currID;
    NSObject<OS_dispatch_queue> *m_logicQueue;
    NSMutableArray *m_recordIDAry;
    unsigned int m_currWriterID;
    BOOL isShowingPreview;
    BOOL isCameraAppear;
    BOOL bNeedOutputVideoBuffer;
    BOOL _shouldHandleScan;
    BOOL _m_isTakingPicture;
    BOOL _m_shouldStart;
    BOOL _m_requestAuthAccess;
    BOOL _m_isNeedResumeWXMusic;
    int _recordState;
    id <WACameraLogicControllerDelegate> _delegate;
    WACameraPreviewView *_cameraPreview;
    NSString *_m_videoPath;
    NSImage *_m_thumbImage;
    NSImage *_m_originalImage;
    NSMutableDictionary *_recorderDict;
    WACameraScanScanner *_cameraScanScanner;
    WACameraCapture *_cameraCapture;
}

+ (BOOL)isAuthStatusOK;
+ (BOOL)needCheckRequestAuthAccess;
@property(retain, nonatomic) WACameraCapture *cameraCapture; // @synthesize cameraCapture=_cameraCapture;
@property(nonatomic) BOOL m_isNeedResumeWXMusic; // @synthesize m_isNeedResumeWXMusic=_m_isNeedResumeWXMusic;
@property(retain, nonatomic) WACameraScanScanner *cameraScanScanner; // @synthesize cameraScanScanner=_cameraScanScanner;
@property(retain, nonatomic) NSMutableDictionary *recorderDict; // @synthesize recorderDict=_recorderDict;
@property(nonatomic) BOOL m_requestAuthAccess; // @synthesize m_requestAuthAccess=_m_requestAuthAccess;
@property(nonatomic) BOOL m_shouldStart; // @synthesize m_shouldStart=_m_shouldStart;
@property(nonatomic) int recordState; // @synthesize recordState=_recordState;
@property(retain, nonatomic) NSImage *m_originalImage; // @synthesize m_originalImage=_m_originalImage;
@property(nonatomic) BOOL m_isTakingPicture; // @synthesize m_isTakingPicture=_m_isTakingPicture;
@property(retain, nonatomic) NSImage *m_thumbImage; // @synthesize m_thumbImage=_m_thumbImage;
@property(retain, nonatomic) NSString *m_videoPath; // @synthesize m_videoPath=_m_videoPath;
@property(retain, nonatomic) WACameraPreviewView *cameraPreview; // @synthesize cameraPreview=_cameraPreview;
@property(nonatomic) BOOL shouldHandleScan; // @synthesize shouldHandleScan=_shouldHandleScan;
@property(nonatomic) __weak id <WACameraLogicControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL bNeedOutputVideoBuffer; // @synthesize bNeedOutputVideoBuffer;
@property(nonatomic) BOOL isCameraAppear; // @synthesize isCameraAppear;
@property(nonatomic) BOOL isShowingPreview; // @synthesize isShowingPreview;
- (void).cxx_destruct;
- (BOOL)compressVideo:(id)arg1 to:(id)arg2;
- (void)filterType:(unsigned long long)arg1;
- (void)setCameraPositon:(long long)arg1;
- (void)setFlashType:(long long)arg1;
- (void)switchCamera;
- (void)switchCameraToDevices:(id)arg1;
- (void)didTakeDoneWithSightPath:(id)arg1 thumbImg:(id)arg2 isMuted:(BOOL)arg3;
- (void)didTakeDoneWithPicture:(id)arg1;
- (void)didTapRetake;
- (void)onTakenPicture:(id)arg1;
- (BOOL)takePicture;
- (BOOL)stopRecord;
- (BOOL)startRecord;
- (void)showPreviewViewWithSightPath:(id)arg1 thumbImg:(id)arg2;
- (void)showPreviewViewWithImage:(id)arg1;
- (void)cancelWriterWithoutReprepare;
- (void)cancelWriter;
- (void)compressVideoIfNeeded:(id)arg1;
- (BOOL)finishWriter;
- (BOOL)startWriter;
- (float)sightCaptureMaxDuration;
- (void)onCameraStop:(id)arg1;
- (void)onWriterResign;
- (void)onMovieCompressFinished:(int)arg1 moviePath:(id)arg2 withThumb:(id)arg3;
- (void)onWriterFailed:(int)arg1;
- (void)pauseCamera;
- (void)resumeCamera;
- (void)removeCameraCropFilter;
- (void)setScanFreq:(double)arg1;
- (void)setScanCropRect:(struct CGRect)arg1;
- (void)setCameraCropRect:(struct CGRect)arg1;
- (void)updateCameraPreviewRect:(struct CGRect)arg1;
- (void)loadCameraLogicWithContentView:(id)arg1;
- (BOOL)isFinishInitial;
- (id)inputDevices;
- (void)didEnterForeground;
- (void)didEnterBackground;
- (void)dealloc;
- (id)initWithInputType:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

