//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVCaptureAudioDataOutputSampleBufferDelegate-Protocol.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"

@class AVCaptureConnection, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, NSString, WACameraManager, WAMovieManager;

@interface WACameraCapture : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    AVCaptureSession *_session;
    AVCaptureDeviceInput *_deviceInput;
    AVCaptureConnection *_videoConnection;
    AVCaptureConnection *_audioConnection;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureStillImageOutput *_imageOutput;
    BOOL _recording;
    WAMovieManager *_movieManager;
    WACameraManager *_cameraManager;
    AVCaptureDevice *_activeCamera;
    unsigned long long _inputType;
}

@property(nonatomic) unsigned long long inputType; // @synthesize inputType=_inputType;
@property(retain, nonatomic) AVCaptureDevice *activeCamera; // @synthesize activeCamera=_activeCamera;
@property(retain, nonatomic) WACameraManager *cameraManager; // @synthesize cameraManager=_cameraManager;
@property(retain, nonatomic) WAMovieManager *movieManager; // @synthesize movieManager=_movieManager;
- (void).cxx_destruct;
- (long long)currentPhotoOrientation;
- (long long)currentVideoOrientation;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)stopRecordVideoCompletion:(CDUnknownBlockType)arg1;
- (void)startRecordVideoToPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)takePhotoCompletion:(CDUnknownBlockType)arg1;
- (void)swicthCameraToDevice:(id)arg1 actionHandle:(CDUnknownBlockType)arg2;
- (void)torchLightActionHandle:(CDUnknownBlockType)arg1;
- (void)flashLightActionHandle:(CDUnknownBlockType)arg1;
- (void)setFlashlightMode:(long long)arg1;
- (void)autoFocusAndExposureActionHandle:(CDUnknownBlockType)arg1;
- (void)exposActionToPoint:(struct CGPoint)arg1 handle:(CDUnknownBlockType)arg2;
- (void)focusActionToPoint:(struct CGPoint)arg1 handle:(CDUnknownBlockType)arg2;
- (void)stopCaptureSession;
- (void)startCaptureSession;
- (void)setupSessionOutputs:(id *)arg1;
- (void)setupSessionInputs:(id *)arg1;
- (id)previewLayer;
- (BOOL)isAVCaptureSessionAvailble;
- (void)setupSession:(id *)arg1;
- (void)dealloc;
- (BOOL)setup;
- (id)initWithInputType:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

