//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IWALocalCacheMgrExt-Protocol.h"
#import "MMCGIDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, WAAppTaskExtInfo, WAInfoData, WALoadingViewController;

@interface WACacheVersionChecker : NSObject <IWALocalCacheMgrExt, MMCGIDelegate>
{
    unsigned long long _checkScene;
    NSString *_appID;
    NSString *_userName;
    WAInfoData *_appInfoData;
    unsigned int _appType;
    BOOL _isCancelled;
    CDUnknownBlockType _completeHandler;
    CDUnknownBlockType _progressHandler;
    BOOL _isUseModule;
    WAInfoData *_bootModuleInfoData;
    WAInfoData *_subModuleInfoData;
    NSMutableArray *_arrDownloadInfoData;
    NSDictionary *_dicExtraInfo;
    WAAppTaskExtInfo *_taskExtInfo;
    NSString *_relativePath;
    WALoadingViewController *_loadingVC;
    unsigned long long _startDownloadTime;
    BOOL _isDownloadStart;
    BOOL _hasReported;
    unsigned long long _updatePackageStartTime;
}

- (void).cxx_destruct;
- (void)reportUpdatePackageTime;
- (void)reportLoadPackageInvalid:(id)arg1;
- (unsigned long long)appstateWithExtraInfo:(id)arg1;
- (void)reportIntallOrUpdateInfo:(BOOL)arg1 errorCode:(unsigned int)arg2;
- (void)onUpdateAppPkgComplete:(BOOL)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 totalLength:(unsigned long long)arg3 withAppInfoData:(id)arg4;
- (void)callCompletionHandlerWithSuccess:(BOOL)arg1 errorCode:(long long)arg2;
- (void)removeDownloadInfoData:(id)arg1;
- (BOOL)hasDownloadInfoData:(id)arg1;
- (unsigned long long)downloadInfoDataCount;
- (void)addDownloadInfoData:(id)arg1;
- (void)checkLocalCacheWithInfoDataList:(id)arg1 getDownloadInfoDataList:(id)arg2;
- (BOOL)checkLocalCacheOK:(id)arg1;
- (BOOL)startDownloadPkgWithAppInfoData:(id)arg1 CDNURL:(id)arg2 patchURL:(id)arg3;
- (void)handleGetDebugModePkgDownloadUrl:(id)arg1;
- (BOOL)getDebugModePkgDownloadUrlWithAppInfoData:(id)arg1;
- (void)handleGetRemoteCDNPkgDownloadUrl:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (BOOL)getRemoteCDNPkgDownloadUrlWithAppInfoData:(id)arg1;
- (void)triggerPkgDownloadWithAppInfoData:(id)arg1;
- (void)resetOldExistVersionIfFileNotExist:(id)arg1;
- (id)getBootModuleInfoDataWithPackageConfig:(id)arg1 relativeUrl:(id)arg2;
- (id)getInfoDataWithPackageConfig:(id)arg1 moduleName:(id)arg2;
- (id)generateInfoDataWithPackageConfig:(id)arg1 relativeUrl:(id)arg2;
- (void)cancel;
- (void)checkModuleCacheReadyWithPackageConfig:(id)arg1 moduleName:(id)arg2 completeHandler:(CDUnknownBlockType)arg3 progressHandler:(CDUnknownBlockType)arg4;
- (void)tryDoDecryptAndRemoveDecryptEnabledInfoData:(id)arg1;
- (void)checkCacheReadyWithContext:(id)arg1 completeHandler:(CDUnknownBlockType)arg2 progressHandler:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)initWithAppID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

