//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface WAContainerView : NSView
{
    NSView *_scrollView;
    NSView *_nativeView;
}

@property(nonatomic) __weak NSView *nativeView; // @synthesize nativeView=_nativeView;
@property(nonatomic) __weak NSView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;
- (void)updateContainer;
- (void)removeNativeView;

@end

