//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPickerViewController.h"

#import "NSDatePickerCellDelegate-Protocol.h"

@class NSDatePicker, NSString;

@interface WADatePickerViewController : WAPickerViewController <NSDatePickerCellDelegate>
{
    unsigned long long _mode;
    unsigned long long _customMode;
    NSDatePicker *_picker;
    NSString *_field;
    NSString *_format;
}

@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
@property(copy, nonatomic) NSString *field; // @synthesize field=_field;
@property(retain, nonatomic) NSDatePicker *picker; // @synthesize picker=_picker;
@property(nonatomic) unsigned long long customMode; // @synthesize customMode=_customMode;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (void)updatePickerElements;
- (void)datePickerCell:(id)arg1 validateProposedDateValue:(id *)arg2 timeInterval:(double *)arg3;
- (void)setCurrent:(id)arg1;
- (id)dateValue;
- (struct CGSize)viewSize;
- (void)viewDidLoad;
- (void)setup;
- (id)init;
- (id)initWithMode:(unsigned long long)arg1 field:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

