//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "IMusicPlayerExt-Protocol.h"

@class NSString;

@interface WAJSContextPlugin_operateMusic : WAJSContextPluginBase <IMusicPlayerExt>
{
    NSString *_currentMusic;
}

@property(retain) NSString *currentMusic; // @synthesize currentMusic=_currentMusic;
- (void).cxx_destruct;
- (void)onMusicPlayInnerStatusChanged:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (void)onPlayMusic:(id)arg1 fromScene:(int)arg2;
- (BOOL)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (BOOL)monopolizeMusicPlayer;
- (id)getCurrentMusicId;
- (id)generateMusicId:(id)arg1;
- (double)getDuration;
- (void)seekPlay:(float)arg1;
- (void)stopMusic;
- (void)resumeMusic;
- (void)pauseMusic;
- (BOOL)isPlaying;
- (BOOL)isPlaused;
- (void)dealloc;
- (void)playMusic:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

