//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "WATakePhotoViewControllerDelegate-Protocol.h"

@class NSString, WATakePhotoViewController;

@interface WAJSEventHandler_chooseImage : WAJSEventHandler_BaseEvent <WATakePhotoViewControllerDelegate>
{
    unsigned int m_imgCnt;
    long long m_sizeType;
    long long m_sourceType;
    BOOL _frontCamera;
    WATakePhotoViewController *_chooseImageViewController;
}

@property(retain, nonatomic) WATakePhotoViewController *chooseImageViewController; // @synthesize chooseImageViewController=_chooseImageViewController;
- (void).cxx_destruct;
- (void)takePhotoDidFinish:(id)arg1;
- (void)takePhotoDidCancel;
- (void)delayNotifyWeb:(id)arg1;
- (void)onLocalImageSaveFinish:(id)arg1;
- (long long)getImagePickerSizeType:(id)arg1;
- (void)compressImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processImages:(id)arg1;
- (void)handleImages:(id)arg1;
- (void)openPanel;
- (void)openTakePhotoPanel;
- (void)openChosseImageMenu;
- (void)asyncHandleCancel;
- (void)handleJSEvent:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

