//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "MMCGIDelegate-Protocol.h"
#import "WAAppScopeConfirmWindowDelegate-Protocol.h"
#import "WAJSContextPlugin_userAccountProtocol-Protocol.h"

@class NSDictionary, NSString, WAAppScopeConfirmWindow, WAJSContextPlugin_userAccount;

@interface WAJSEventHandler_authorize : WAJSEventHandler_BaseEvent <MMCGIDelegate, WAAppScopeConfirmWindowDelegate, WAJSContextPlugin_userAccountProtocol>
{
    NSString *_appID;
    WAAppScopeConfirmWindow *_confirmWindow;
    unsigned int _eventId;
    BOOL _requestInQueue;
    NSDictionary *_dicInputParam;
    WAJSContextPlugin_userAccount *_userAccountInstance;
}

@property(nonatomic) BOOL requestInQueue; // @synthesize requestInQueue=_requestInQueue;
@property(nonatomic) __weak WAJSContextPlugin_userAccount *userAccountInstance; // @synthesize userAccountInstance=_userAccountInstance;
@property(retain) NSDictionary *dicInputParam; // @synthesize dicInputParam=_dicInputParam;
- (void).cxx_destruct;
- (void)onScopeWindowCancel:(id)arg1 withScope:(id)arg2;
- (void)onScopeWindowConfirm:(id)arg1 withScope:(id)arg2;
- (void)onConfirmViewCancel:(id)arg1;
- (void)onConfirmViewOKWithScope:(id)arg1;
- (void)closeConfirmWindow;
- (void)showConfirmViewWithResponse:(id)arg1;
- (void)continueShowConfirmViewWithResponse:(id)arg1;
- (void)stopLoading;
- (void)startLoading:(id)arg1;
- (void)OnResponseCGIFailedWithSessionId:(unsigned int)arg1 cgiWrap:(id)arg2 errType:(unsigned int)arg3 errCode:(unsigned int)arg4;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onConfirmResponse:(id)arg1;
- (void)confirmRequestWithAppID:(id)arg1 scope:(id)arg2;
- (void)onAuthorizeResponse:(id)arg1;
- (void)authorizeRequestWithAppID:(id)arg1 scope:(id)arg2;
- (void)endCancel;
- (void)endOK;
- (void)endErrorWithMessage:(id)arg1 code:(int)arg2;
- (void)endErrorWithMessage:(id)arg1;
- (void)endWithResult:(id)arg1;
- (void)handleJSEvent:(id)arg1;
- (void)onUserAccountJSEventEnd;
- (void)mainThread_runUserAccountJSEvent:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

