//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

@class NSColor, NSMutableArray, NSMutableDictionary, NSView;

@interface WAJSContextPlugin_CustomTabBar : WAJSContextPluginBase
{
    BOOL _m_IsChangeTab;
    BOOL _isTopTabBar;
    BOOL _bIsLoading;
    BOOL _isTabbarAnimating;
    BOOL _isTabbarVisible;
    long long m_TabItemCount;
    long long _mainTabIndex;
    long long _curSelectedIndex;
    NSView *_topCoverBoderLine;
    NSView *_topSelectedLine;
    NSColor *_textColor;
    NSColor *_selectTextColor;
    NSMutableArray *_arrTabItemData;
    NSMutableDictionary *_dicTabWebView;
    NSMutableArray *_tabBarBtns;
    NSMutableArray *_badgeViews;
}

@property(nonatomic) BOOL isTabbarVisible; // @synthesize isTabbarVisible=_isTabbarVisible;
@property(nonatomic) BOOL isTabbarAnimating; // @synthesize isTabbarAnimating=_isTabbarAnimating;
@property(retain, nonatomic) NSMutableArray *badgeViews; // @synthesize badgeViews=_badgeViews;
@property(retain, nonatomic) NSMutableArray *tabBarBtns; // @synthesize tabBarBtns=_tabBarBtns;
@property(retain, nonatomic) NSMutableDictionary *dicTabWebView; // @synthesize dicTabWebView=_dicTabWebView;
@property(retain, nonatomic) NSMutableArray *arrTabItemData; // @synthesize arrTabItemData=_arrTabItemData;
@property(retain, nonatomic) NSColor *selectTextColor; // @synthesize selectTextColor=_selectTextColor;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSView *topSelectedLine; // @synthesize topSelectedLine=_topSelectedLine;
@property(retain, nonatomic) NSView *topCoverBoderLine; // @synthesize topCoverBoderLine=_topCoverBoderLine;
@property(nonatomic) BOOL bIsLoading; // @synthesize bIsLoading=_bIsLoading;
@property(nonatomic) long long curSelectedIndex; // @synthesize curSelectedIndex=_curSelectedIndex;
@property(nonatomic) long long mainTabIndex; // @synthesize mainTabIndex=_mainTabIndex;
@property(nonatomic) BOOL isTopTabBar; // @synthesize isTopTabBar=_isTopTabBar;
@property(nonatomic) BOOL m_IsChangeTab; // @synthesize m_IsChangeTab=_m_IsChangeTab;
@property(nonatomic) long long m_TabItemCount; // @synthesize m_TabItemCount;
- (void).cxx_destruct;
- (void)layoutBadgeView;
- (void)layoutTabbarByWAWebviewVC:(id)arg1;
- (void)hideBadgeOnItemIndex:(long long)arg1;
- (void)setTabBarBadgeImage:(id)arg1 forIndex:(long long)arg2;
- (id)getBadgeViewForIndex:(long long)arg1;
- (id)getTabBarBtnForIndex:(long long)arg1;
- (void)setTabBarBadgeString:(id)arg1 badgeColor:(id)arg2 forIndex:(long long)arg3;
- (int)getBadgeViewRightMarginPortraitAtIndex:(long long)arg1;
- (id)getBadgeViews;
- (id)getTabBarBtnViews;
- (BOOL)isVisible;
- (void)setTabBarVisible:(BOOL)arg1 animate:(BOOL)arg2;
- (void)setTabBarVisible:(BOOL)arg1;
- (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (void)delaySwitchTabItemWithIndex:(id)arg1;
- (void)loadTabWebViewWithIndex:(long long)arg1;
- (void)frameChanged;
- (void)switchToTabItem:(long long)arg1;
- (void)updateTopTabBarSelectedLinePosition;
- (void)bringTabBarToFront;
- (struct CGRect)currentTabBarFrame;
- (void)setTabBarStyleWithTextColor:(id)arg1 selectTextColor:(id)arg2 backgroundColor:(id)arg3 borderColor:(id)arg4;
- (void)setItemAtTabIndex:(long long)arg1 text:(id)arg2 iconImage:(id)arg3 selectIconImage:(id)arg4;
- (void)createChildVCTabBarWithItems:(id)arg1 mainTabIndex:(long long)arg2 position:(id)arg3 backgroundColor:(id)arg4 textColor:(id)arg5 selectedTextColor:(id)arg6 borderColor:(id)arg7;
- (BOOL)constructByFirstWAWebviewVC:(id)arg1;
- (BOOL)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (id)init;
- (BOOL)isLoadingTab;
- (id)getTabWebViewAtIndex:(unsigned long long)arg1;
- (BOOL)isTabWebVC:(id)arg1;
- (id)getSelectedTabWebView;
- (BOOL)isTabCreatedWithPagePath:(id)arg1;
- (void)selectTabWithPagePath:(id)arg1;
- (void)selectMainTab;
- (BOOL)isSelectedMainTab;
- (void)clearTabWebView;
- (id)getAllTabWebViews;
- (double)tabbarHeight;
- (void)dealloc;

@end

