//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@class NSString;

@interface WAJSEventHandler_UnsupportEvent : WAJSEventHandler_BaseEvent
{
    NSString *_eventName;
}

+ (id)unsupportEventDic;
@property(copy, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
- (void).cxx_destruct;
- (void)handleJSEvent:(id)arg1;

@end

