//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "NSMenuDelegate-Protocol.h"
#import "WAPickerViewControllerDelegate-Protocol.h"

@class NSArray, NSMenu, NSString, WAPickerViewController;

@interface WAJSEventHandler_showPickerView : WAJSEventHandler_BaseEvent <WAPickerViewControllerDelegate, NSMenuDelegate>
{
    long long _current;
    double _pickerTime;
    WAPickerViewController *_pickerViewController;
    NSArray *_items;
    NSMenu *_menu;
}

@property(retain, nonatomic) NSMenu *menu; // @synthesize menu=_menu;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak WAPickerViewController *pickerViewController; // @synthesize pickerViewController=_pickerViewController;
- (void).cxx_destruct;
- (void)pickerViewControllerOnCancelButtonClick:(id)arg1;
- (void)pickerViewController:(id)arg1 onConfirmButtonClick:(id)arg2;
- (void)showNormalPickerVC;
- (void)cancel;
- (void)menuDidClose:(id)arg1;
- (void)onMenuItemSelected:(id)arg1;
- (void)showMenu;
- (void)handleJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

