//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@class CaptureVideoInfo, WALoadingView;

@interface WAJSEventHandler_chooseVideo : WAJSEventHandler_BaseEvent
{
    CaptureVideoInfo *m_oVideoInfo;
    WALoadingView *m_loadingView;
    unsigned int _maxDuration;
    BOOL _isCameraMode;
    BOOL _isFrontCamera;
    BOOL _isCompressed;
}

+ (id)thumbForVideoWithPath:(id)arg1;
+ (void)mov2mp4withInputURL:(id)arg1 withOutputURL:(id)arg2 withTarget:(id)arg3 withSel:(SEL)arg4 withQuality:(id)arg5;
- (void).cxx_destruct;
- (void)didTakeVideo:(CDUnknownBlockType)arg1;
- (int)getVideoDuration:(id)arg1;
- (void)initLoadingView;
- (void)processVideo:(id)arg1;
- (void)handleVideo:(id)arg1;
- (void)openPanel;
- (void)handleJSEvent:(id)arg1;
- (void)dealloc;

@end

