//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAJSCoreServiceRemoteDelegate-Protocol.h"
#import "WARemoteDebugChannelDelegate-Protocol.h"
#import "WARemoteDebugSendQueueDelegate-Protocol.h"
#import "WCStateMachineDelegate-Protocol.h"

@class MMTimer, NSMutableDictionary, NSString, WAAppTask, WARemoteDebugChannel, WARemoteDebugLocalSendQueue, WARemoteDebugRecvQueue, WARemoteDebug_BaseReq, WCStateMachine, WKWebView;

@interface WALocalDebugger : NSObject <WARemoteDebugChannelDelegate, WCStateMachineDelegate, WARemoteDebugSendQueueDelegate, WAJSCoreServiceRemoteDelegate>
{
    unsigned int _channelType;
    unsigned int _supportCompressAlgo;
    unsigned int _todoReconnectCount;
    unsigned int _doneReconnectCount;
    unsigned int _evaluateID;
    unsigned int _alertBitset;
    unsigned int _maskBitset;
    WAAppTask *_task;
    WCStateMachine *_stateMachine;
    WARemoteDebugChannel *_channel;
    NSString *_roomID;
    NSString *_pkgInfo;
    WKWebView *_webView;
    NSMutableDictionary *_uuid2SendoutTimestapMap;
    WARemoteDebug_BaseReq *_baseReq;
    WARemoteDebugLocalSendQueue *_sendQueue;
    WARemoteDebugRecvQueue *_recvQueue;
    double _heartBeatTimestamp;
    MMTimer *_heartBeatTimer;
    MMTimer *_eventMessageTimer;
    MMTimer *_speedTimer;
    NSMutableDictionary *_jscID2IDWrapMap;
    NSString *_connectJSCID;
    long long _retryCount;
    MMTimer *_retryTimer;
}

@property(retain, nonatomic) MMTimer *retryTimer; // @synthesize retryTimer=_retryTimer;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) NSString *connectJSCID; // @synthesize connectJSCID=_connectJSCID;
@property(retain, nonatomic) NSMutableDictionary *jscID2IDWrapMap; // @synthesize jscID2IDWrapMap=_jscID2IDWrapMap;
@property(nonatomic) unsigned int maskBitset; // @synthesize maskBitset=_maskBitset;
@property(nonatomic) unsigned int alertBitset; // @synthesize alertBitset=_alertBitset;
@property(retain, nonatomic) MMTimer *speedTimer; // @synthesize speedTimer=_speedTimer;
@property(retain, nonatomic) MMTimer *eventMessageTimer; // @synthesize eventMessageTimer=_eventMessageTimer;
@property(retain, nonatomic) MMTimer *heartBeatTimer; // @synthesize heartBeatTimer=_heartBeatTimer;
@property(nonatomic) double heartBeatTimestamp; // @synthesize heartBeatTimestamp=_heartBeatTimestamp;
@property(retain, nonatomic) WARemoteDebugRecvQueue *recvQueue; // @synthesize recvQueue=_recvQueue;
@property(retain, nonatomic) WARemoteDebugLocalSendQueue *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(retain, nonatomic) WARemoteDebug_BaseReq *baseReq; // @synthesize baseReq=_baseReq;
@property(nonatomic) unsigned int evaluateID; // @synthesize evaluateID=_evaluateID;
@property(nonatomic) unsigned int doneReconnectCount; // @synthesize doneReconnectCount=_doneReconnectCount;
@property(nonatomic) unsigned int todoReconnectCount; // @synthesize todoReconnectCount=_todoReconnectCount;
@property(retain, nonatomic) NSMutableDictionary *uuid2SendoutTimestapMap; // @synthesize uuid2SendoutTimestapMap=_uuid2SendoutTimestapMap;
@property(nonatomic) unsigned int supportCompressAlgo; // @synthesize supportCompressAlgo=_supportCompressAlgo;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSString *pkgInfo; // @synthesize pkgInfo=_pkgInfo;
@property(retain, nonatomic) NSString *roomID; // @synthesize roomID=_roomID;
@property(retain, nonatomic) WARemoteDebugChannel *channel; // @synthesize channel=_channel;
@property(nonatomic) unsigned int channelType; // @synthesize channelType=_channelType;
@property(retain, nonatomic) WCStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(nonatomic) __weak WAAppTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (id)waServiceMD5;
- (void)showAlertWithMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)destorySpeedTimer;
- (void)initSpeedTimer;
- (void)destoryEventMessageTimer;
- (void)initEventMessageTimer;
- (void)destoryHeartBeatTimer;
- (void)checkEventMessageTimeout;
- (void)updateSpeed;
- (void)sendFrameData:(id)arg1 consoleLog:(id)arg2;
- (void)consoleLog:(id)arg1 isSendout:(BOOL)arg2;
- (void)onConnectJSContext:(id)arg1;
- (void)onChromeDevtools:(id)arg1;
- (void)onDomOp:(id)arg1;
- (void)onPing:(id)arg1;
- (void)onBreakpoint:(id)arg1;
- (void)onEvaluateJavascriptResult:(id)arg1;
- (void)onCallInterface:(id)arg1;
- (void)recvHandleMessage:(id)arg1;
- (void)onChannelReciveData:(id)arg1;
- (void)onChannelReciveString:(id)arg1;
- (void)onChannelDisconnected;
- (void)onChannelConnected;
- (void)enSendQueue:(id)arg1;
- (void)enSendQueueOnMainThread:(id)arg1;
- (void)remoteSetupContextWithConfigureJS:(id)arg1 publibVersion:(unsigned int)arg2 publibMD5:(id)arg3 threeJSMD5:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)remoteNetworkRequest:(id)arg1 taskID:(id)arg2 header:(id)arg3;
- (void)remoteEvaluateJavascript:(id)arg1;
- (void)remoteDomEvent:(id)arg1 webViewID:(unsigned int)arg2;
- (void)remoteCallInterfaceResult:(id)arg1 callID:(unsigned int)arg2;
- (void)remoteRemoveJSCoreIDWrap:(id)arg1;
- (void)remoteAddJSCoreIDWrap:(id)arg1;
- (void)reConnect;
- (void)onReconnectCancel;
- (void)handleClearDisconnect;
- (BOOL)isGameDebugBitBreakpoint;
- (void)updateMaskView;
- (void)handleDisconnectWithCode:(long long)arg1;
- (void)onHeartBeatResp:(id)arg1;
- (void)onReconnectConfirm;
- (void)onResendCancel;
- (void)onResendConfirm;
- (void)performReconnectLater;
- (void)disConnect;
- (BOOL)hasLocalJSCore;
- (void)sendPbReq:(id)arg1 frameCmd:(unsigned int)arg2;
- (void)quitRoom;
- (void)endDebug;
- (void)endDebugAndClostTask;
- (void)onChannelFailed;
- (void)onRemoteDebugWillEnd;
- (void)showEndAlert:(id)arg1;
- (void)alterEndReason:(id)arg1;
- (void)beginDebugWithRoomID:(id)arg1 pkgInfo:(id)arg2 debugUrl:(id)arg3 channelType:(unsigned int)arg4 proxyPort:(unsigned int)arg5 supportCompressAlgo:(unsigned int)arg6;
- (void)setupMessageTypeLookup;
- (void)setupStateMachine;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

