//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JSValue;

@interface WALockItem : NSObject
{
    BOOL _writeLock;
    unsigned int _workerId;
    JSValue *_block;
}

+ (id)itemWithNoBlock:(unsigned int)arg1 writeLock:(BOOL)arg2;
+ (id)itemWithBlock:(unsigned int)arg1 block:(id)arg2 writeLock:(BOOL)arg3;
@property(retain, nonatomic) JSValue *block; // @synthesize block=_block;
@property(nonatomic) BOOL writeLock; // @synthesize writeLock=_writeLock;
@property(nonatomic) unsigned int workerId; // @synthesize workerId=_workerId;
- (void).cxx_destruct;

@end

