//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAssetWriter, AVAssetWriterInput, AVCaptureDevice, NSURL;
@protocol OS_dispatch_queue;

@interface WAMovieManager : NSObject
{
    BOOL _readyToRecordVideo;
    BOOL _readyToRecordAudio;
    NSObject<OS_dispatch_queue> *_movieWritingQueue;
    AVAssetWriter *_movieWriter;
    AVAssetWriterInput *_movieAudioInput;
    AVAssetWriterInput *_movieVideoInput;
    long long _referenceOrientation;
    long long _currentOrientation;
    AVCaptureDevice *_currentDevice;
    NSURL *_movieURL;
}

@property(copy, nonatomic) NSURL *movieURL; // @synthesize movieURL=_movieURL;
@property(retain, nonatomic) AVCaptureDevice *currentDevice; // @synthesize currentDevice=_currentDevice;
@property(nonatomic) long long currentOrientation; // @synthesize currentOrientation=_currentOrientation;
@property(nonatomic) long long referenceOrientation; // @synthesize referenceOrientation=_referenceOrientation;
- (void).cxx_destruct;
- (void)removeFile:(id)arg1;
- (double)angleOffsetFromPortraitOrientationToOrientation:(long long)arg1;
- (struct CGAffineTransform)transformFromCurrentVideoOrientationToOrientation:(long long)arg1;
- (id)setupAssetWriterVideoInput:(struct opaqueCMFormatDescription *)arg1;
- (id)setupAssetWriterAudioInput:(struct opaqueCMFormatDescription *)arg1;
- (BOOL)inputsReadyToRecord;
- (void)writeSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 ofType:(id)arg2;
- (void)writeData:(id)arg1 video:(id)arg2 audio:(id)arg3 buffer:(struct opaqueCMSampleBuffer *)arg4;
- (void)stop:(CDUnknownBlockType)arg1;
- (void)startToPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

