//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol WAMsgNodeLaunchLogicDelegate;

@interface WAMsgNodeLaunchLogic : NSObject
{
    NSMutableDictionary *_dictLaunchTask;
    id <WAMsgNodeLaunchLogicDelegate> _delegate;
}

@property(nonatomic) __weak id <WAMsgNodeLaunchLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)getReleaseDownloadUrlWithAppId:(id)arg1 expectedVersion:(unsigned long long)arg2 checksum:(id)arg3 scene:(unsigned int)arg4 preloadUrlResp:(id)arg5 userInfo:(id)arg6;
- (void)getDemoDownloadUrlWithAppId:(id)arg1 localChecksum:(id)arg2 scene:(unsigned int)arg3;
- (void)getDebugDownloadUrlWithAppId:(id)arg1 localChecksum:(id)arg2 scene:(unsigned int)arg3;
- (BOOL)launchAppId:(id)arg1 requestType:(unsigned int)arg2 debugMode:(unsigned int)arg3 version:(unsigned long long)arg4 scene:(unsigned int)arg5 launchResponse:(id)arg6 userInfo:(id)arg7;

@end

