//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class MMButton, NSAttributedString, NSMutableArray, NSTextField, WANavigationItem;

@interface WANavigationBar : NSView
{
    WANavigationItem *_navigationItem;
    NSAttributedString *_attributedTitle;
    MMButton *_leftBarButtonItem;
    MMButton *_rightBarButtonItem;
    NSMutableArray *_navigationItems;
    NSTextField *_titleTextField;
    NSView *_leftItemContainer;
    NSView *_rightItemContainer;
}

+ (id)defaultBackButton;
@property(retain, nonatomic) NSView *rightItemContainer; // @synthesize rightItemContainer=_rightItemContainer;
@property(retain, nonatomic) NSView *leftItemContainer; // @synthesize leftItemContainer=_leftItemContainer;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(retain, nonatomic) NSMutableArray *navigationItems; // @synthesize navigationItems=_navigationItems;
@property(retain, nonatomic) MMButton *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(retain, nonatomic) MMButton *leftBarButtonItem; // @synthesize leftBarButtonItem=_leftBarButtonItem;
@property(copy, nonatomic) NSAttributedString *attributedTitle; // @synthesize attributedTitle=_attributedTitle;
@property(retain, nonatomic) WANavigationItem *navigationItem; // @synthesize navigationItem=_navigationItem;
- (void).cxx_destruct;
- (id)defaultAttributes;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeCurrentItemObserver;
- (void)addCurrentItemObserver;
- (void)layoutViews;
- (void)cleanItems;
- (id)popNavigationItem:(BOOL)arg1;
- (void)pushNavigationItem:(id)arg1 animated:(BOOL)arg2;
- (void)updateUI;
- (void)drawRect:(struct CGRect)arg1;
- (void)initViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

