//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCNNavigationController.h"

@class WANavigationBar, WANavigationItem;

@interface WANavigationController : CCNNavigationController
{
    WANavigationBar *_navigationBar;
    WANavigationItem *_navigationItem;
}

@property(retain, nonatomic) WANavigationItem *navigationItem; // @synthesize navigationItem=_navigationItem;
@property(retain, nonatomic) WANavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (void).cxx_destruct;
- (void)onClickBackButton:(id)arg1;
- (void)bringNavigationBarToFront;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)setNavigationBarHidden:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithRootViewController:(id)arg1;

@end

