//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSTextField;

@interface WANormalPickerViewTableViewCell : NSTableCellView
{
    NSTextField *_contentTextField;
}

@property(retain, nonatomic) NSTextField *contentTextField; // @synthesize contentTextField=_contentTextField;
- (void).cxx_destruct;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

