//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class MMAppMouseEventView, NSView;
@protocol WAPageSheetDelegate;

@interface WAPageSheet : MMObject
{
    BOOL _isShown;
    BOOL _isShowing;
    BOOL _isDismissing;
    id <WAPageSheetDelegate> _delegate;
    MMAppMouseEventView *_contentView;
    NSView *_parentView;
    NSView *_containerView;
    MMAppMouseEventView *_interateView;
    WAPageSheet *_retainSheet;
}

@property(nonatomic) BOOL isDismissing; // @synthesize isDismissing=_isDismissing;
@property(nonatomic) BOOL isShowing; // @synthesize isShowing=_isShowing;
@property(retain, nonatomic) WAPageSheet *retainSheet; // @synthesize retainSheet=_retainSheet;
@property(retain, nonatomic) MMAppMouseEventView *interateView; // @synthesize interateView=_interateView;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak NSView *parentView; // @synthesize parentView=_parentView;
@property(nonatomic) BOOL isShown; // @synthesize isShown=_isShown;
@property(retain, nonatomic) MMAppMouseEventView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <WAPageSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)contentHeight;
- (void)layoutSubViews;
- (void)loadSubViews;
- (void)initContentView;
- (void)initInterateView;
- (void)initContainerView;
- (void)loadViews;
- (void)resetPosition;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissWithAnimation;
- (void)resetShownPosition;
- (void)showInView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

