//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMCGIDelegate-Protocol.h"
#import "WAAppScopeConfirmWindowDelegate-Protocol.h"

@class NSString, WAAppScopeConfirmWindow, WxaExternalInfo;
@protocol WAPermissionUserAuthTaskDelegate;

@interface WAPermissionUserAuthTask : NSObject <MMCGIDelegate, WAAppScopeConfirmWindowDelegate>
{
    unsigned int _debugModeType;
    WxaExternalInfo *_externalInfo;
    NSString *_appID;
    NSString *_jsapi;
    CDUnknownBlockType _handler;
    CDUnknownBlockType _failHandler;
    unsigned long long _scene;
    NSString *_scope;
    WAAppScopeConfirmWindow *_confirmWindow;
    unsigned int _eventId;
    BOOL _isAllow;
    id <WAPermissionUserAuthTaskDelegate> _delegate;
}

@property(nonatomic) __weak id <WAPermissionUserAuthTaskDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onScopeWindowCancel:(id)arg1 withScope:(id)arg2;
- (void)onScopeWindowConfirm:(id)arg1 withScope:(id)arg2;
- (void)onConfirmViewCancel:(id)arg1;
- (void)onConfirmViewOKWithScope:(id)arg1;
- (void)closeConfirmWindow;
- (void)showConfirmViewWithResponse:(id)arg1;
- (void)continueShowConfirmView:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onConfirmResponse:(id)arg1;
- (void)onResponseAuth:(id)arg1;
- (void)requestConfirm;
- (void)requestAuth;
- (id)getCurrentViewController;
- (void)authFailAndCompleteTaskWithMessage:(id)arg1;
- (void)taskComplete;
- (void)authFailWithMessage:(id)arg1;
- (void)authOK;
- (void)saveAuthInfoWithStatus:(unsigned long long)arg1;
- (void)saveAuthInfo:(id)arg1;
- (id)getAuthInfo;
- (void)runUserAuth;
- (void)setUserAuthDataWithAPPID:(id)arg1 jsapi:(id)arg2 handler:(CDUnknownBlockType)arg3 failHandler:(CDUnknownBlockType)arg4 scene:(unsigned long long)arg5;
- (id)getJsapi;
- (id)getAppID;
- (void)dealloc;
- (id)initWithDebugModeType:(unsigned int)arg1 externalInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

