//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MMButton, MMIgnoreEventView, NSButton, NSString, NSTextField, NSView;
@protocol WAPhoneVerifyViewControllerDelegate;

@interface WAPhoneVerifyViewController : NSViewController
{
    int _secCount;
    id <WAPhoneVerifyViewControllerDelegate> _verifyWindowDelegate;
    long long _inputCount;
    NSString *_phoneNum;
    NSTextField *_titleTextField;
    NSTextField *_descTextLabel;
    NSButton *_closeButton;
    NSTextField *_bottomTextField;
    NSButton *_resendButton;
    NSView *_contentView;
    MMIgnoreEventView *_maskView;
    NSTextField *_input;
    MMButton *_confirmButton;
    NSTextField *_countDownTextField;
}

+ (id)setupWindow:(id)arg1 phone:(id)arg2 inputCount:(long long)arg3;
@property(nonatomic) int secCount; // @synthesize secCount=_secCount;
@property(nonatomic) __weak NSTextField *countDownTextField; // @synthesize countDownTextField=_countDownTextField;
@property(nonatomic) __weak MMButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(nonatomic) __weak NSTextField *input; // @synthesize input=_input;
@property(nonatomic) __weak MMIgnoreEventView *maskView; // @synthesize maskView=_maskView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak NSButton *resendButton; // @synthesize resendButton=_resendButton;
@property(nonatomic) __weak NSTextField *bottomTextField; // @synthesize bottomTextField=_bottomTextField;
@property(nonatomic) __weak NSButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak NSTextField *descTextLabel; // @synthesize descTextLabel=_descTextLabel;
@property(nonatomic) __weak NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(copy, nonatomic) NSString *phoneNum; // @synthesize phoneNum=_phoneNum;
@property(nonatomic) long long inputCount; // @synthesize inputCount=_inputCount;
@property(nonatomic) __weak id <WAPhoneVerifyViewControllerDelegate> verifyWindowDelegate; // @synthesize verifyWindowDelegate=_verifyWindowDelegate;
- (void).cxx_destruct;
- (void)updateCountDown:(long long)arg1;
- (void)showCountDown:(BOOL)arg1;
- (void)onClickResendButton:(id)arg1;
- (void)onClickCloseButton:(id)arg1;
- (void)onClickConfirmButton:(id)arg1;
- (void)countDown;
- (void)closeWindow;
- (void)viewDidLoad;
- (id)initWithFrame:(struct CGRect)arg1;

@end

