//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSButton;
@protocol WAPickerViewControllerDelegate;

@interface WAPickerViewController : NSViewController
{
    id <WAPickerViewControllerDelegate> _delegate;
    id _selectObject;
    NSButton *_confirmButton;
    NSButton *_cancelButton;
}

@property(retain, nonatomic) NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) NSButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) id selectObject; // @synthesize selectObject=_selectObject;
@property(nonatomic) __weak id <WAPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onCancel:(id)arg1;
- (void)onConfirm:(id)arg1;
- (struct CGSize)viewSize;
- (void)dealloc;
- (void)initView;
- (void)viewDidLoad;
- (void)loadView;

@end

