//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMViewController.h"

#import "JWCTableViewDataSource-Protocol.h"
#import "JWCTableViewDelegate-Protocol.h"
#import "WAProfileHeaderViewDelegate-Protocol.h"

@class CContact, JWCTableView, NSArray, NSMenu, NSString, NSView, NSVisualEffectView, RBLPopover, RBLPopoverBackgroundView, RFOverlayScrollView, WAProfileCardViewController, WAProfileHeaderView, WAProfileLogicController;
@protocol WAProfileContentViewDelegate;

@interface WAProfileContentViewController : MMViewController <JWCTableViewDelegate, JWCTableViewDataSource, WAProfileHeaderViewDelegate>
{
    id <WAProfileContentViewDelegate> _delegate;
    long long _mode;
    RBLPopover *_rblPopover;
    RBLPopoverBackgroundView *_rblBackgroundView;
    NSVisualEffectView *_visualEffectView;
    JWCTableView *_tableView;
    RFOverlayScrollView *_scrollView;
    NSArray *_section0;
    NSArray *_section1;
    WAProfileLogicController *_logicController;
    NSString *_userName;
    CContact *_contactData;
    WAProfileHeaderView *_headerView;
    NSMenu *_contentMenu;
    NSView *_parentView;
    WAProfileCardViewController *_cardController;
}

+ (double)getWAProfileContentSize:(id)arg1;
@property(retain, nonatomic) WAProfileCardViewController *cardController; // @synthesize cardController=_cardController;
@property(retain, nonatomic) NSView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) NSMenu *contentMenu; // @synthesize contentMenu=_contentMenu;
@property(retain, nonatomic) WAProfileHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) CContact *contactData; // @synthesize contactData=_contactData;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) WAProfileLogicController *logicController; // @synthesize logicController=_logicController;
@property(retain, nonatomic) NSArray *section1; // @synthesize section1=_section1;
@property(retain, nonatomic) NSArray *section0; // @synthesize section0=_section0;
@property(nonatomic) __weak RFOverlayScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak JWCTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
@property(retain, nonatomic) RBLPopoverBackgroundView *rblBackgroundView; // @synthesize rblBackgroundView=_rblBackgroundView;
@property(retain, nonatomic) RBLPopover *rblPopover; // @synthesize rblPopover=_rblPopover;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(nonatomic) __weak id <WAProfileContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onHeaderViewClick;
- (BOOL)tableView:(id)arg1 shouldSelectSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 withMouseEvent:(id)arg3;
- (id)tableView:(id)arg1 viewForIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (BOOL)isShown;
- (void)hide;
- (void)showInView:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)setupEffectView;
- (void)setupTableView;
- (void)setupPopoverView;
- (void)setupSettingSection:(id)arg1;
- (void)setupDefaultSection:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

