//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMCGIDelegate-Protocol.h"
#import "MMService-Protocol.h"

@class GetProfileInfoResponse_WxaEvaluateWordingList, NSMutableDictionary, NSString;

@interface WAProfileService : MMService <MMCGIDelegate, MMService>
{
    NSMutableDictionary *_dicUserName2LastForegroundTime;
    GetProfileInfoResponse_WxaEvaluateWordingList *_evaluateWordingList;
}

@property(retain, nonatomic) GetProfileInfoResponse_WxaEvaluateWordingList *evaluateWordingList; // @synthesize evaluateWordingList=_evaluateWordingList;
@property(retain, nonatomic) NSMutableDictionary *dicUserName2LastForegroundTime; // @synthesize dicUserName2LastForegroundTime=_dicUserName2LastForegroundTime;
- (void).cxx_destruct;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onUpdateProfileEvaluate:(id)arg1;
- (BOOL)updateProfileEvaluateForUserName:(id)arg1 OperType:(int)arg2 RatingValue:(double)arg3;
- (BOOL)updateProfileLikeStatusForUserName:(id)arg1 myselfLike:(BOOL)arg2;
- (BOOL)skipProfileEvaluateForUserName:(id)arg1;
- (BOOL)updateProfileEvaluateForUserName:(id)arg1 RatingValue:(double)arg2;
- (void)saveWording:(id)arg1;
- (void)onFetchProfileBaseInfo:(id)arg1;
- (BOOL)fetchProfileInfoForUserName:(id)arg1;
- (BOOL)canPopEvaluateDueToMinStayTime:(unsigned int)arg1 UserName:(id)arg2;
- (void)updateForegroundTimeForUserName:(id)arg1;
- (BOOL)saveDataToCacheFile:(id)arg1 Path:(id)arg2;
- (BOOL)loadDataFromFile:(id)arg1 ToClass:(Class)arg2 ToData:(id *)arg3;
- (void)saveWordingToCache;
- (void)loadCacheWording;
- (id)getDefaultEvaluateWordingForScore:(int)arg1;
- (id)getEvaluteWordingForScore:(int)arg1;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

