//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class CAShapeLayer, MMView, NSImageView, NSTextField, NSTrackingArea;

@interface WAProfileTableCellView : NSTableCellView
{
    BOOL _bDisalbed;
    NSTextField *_titleLabel;
    NSImageView *_iconImageView;
    MMView *_box;
    NSTrackingArea *_trackingArea;
    CAShapeLayer *_backgroudLayer;
}

@property(retain, nonatomic) CAShapeLayer *backgroudLayer; // @synthesize backgroudLayer=_backgroudLayer;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) MMView *box; // @synthesize box=_box;
@property(retain, nonatomic) NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) BOOL bDisalbed; // @synthesize bDisalbed=_bDisalbed;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setupTrackingArea;
- (void)updateSection1UI:(id)arg1 withBox:(BOOL)arg2 withOffsetY:(double)arg3;
- (void)updateSection0UI:(id)arg1 withBox:(BOOL)arg2 withIndex:(long long)arg3 withOffsetY:(double)arg4;
- (void)initViews;
- (void)prepareForReuse;
- (BOOL)wantsDefaultClipping;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

