//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMAppMouseEventView.h"

@class NSImageView, NSTextField;

@interface WAProfileInfoCellView : MMAppMouseEventView
{
    BOOL _useSelectStyle;
    long long _tag;
    NSTextField *_titleLabel;
    NSTextField *_detailLabel;
    NSImageView *_disclosureIndicator;
    unsigned long long _style;
}

@property(nonatomic) BOOL useSelectStyle; // @synthesize useSelectStyle=_useSelectStyle;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) NSImageView *disclosureIndicator; // @synthesize disclosureIndicator=_disclosureIndicator;
@property(retain, nonatomic) NSTextField *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property long long tag; // @synthesize tag=_tag;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

