//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMView.h"

@class CAShapeLayer, CContact, MMCTTextView, MMDivider, MMTextField, NSImageView, NSTrackingArea, WAProfileHeaderServiceView;
@protocol WAProfileHeaderViewDelegate;

@interface WAProfileHeaderView : MMView
{
    CContact *_contactData;
    id <WAProfileHeaderViewDelegate> _delegate;
    NSImageView *_iconImageView;
    MMCTTextView *_titleText;
    MMTextField *_modeText;
    MMTextField *_scoreText;
    WAProfileHeaderServiceView *_serviceView;
    MMDivider *_lineView;
    NSTrackingArea *_trackingArea;
    CAShapeLayer *_backgroudLayer;
}

@property(retain, nonatomic) CAShapeLayer *backgroudLayer; // @synthesize backgroudLayer=_backgroudLayer;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) MMDivider *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) WAProfileHeaderServiceView *serviceView; // @synthesize serviceView=_serviceView;
@property(retain, nonatomic) MMTextField *scoreText; // @synthesize scoreText=_scoreText;
@property(retain, nonatomic) MMTextField *modeText; // @synthesize modeText=_modeText;
@property(retain, nonatomic) MMCTTextView *titleText; // @synthesize titleText=_titleText;
@property(retain, nonatomic) NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak id <WAProfileHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CContact *contactData; // @synthesize contactData=_contactData;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setupTrackingArea;
- (void)dismissServiceView;
- (void)showServiceView:(long long)arg1;
- (void)setupUI;
- (void)initUI;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

