//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol WARemoteDebugSendQueueDelegate;

@interface WARemoteDebugLocalSendQueue : NSObject
{
    id <WARemoteDebugSendQueueDelegate> _delegate;
    NSMutableArray *_sendQueue;
}

@property(retain, nonatomic) NSMutableArray *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(nonatomic) __weak id <WARemoteDebugSendQueueDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleQueue;
- (void)sendDebugMsg:(id)arg1;
- (id)init;

@end

