//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportPatchUpdateItem : WAReportBaseItem
{
    BOOL _canUsePatchUpdate;
    BOOL _isUpdateComplete;
    BOOL _isUpdateCompleteWithPatch;
    unsigned int _fullPkgSize;
    unsigned int _patchSize;
    unsigned int _patchError;
    long long _oldVersion;
    long long _targetVersion;
    long long _beginTime;
    long long _endTime;
    NSString *_moduleName;
}

@property(retain, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(nonatomic) unsigned int patchError; // @synthesize patchError=_patchError;
@property(nonatomic) unsigned int patchSize; // @synthesize patchSize=_patchSize;
@property(nonatomic) unsigned int fullPkgSize; // @synthesize fullPkgSize=_fullPkgSize;
@property(nonatomic) BOOL isUpdateCompleteWithPatch; // @synthesize isUpdateCompleteWithPatch=_isUpdateCompleteWithPatch;
@property(nonatomic) BOOL isUpdateComplete; // @synthesize isUpdateComplete=_isUpdateComplete;
@property(nonatomic) BOOL canUsePatchUpdate; // @synthesize canUsePatchUpdate=_canUsePatchUpdate;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) long long targetVersion; // @synthesize targetVersion=_targetVersion;
@property(nonatomic) long long oldVersion; // @synthesize oldVersion=_oldVersion;
- (void).cxx_destruct;
- (id)reportString;
- (int)reportID;

@end

