//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@class NSString;

@interface WAScrollView : NSScrollView
{
    NSString *_viewID;
    CDUnknownBlockType _pullDownRefreshBlock;
}

@property(copy, nonatomic) CDUnknownBlockType pullDownRefreshBlock; // @synthesize pullDownRefreshBlock=_pullDownRefreshBlock;
@property(copy, nonatomic) NSString *viewID; // @synthesize viewID=_viewID;
- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

