//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextView.h>

#import "NSTextViewDelegate-Protocol.h"
#import "WATextInputInterface-Protocol.h"

@class NSColor, NSFont, NSMutableParagraphStyle, NSScrollView, NSString, NSView;
@protocol WATextInputDelegate;

@interface WATextView : NSTextView <WATextInputInterface, NSTextViewDelegate>
{
    long long _lineCount;
    NSView *_greyMask;
    NSColor *_placeColor;
    NSFont *_placeFont;
    BOOL _autoSize;
    struct CGRect _rcCaret;
    unsigned short _keyCode;
    BOOL _disableEditing;
    BOOL showConfirmButton;
    BOOL multiLine;
    BOOL initKeyBoard;
    BOOL fixed;
    BOOL confirmHold;
    BOOL native;
    BOOL adjustPosition;
    BOOL _disableContainerInset;
    unsigned int inputId;
    id <WATextInputDelegate> keyboardDelegate;
    NSString *userData;
    long long maxLength;
    NSString *defaultValue;
    double bottomMargin;
    long long initCursor;
    long long endCursor;
    long long selectionBegin;
    long long selectionEnd;
    NSScrollView *_scrollView;
    double _minHeight;
    double _maxHeight;
    NSString *_placeHolder;
    NSMutableParagraphStyle *_paragraphStyle;
}

@property(retain, nonatomic) NSMutableParagraphStyle *paragraphStyle; // @synthesize paragraphStyle=_paragraphStyle;
@property(copy, nonatomic) NSString *placeHolder; // @synthesize placeHolder=_placeHolder;
@property(nonatomic) BOOL disableContainerInset; // @synthesize disableContainerInset=_disableContainerInset;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) double minHeight; // @synthesize minHeight=_minHeight;
@property(nonatomic) __weak NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) BOOL adjustPosition; // @synthesize adjustPosition;
@property(nonatomic) BOOL native; // @synthesize native;
@property(nonatomic) long long selectionEnd; // @synthesize selectionEnd;
@property(nonatomic) long long selectionBegin; // @synthesize selectionBegin;
@property(nonatomic) long long endCursor; // @synthesize endCursor;
@property(nonatomic) long long initCursor; // @synthesize initCursor;
@property(nonatomic) BOOL confirmHold; // @synthesize confirmHold;
@property(nonatomic) BOOL fixed; // @synthesize fixed;
@property(nonatomic) BOOL initKeyBoard; // @synthesize initKeyBoard;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin;
@property(nonatomic) BOOL multiLine; // @synthesize multiLine;
@property(copy, nonatomic) NSString *defaultValue; // @synthesize defaultValue;
@property(nonatomic) long long maxLength; // @synthesize maxLength;
@property(copy, nonatomic) NSString *userData; // @synthesize userData;
@property(nonatomic) unsigned int inputId; // @synthesize inputId;
@property(nonatomic) __weak id <WATextInputDelegate> keyboardDelegate; // @synthesize keyboardDelegate;
@property(nonatomic) BOOL showConfirmButton; // @synthesize showConfirmButton;
- (void).cxx_destruct;
- (id)getInputView;
- (void)onKeyboardDidHide;
- (void)onKeyboardWillHide;
- (id)getParentView;
- (BOOL)isAutoSize;
- (void)setAutoSize:(BOOL)arg1;
- (double)oneLineHeight;
- (double)getContentHeight;
- (long long)getLineCount;
- (void)setBackgroundColor:(id)arg1;
- (void)setVisible:(BOOL)arg1;
- (BOOL)isBold;
- (double)getFontSize;
- (void)setInputFrame:(struct CGRect)arg1;
- (void)setTextColor:(id)arg1;
- (void)setFont:(double)arg1 bold:(BOOL)arg2;
- (id)getAccessoryButton;
- (struct CGRect)getVisibleRect;
- (void)removeFromParent;
- (void)becomeFirstResponder:(BOOL)arg1;
- (void)setInputValue:(id)arg1 cursorPos:(long long)arg2;
- (void)setDisable:(BOOL)arg1;
- (void)controlTextDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)setAlignment:(unsigned long long)arg1;
- (void)setLineSpace:(double)arg1;
- (void)adjustSizeFit:(id)arg1;
- (void)calculateCaretPos;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)setInputPlaceholder:(id)arg1 placeholderStyle:(id)arg2;
- (id)getInputValue;
- (void)setSelectedTextRange:(struct _NSRange)arg1;
- (struct _NSRange)getSelectedTextRange;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)setFont:(id)arg1;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)textDidChange:(id)arg1;
- (BOOL)textViewShouldEndEditing:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long keyboardType;
@property(readonly) Class superclass;

@end

