//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

#import "NSControlTextEditingDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"
#import "WATextInputInterface-Protocol.h"

@class MMVerticallyCenteredSecureTextFieldCell, NSColor, NSFont, NSString, VerticallyCenteredTextFieldCell;
@protocol WATextInputDelegate;

@interface WATextField : NSTextField <WATextInputInterface, NSTextFieldDelegate, NSControlTextEditingDelegate>
{
    NSColor *_placeColor;
    NSFont *_placeFont;
    BOOL _disableEditing;
    unsigned short _keyCode;
    BOOL showConfirmButton;
    BOOL multiLine;
    BOOL initKeyBoard;
    BOOL fixed;
    BOOL confirmHold;
    BOOL native;
    BOOL adjustPosition;
    BOOL _screenWidth;
    BOOL _blockFocus;
    BOOL _bAboveDrop;
    unsigned int inputId;
    id <WATextInputDelegate> keyboardDelegate;
    NSString *userData;
    long long maxLength;
    NSString *defaultValue;
    double bottomMargin;
    long long initCursor;
    long long endCursor;
    long long selectionBegin;
    long long selectionEnd;
    long long keyboardType;
    double _marginLeft;
    double _marginRight;
    VerticallyCenteredTextFieldCell *_normalCell;
    MMVerticallyCenteredSecureTextFieldCell *_secureCell;
}

@property(retain, nonatomic) MMVerticallyCenteredSecureTextFieldCell *secureCell; // @synthesize secureCell=_secureCell;
@property(retain, nonatomic) VerticallyCenteredTextFieldCell *normalCell; // @synthesize normalCell=_normalCell;
@property(nonatomic) BOOL bAboveDrop; // @synthesize bAboveDrop=_bAboveDrop;
@property(nonatomic) BOOL blockFocus; // @synthesize blockFocus=_blockFocus;
@property(nonatomic) double marginRight; // @synthesize marginRight=_marginRight;
@property(nonatomic) double marginLeft; // @synthesize marginLeft=_marginLeft;
@property(nonatomic) BOOL screenWidth; // @synthesize screenWidth=_screenWidth;
@property(nonatomic) long long keyboardType; // @synthesize keyboardType;
@property(nonatomic) BOOL adjustPosition; // @synthesize adjustPosition;
@property(nonatomic) BOOL native; // @synthesize native;
@property(nonatomic) long long selectionEnd; // @synthesize selectionEnd;
@property(nonatomic) long long selectionBegin; // @synthesize selectionBegin;
@property(nonatomic) long long endCursor; // @synthesize endCursor;
@property(nonatomic) long long initCursor; // @synthesize initCursor;
@property(nonatomic) BOOL confirmHold; // @synthesize confirmHold;
@property(nonatomic) BOOL fixed; // @synthesize fixed;
@property(nonatomic) BOOL initKeyBoard; // @synthesize initKeyBoard;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin;
@property(nonatomic) BOOL multiLine; // @synthesize multiLine;
@property(copy, nonatomic) NSString *defaultValue; // @synthesize defaultValue;
@property(nonatomic) long long maxLength; // @synthesize maxLength;
@property(copy, nonatomic) NSString *userData; // @synthesize userData;
@property(nonatomic) unsigned int inputId; // @synthesize inputId;
@property(nonatomic) __weak id <WATextInputDelegate> keyboardDelegate; // @synthesize keyboardDelegate;
@property(nonatomic) BOOL showConfirmButton; // @synthesize showConfirmButton;
- (void).cxx_destruct;
- (BOOL)textShouldEndEditing:(id)arg1;
- (void)updateDropHeight:(BOOL)arg1;
- (void)textDidBeginEditing:(id)arg1;
- (BOOL)textShouldBeginEditing:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)onDeleteDrop:(id)arg1;
- (void)onSelectDrop:(id)arg1 value:(id)arg2;
- (void)setDropList:(id)arg1 above:(BOOL)arg2;
- (void)onKeyboardDidHide;
- (void)onKeyboardWillHide;
- (id)getParentView;
- (BOOL)isAutoSize;
- (void)setAutoSize:(BOOL)arg1;
- (double)getContentHeight;
- (long long)getLineCount;
- (void)setBackgroundColor:(id)arg1;
- (void)setVisible:(BOOL)arg1;
- (BOOL)isBold;
- (void)setDisable:(BOOL)arg1;
- (double)getFontSize;
- (void)setInputFrame:(struct CGRect)arg1;
- (void)setTextColor:(id)arg1;
- (void)setFont:(double)arg1 bold:(BOOL)arg2;
- (id)getAccessoryButton;
- (struct CGRect)getVisibleRect;
- (void)removeFromSuperview;
- (void)removeFromParent;
- (void)becomeFirstResponder:(BOOL)arg1;
- (void)setInputAccessoryView:(id)arg1;
- (void)setInputView:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textDidChange:(id)arg1;
- (id)subStringWith:(id)arg1 ToIndex:(long long)arg2;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)setInputPlaceholder:(id)arg1 placeholderStyle:(id)arg2;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (void)setInputValue:(id)arg1 cursorPos:(long long)arg2;
- (id)getInputValue;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (void)layoutSubviews;
- (void)setPasswordMode:(BOOL)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (void)updateStringValue:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

