//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSButton, NSColor, NSDictionary, NSString, NSView;
@protocol WATextInputDelegate;

@protocol WATextInputInterface <NSObject>
@property(nonatomic) long long keyboardType;
@property(nonatomic) BOOL native;
@property(nonatomic) long long selectionEnd;
@property(nonatomic) long long selectionBegin;
@property(nonatomic) long long endCursor;
@property(nonatomic) long long initCursor;
@property(nonatomic) BOOL adjustPosition;
@property(nonatomic) BOOL confirmHold;
@property(nonatomic) BOOL fixed;
@property(nonatomic) BOOL initKeyBoard;
@property(nonatomic) double bottomMargin;
@property(copy, nonatomic) NSString *userData;
@property(nonatomic) unsigned int inputId;
@property(nonatomic) long long maxLength;
@property(copy, nonatomic) NSString *defaultValue;
@property(nonatomic) BOOL multiLine;
@property(nonatomic) BOOL showConfirmButton;
@property(nonatomic) __weak id <WATextInputDelegate> keyboardDelegate;
- (NSView *)getParentView;
- (struct CGRect)getVisibleRect;
- (void)removeFromParent;
- (void)setBackgroundColor:(NSColor *)arg1;
- (void)setVisible:(BOOL)arg1;
- (BOOL)isBold;
- (double)getFontSize;
- (void)setInputFrame:(struct CGRect)arg1;
- (void)setTextColor:(NSColor *)arg1;
- (void)setFont:(double)arg1 bold:(BOOL)arg2;
- (NSButton *)getAccessoryButton;
- (void)becomeFirstResponder:(BOOL)arg1;
- (void)setInputView:(NSView *)arg1;
- (void)setInputAccessoryView:(NSView *)arg1;
- (NSString *)getInputValue;
- (void)setSelectedTextRange:(struct _NSRange)arg1;
- (struct _NSRange)getSelectedTextRange;
- (void)setInputPlaceholder:(NSString *)arg1 placeholderStyle:(NSDictionary *)arg2;
- (void)setInputValue:(NSString *)arg1 cursorPos:(long long)arg2;

@optional
- (void)onKeyboardDidHide;
- (void)onKeyboardWillHide;
- (BOOL)isAutoSize;
- (void)setAutoSize:(BOOL)arg1;
- (double)getContentHeight;
- (long long)getLineCount;
- (void)setDisable:(BOOL)arg1;
- (void)setPasswordMode:(BOOL)arg1;
@end

