//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

@class WAWebViewPullDownRefreshView;

@interface WAWebViewPlugin_PullRefresh : WAWebViewPluginBase
{
    BOOL _isReflashingHead;
    BOOL _isRecoverInsetProcessing;
    BOOL _bIsEnablePullRefresh;
    WAWebViewPullDownRefreshView *_pullDownRefreshView;
    double _offset;
    unsigned long long _triggerTime;
}

@property(nonatomic) unsigned long long triggerTime; // @synthesize triggerTime=_triggerTime;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(retain, nonatomic) WAWebViewPullDownRefreshView *pullDownRefreshView; // @synthesize pullDownRefreshView=_pullDownRefreshView;
@property(readonly, nonatomic) BOOL bIsEnablePullRefresh; // @synthesize bIsEnablePullRefresh=_bIsEnablePullRefresh;
@property(readonly, nonatomic) BOOL isRecoverInsetProcessing; // @synthesize isRecoverInsetProcessing=_isRecoverInsetProcessing;
- (void).cxx_destruct;
- (void)startRefreshHeaderView:(BOOL)arg1;
- (void)stopRefreshHeaderView:(BOOL)arg1;
- (void)stopRefreshHead;
- (void)startRefreshHead;
- (void)setDisableWebViewScrollViewPullUp;
- (void)setDisableWebViewScrollViewPullDown;
- (void)changePullRefreshMode:(int)arg1;
- (void)stopPullRefresh;
- (void)startPullRefresh;
- (void)disablePullRefresh;
- (void)enablePullRefresh:(double)arg1 mode:(int)arg2;
@property(readonly, nonatomic) BOOL isReflashingHead; // @synthesize isReflashingHead=_isReflashingHead;
- (BOOL)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;

@end

