//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSButton, NSMutableArray, NSScrollView, NSView;
@protocol WAWebActionSheetDelegate;

@interface WAWebActionSheet : NSObject
{
    NSButton *_backgroundView;
    NSScrollView *_containerView;
    NSMutableArray *_buttonArray;
    NSButton *_cancelButton;
    id <WAWebActionSheetDelegate> _delegate;
    double _maxHeight;
    NSView *_view;
}

+ (id)defaultButtonAttributes;
@property(nonatomic) __weak NSView *view; // @synthesize view=_view;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) __weak id <WAWebActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)hideActionSheet;
- (void)setItemColor:(id)arg1 atIndex:(long long)arg2;
- (void)onClickBtn:(id)arg1;
- (void)tapOut:(id)arg1;
- (void)setItemColor:(id)arg1 cancelColor:(id)arg2;
- (void)setItems:(id)arg1 cancelText:(id)arg2;
- (id)initWithWebView:(id)arg1;

@end

