//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

@class NSColor, NSString, WAWebViewController;

@interface WAWebViewPlugin_CustomNavigationBar : WAWebViewPluginBase
{
    BOOL _bIsJsapiDefineNavigationLeftItem;
    BOOL _bIsJsapiDefineNavigationRightItem;
    CDUnknownBlockType _onClickRightNavItem;
    BOOL _isTrigerLongPress;
    BOOL _isEnableClose;
    BOOL _webAppear;
    NSColor *_reservedBgColor;
    int _reservedStatusBar;
    int _reservedNavigationMode;
    NSString *_reservedNavigationTitle;
    BOOL _showShareMenu;
    BOOL _listenTapStatusBar;
    BOOL _shouldUseDynamicPageShare;
    long long _shareMenuType;
    WAWebViewController *_mainWebView;
}

@property(nonatomic) BOOL shouldUseDynamicPageShare; // @synthesize shouldUseDynamicPageShare=_shouldUseDynamicPageShare;
@property(nonatomic) BOOL listenTapStatusBar; // @synthesize listenTapStatusBar=_listenTapStatusBar;
@property(nonatomic) __weak WAWebViewController *mainWebView; // @synthesize mainWebView=_mainWebView;
@property(nonatomic) BOOL showShareMenu; // @synthesize showShareMenu=_showShareMenu;
@property(nonatomic) long long shareMenuType; // @synthesize shareMenuType=_shareMenuType;
@property(nonatomic) BOOL m_bIsJsapiDefineNavigationRightItem; // @synthesize m_bIsJsapiDefineNavigationRightItem=_bIsJsapiDefineNavigationRightItem;
- (void).cxx_destruct;
- (void)setNavBarTitle:(id)arg1;
- (void)setNavBarElementAndStatusBarStyle:(int)arg1;
- (void)setNavBarBackgroundColor:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)addWeAppStatusBarListener;
- (void)__changeStatusBarWhite:(BOOL)arg1;
- (void)changeStatusBarWhite:(BOOL)arg1;
- (void)onClickJSDefineRightNavItem;
- (void)onRouteToHome;
- (void)onClickCustomRightButton;
- (void)onMore;
- (BOOL)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)dealloc;

@end

