//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

#import "AVAudioRecorderDelegate-Protocol.h"
#import "IWebviewRecorderManagerExt-Protocol.h"

@class AVAudioRecorder, NSString;
@protocol IWAWebViewPluginDelegate;

@interface WAWebViewPlugin_Recorder : WAWebViewPluginBase <IWebviewRecorderManagerExt, AVAudioRecorderDelegate>
{
    BOOL _isCheckingPermission;
    id <IWAWebViewPluginDelegate> _resultDelegate;
    unsigned long long _duration;
    AVAudioRecorder *_currentRecorder;
    NSString *_currentFilePath;
}

@property(retain, nonatomic) NSString *currentFilePath; // @synthesize currentFilePath=_currentFilePath;
@property(retain, nonatomic) AVAudioRecorder *currentRecorder; // @synthesize currentRecorder=_currentRecorder;
@property(nonatomic) unsigned long long duration; // @synthesize duration=_duration;
@property(nonatomic) BOOL isCheckingPermission; // @synthesize isCheckingPermission=_isCheckingPermission;
@property(nonatomic) __weak id <IWAWebViewPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void).cxx_destruct;
- (void)onFinishedRecord:(id)arg1 ErrCode:(int)arg2 stopReason:(long long)arg3;
- (void)onRecordTimeTooShort;
- (void)onStartRecord:(long long)arg1;
- (void)updateWebviewTitle;
- (void)audioRecorderEncodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(BOOL)arg2;
- (void)startRecord;
- (BOOL)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)stopRecorder;
- (void)startRecorderForDuration:(unsigned long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

