//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPlugin_embedView.h"

#import "MMVideoPlayerViewDelegate-Protocol.h"

@class NSString;

@interface WAWebViewPlugin_VideoPlayer : WAWebViewPlugin_embedView <MMVideoPlayerViewDelegate>
{
    BOOL _didAppear;
    Class VideoClass;
    struct CGPoint _contentOffset;
    struct CGRect _webViewFrame;
    struct CGRect _mainViewFrame;
    BOOL _scrollEnabled;
    BOOL _statusBarBlack;
    long long _contentInsetAdjustmentBehavior;
    BOOL _interuptExternalMusic;
    long long _videoNum;
    unsigned int _delayFullScreenViewID;
    BOOL _statusBarHidden;
}

- (BOOL)isForground;
- (void)pauseVideoTemp:(BOOL)arg1;
- (id)getCurrentSnapshot;
- (void)enableWebViewScroll:(BOOL)arg1;
- (BOOL)operateVideoPlayer:(id)arg1 videoId:(unsigned int)arg2;
- (void)onVideoStateChange:(long long)arg1;
- (void)onVideoEvent:(id)arg1 param:(id)arg2;
- (void)onVolumeChange:(double)arg1;
- (id)getVideoPlayer:(unsigned int)arg1;
- (BOOL)removeChildView:(unsigned int)arg1;
- (id)insertVideo:(id)arg1 pos:(struct CGRect)arg2 videoId:(unsigned int)arg3 parentId:(unsigned int)arg4;
- (void)disableFullScreen;
- (void)pauseAllVideos:(BOOL)arg1;
- (BOOL)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)onWeAppEnterForeground;
- (void)appWillTerminate:(id)arg1;
- (void)appWillEnterBackground:(id)arg1;
- (void)onWeAppEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

