//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPlugin_embedView.h"

#import "RemoteTaskCenterExt-Protocol.h"

@class ForwardMessageLogicController, NSArray, NSData, NSDictionary, NSImageView, NSMutableArray, NSMutableDictionary, NSString;
@protocol IWAWebViewPluginDelegate;

@interface WAWebViewPlugin_WeAppMsg : WAWebViewPlugin_embedView <RemoteTaskCenterExt>
{
    struct CGPoint _ptOffset;
    BOOL _offsetChanged;
    NSMutableDictionary *_shareKeys;
    NSMutableArray *_reportArray;
    BOOL _waitingShare;
    NSImageView *_maskView;
    BOOL _downloadImage;
    NSArray *_arrSpecificSendToContacts;
    NSArray *_arrWaitingContactList;
    BOOL _firstShare;
    BOOL _shouldUseDynamicShare;
    BOOL _shouldUseUpdatableShare;
    BOOL _bNoCapture;
    BOOL _bInSharing;
    int _cardType;
    id <IWAWebViewPluginDelegate> _resultDelegate;
    NSData *_thumbData;
    NSString *_updatableShareTemplateId;
    NSString *_messageExtraData;
    NSMutableDictionary *_customData;
    ForwardMessageLogicController *_forwardLogic;
    NSMutableDictionary *_scrollOffset;
    ForwardMessageLogicController *_shareController;
    NSDictionary *_shareParam;
}

@property(retain, nonatomic) NSDictionary *shareParam; // @synthesize shareParam=_shareParam;
@property(nonatomic) __weak ForwardMessageLogicController *shareController; // @synthesize shareController=_shareController;
@property(retain, nonatomic) NSMutableDictionary *scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogic; // @synthesize forwardLogic=_forwardLogic;
@property(retain, nonatomic) NSMutableDictionary *customData; // @synthesize customData=_customData;
@property(retain, nonatomic) NSString *messageExtraData; // @synthesize messageExtraData=_messageExtraData;
@property(nonatomic) BOOL bInSharing; // @synthesize bInSharing=_bInSharing;
@property(nonatomic) BOOL bNoCapture; // @synthesize bNoCapture=_bNoCapture;
@property(retain, nonatomic) NSString *updatableShareTemplateId; // @synthesize updatableShareTemplateId=_updatableShareTemplateId;
@property(nonatomic) BOOL shouldUseUpdatableShare; // @synthesize shouldUseUpdatableShare=_shouldUseUpdatableShare;
@property(nonatomic) BOOL shouldUseDynamicShare; // @synthesize shouldUseDynamicShare=_shouldUseDynamicShare;
@property(nonatomic) int cardType; // @synthesize cardType=_cardType;
@property(nonatomic) BOOL firstShare; // @synthesize firstShare=_firstShare;
@property(retain, nonatomic) NSData *thumbData; // @synthesize thumbData=_thumbData;
@property(nonatomic) __weak id <IWAWebViewPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void).cxx_destruct;
- (void)openWeAppForwardMessage:(id)arg1 type:(int)arg2 toContacts:(id)arg3;
- (void)openWeAppForwardMessage:(id)arg1 type:(int)arg2;
- (void)takeSnapShot;
- (void)restoreScrollOffsets:(id)arg1;
- (void)resetScrollOffsets:(id)arg1;
- (void)saveScrollOffsets:(id)arg1;
- (void)saveRestoreWebViewScroll:(BOOL)arg1;
- (void)OnForwardWeAppMessageSend:(id)arg1 appMsgItem:(id)arg2;
- (id)getCurrentViewController;
- (unsigned int)getAppType;
- (void)OnForwardMessageException;
- (void)OnForwardMessageCancel;
- (void)OnForwardMessageSend;
- (id)pluginReportPageEvent;
- (void)onForwardMsgCallBack:(id)arg1 withErrCode:(int)arg2;
- (void)showSessionPicker:(id)arg1;
- (void)takeSnapShotWithCompletion:(CDUnknownBlockType)arg1;
- (void)downloadImageFrom:(id)arg1 forMessageData:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)shareToFriend:(int)arg1 appInfo:(id)arg2;
- (void)onCustomWeAppMessage:(id)arg1;
- (void)getWeAppMessage:(int)arg1 customData:(id)arg2;
- (void)dealloc;
- (id)init;

@end

