//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AccountServiceExt-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface WCDBMonitorMgr : NSObject <AccountServiceExt>
{
    NSObject<OS_dispatch_queue> *m_reportQueue;
    BOOL m_stopReport;
    unsigned int m_errorLastReportTime;
    unsigned int m_performanceLastReportTime;
}

- (void).cxx_destruct;
- (void)onUserLogout;
- (id)parseError:(id)arg1;
- (void)reportErrorToIDKey:(id)arg1;
- (void)reportErrorToKV:(id)arg1;
- (void)reportPerformanceToKV:(id)arg1;
- (void)setupWCDBMonitor;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

