//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCDBHelper : NSObject
{
}

+ (void)reportDBFileSize;
+ (void)reportAddMsg:(id)arg1 chatName:(id)arg2;
+ (id)GetRecoverFilePath:(unsigned int)arg1;
+ (id)GetFilePath:(unsigned int)arg1;
+ (id)CipherKey;
+ (int)PageSize;

@end

