//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSRecursiveLock, WCState;
@protocol WCStateMachineDelegate;

@interface WCStateMachine : NSObject
{
    NSRecursiveLock *_lock;
    BOOL _active;
    id <WCStateMachineDelegate> _delegate;
    WCState *_initialState;
    WCState *_currentState;
    NSMutableSet *_states;
    NSMutableSet *_events;
}

@property(readonly, nonatomic) BOOL active; // @synthesize active=_active;
@property(readonly, nonatomic) NSMutableSet *events; // @synthesize events=_events;
@property(readonly, nonatomic) NSMutableSet *states; // @synthesize states=_states;
@property(retain, nonatomic) WCState *currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) WCState *initialState; // @synthesize initialState=_initialState;
@property(nonatomic) __weak id <WCStateMachineDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)stateNamed:(id)arg1;
- (id)eventNamed:(id)arg1;
- (int)fireEvent:(id)arg1 userInfo:(id)arg2;
- (int)addEvent:(id)arg1;
- (int)addState:(id)arg1;
- (int)activate;
- (id)init;

@end

