//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

@interface WeAppCustomTabItemData : NSObject
{
    NSImage *_iconImg;
    NSImage *_selectedIconImg;
    NSString *_titleText;
    NSString *_linkUrl;
}

@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(retain, nonatomic) NSImage *selectedIconImg; // @synthesize selectedIconImg=_selectedIconImg;
@property(retain, nonatomic) NSImage *iconImg; // @synthesize iconImg=_iconImg;
- (void).cxx_destruct;

@end

