//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSApplication.h>

@class NSMenuItem, VoiceOver, WeChat;

@interface WeChatApplication : NSApplication
{
    WeChat *_wechat;
    NSMenuItem *_settingsMenuItem;
    VoiceOver *_status;
}

@property(retain, nonatomic) VoiceOver *status; // @synthesize status=_status;
@property(nonatomic) __weak NSMenuItem *settingsMenuItem; // @synthesize settingsMenuItem=_settingsMenuItem;
@property(retain) WeChat *wechat; // @synthesize wechat=_wechat;
- (void).cxx_destruct;
- (unsigned char)isUndoMangerException:(id)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)isVoiceOverRunning;
- (long long)requestUserAttention:(unsigned long long)arg1;
- (void)reportException:(id)arg1;

@end

