//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKWebView.h>

#import "MMWKWebViewInterface-Protocol.h"

@class NSSet, NSString;

@interface WKWebView (MM) <MMWKWebViewInterface>
+ (BOOL)hasLocalValidWePkg:(id)arg1;
+ (BOOL)enableWKProxy:(long long)arg1;
+ (id)webViewWithType:(long long)arg1 frame:(struct CGRect)arg2 recordInitUrl:(id)arg3 delegate:(id)arg4;
@property(retain, nonatomic) NSSet *noNeedCheckOfflineUrlSet;
@property(nonatomic) BOOL isOfflinePage;
@property(retain, nonatomic) NSString *recordInitUrl;
@property(nonatomic) BOOL bWkProxyEnabled;
- (void)tryDestroyWebView;
- (void)tryUpdateWePkgByLoadingUrl:(id)arg1 isMainFrame:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

