//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMJSApiVerifyMgrDelegate-Protocol.h"
#import "WXCustomWebViewControllerProtocol-Protocol.h"
#import "WebViewA8KeyLogicDelegate-Protocol.h"
#import "WebViewJSLogicDelegate-Protocol.h"
#import "YYWebViewDelegate-Protocol.h"

@class MMJSApiVerifyMgr, MMURLHandler, NSButton, NSMutableDictionary, NSString, NSURLRequest, NSView, WCDeepLinkHandler, WebViewA8KeyLogicImpl, WebViewJSLogicImpl;
@protocol WXCustomWebViewControllerDelegate, YYWebViewInterface;

@interface WXBaseWebViewController : MMUIViewController <WebViewA8KeyLogicDelegate, WebViewJSLogicDelegate, MMJSApiVerifyMgrDelegate, YYWebViewDelegate, WXCustomWebViewControllerProtocol>
{
    NSView<YYWebViewInterface> *webView;
    MMURLHandler *m_urlHandler;
    NSButton *m_loadFailView;
    NSMutableDictionary *m_jsInitInfo;
    WCDeepLinkHandler *m_deepLinkHandler;
    MMJSApiVerifyMgr *m_apiVerifyMgr;
    BOOL m_bShowOnNewMainFrameBanner;
    NSMutableDictionary *_dicJsapiGetA8keyHadnleBlocks;
    long long m_loadingCount;
    NSString *m_jump;
    BOOL m_viewDidAppear;
    BOOL m_isPageLoadFail;
    BOOL m_bIFrame;
    BOOL _bIsDraggingScroll;
    BOOL _bIsBackForwardNavigationType;
    NSString *_lastURL;
    BOOL m_isFinishLoaded;
    BOOL _m_bIsSettingInAppBrand;
    BOOL _m_bOfflinePage;
    BOOL _m_bIsJsapiUploadVideoUploading;
    NSMutableDictionary *m_extraInfo;
    WebViewJSLogicImpl *_m_jsLogicImpl;
    NSString *_sourceAppid;
    NSString *_m_initUrl;
    WebViewA8KeyLogicImpl *_m_a8KeyLogicImpl;
    CDUnknownBlockType _m_blockOnWebViewDidTerminate;
    id <WXCustomWebViewControllerDelegate> _m_delegate;
    NSString *_m_lastCheckCpKey;
}

@property(retain, nonatomic) NSString *m_lastCheckCpKey; // @synthesize m_lastCheckCpKey=_m_lastCheckCpKey;
@property(nonatomic) __weak id <WXCustomWebViewControllerDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(nonatomic) BOOL m_bIsJsapiUploadVideoUploading; // @synthesize m_bIsJsapiUploadVideoUploading=_m_bIsJsapiUploadVideoUploading;
@property(copy, nonatomic) CDUnknownBlockType m_blockOnWebViewDidTerminate; // @synthesize m_blockOnWebViewDidTerminate=_m_blockOnWebViewDidTerminate;
@property(readonly, nonatomic) BOOL m_bOfflinePage; // @synthesize m_bOfflinePage=_m_bOfflinePage;
@property(readonly, nonatomic) WebViewA8KeyLogicImpl *m_a8KeyLogicImpl; // @synthesize m_a8KeyLogicImpl=_m_a8KeyLogicImpl;
@property(readonly, nonatomic) NSString *m_initUrl; // @synthesize m_initUrl=_m_initUrl;
@property(retain, nonatomic) NSString *sourceAppid; // @synthesize sourceAppid=_sourceAppid;
@property(nonatomic) BOOL m_bIsSettingInAppBrand; // @synthesize m_bIsSettingInAppBrand=_m_bIsSettingInAppBrand;
@property(retain, nonatomic) WebViewJSLogicImpl *m_jsLogicImpl; // @synthesize m_jsLogicImpl=_m_jsLogicImpl;
@property(retain, nonatomic) NSMutableDictionary *m_extraInfo; // @synthesize m_extraInfo;
@property(retain, nonatomic) NSView<YYWebViewInterface> *webView; // @synthesize webView;
- (void).cxx_destruct;
- (void)enableLongPressDetect;
- (void)keyboardDidShow:(id)arg1;
- (void)removeNotificationObservers;
- (void)initNotificationObservers;
- (void)removeWebViewObservers;
- (void)initWebViewObservers;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidDisappear;
- (void)viewDidLoad;
- (void)kvReportJSCall:(id)arg1 withParam:(id)arg2;
- (id)getJSFunctionDef:(id)arg1;
- (void)diagnose_onJSApiRespForEvent:(id)arg1 result:(id)arg2;
- (void)onPageStateChange:(id)arg1;
- (void)onDomReady;
- (BOOL)isDisableRecordHistory;
- (id)getAuthorizedMonitorEvents:(id)arg1;
- (void)processJSAPICall:(id)arg1 funcDef:(id)arg2 funcBlock:(CDUnknownBlockType)arg3 failHandleBlock:(CDUnknownBlockType)arg4 apiPermission:(unsigned char)arg5;
- (unsigned char)getJSApiPermission:(id)arg1;
- (BOOL)isGetingA8Key;
- (void)onFinishedHandleJSApi;
- (id)getCurrentWebviewViewController;
- (void)willStartGetA8Key;
- (void)saveJSAPIPermissionsInOfflineCache:(id)arg1 url:(id)arg2;
- (void)saveJSAPIPermissions:(id)arg1 url:(id)arg2;
- (void)saveJSAPIAuthInfo:(id)arg1;
- (void)onJumpToEmoticonDetailViewController:(id)arg1;
- (void)onJumpToViewController:(id)arg1;
- (void)onJumpToSafariWithUrl:(id)arg1;
- (void)onUpdatedPermisson;
- (void)onGetA8KeyWithMediaAutoPlay;
- (void)onGetA8Key:(BOOL)arg1 ReqUrl:(id)arg2 Reason:(int)arg3 diagnose:(id)arg4;
- (void)handleJumpProfileUrl:(id)arg1 profileRange:(struct _NSRange)arg2;
- (void)delayHandleUrl:(id)arg1;
- (id)getPreInjectScriptStr;
- (void)handleWebViewVCDismiss;
- (void)cleanJSAPIDelegate;
- (BOOL)isSvrErrorTipForbidden;
- (void)webViewControllerJSApiRespForEvent:(id)arg1 result:(id)arg2;
- (id)webViewControllerBackgroundColor;
- (void)webViewControllerForceSyncA8KeyError;
- (void)webViewControllerDidStartSyncA8Key:(id)arg1;
- (id)webViewControllerPreInjectScriptStr;
- (void)webViewControllerTitleDidChange:(id)arg1;
- (void)webViewControllerContentProcessDidTerminate:(id)arg1;
- (void)webViewController:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webviewControllerDidReceiveScriptMessage:(id)arg1 handler:(id)arg2;
- (void)webViewControllerDidFinishLoad:(id)arg1;
- (void)webViewDidReceiveResponse:(id)arg1;
- (void)webViewControllerDidStartLoad:(id)arg1;
- (BOOL)webViewController:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 isMainFrame:(BOOL)arg4;
- (void)webViewContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webviewDidReceiveScriptMessage:(id)arg1 handler:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (id)getTouchemulatorScriptStr;
- (id)getWXHookScriptStr;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 isMainFrame:(BOOL)arg4;
- (void)logUseWebviewSchemeToJumpWithUrl:(id)arg1;
- (void)startupPreVerifyJSAPI:(id)arg1 failHandleBlock:(CDUnknownBlockType)arg2;
- (void)sendEventToJSBridge:(id)arg1 Param:(id)arg2;
- (void)forceShowCloseButton;
- (void)doJsApiInitEvent;
- (void)setDisableWebAlertView:(BOOL)arg1;
- (BOOL)allowFayByImage;
- (BOOL)allowShareByImage;
- (BOOL)allowScanQRCodeByImage;
- (unsigned int)getCurrentScene;
- (id)extraInfo;
- (id)getInitUrl;
- (id)getCurrentAppId;
- (id)getCurrentUrl;
- (void)goToURL:(id)arg1;
- (void)goForward;
- (void)goBack;
- (BOOL)canGoBack;
- (void)clearScrollBackgroundColor;
- (id)getRequestingOrCurrentUrl;
- (void)setCurrentUrl:(id)arg1;
- (void)markNeedCheckUrlAndRemoveLastCheckedUrl:(id)arg1;
- (void)notifyToJSBridgeVisibilityChanged:(BOOL)arg1;
- (void)startLoadWeb;
- (void)tryStartOutlinkDetect;
- (id)getShareUrl;
- (unsigned char)getPermissionWithName:(id)arg1;
- (void)sendGetA8KeyEvent;
- (id)getUrlPermission:(id)arg1;
- (BOOL)hasUrlPermission:(id)arg1;
- (unsigned int)GetGeneralBitSetForUrl:(id)arg1;
- (BOOL)IsBitsetSet:(unsigned int)arg1 forUrl:(id)arg2;
- (void)internalInitWithUrl:(id)arg1 extraInfo:(id)arg2;
- (id)initWithURL:(id)arg1 extraInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSURLRequest *request;
@property(readonly) Class superclass;

@end

